<nav class="MDCurrencyWrapper">
    <ul>
        <li>
        <a class="selectedCurrency USD" href="javascript:void(0);"></a>
            <ul class="currencyNames" onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
                <li class="language">
                    Please choose your language
                </li>
                <li><a class="USD" href="https://us.md-factor.com/">English</a></li>
                <li><a class="AUD" href="http://au.md-factor.com/">Australian</a></li>
                <li><a class="BRL" href="http://br.md-factor.com/">Portugese</a></li>
                <li><a class="CAD" href="http://ca.md-factor.com/">French</a></li>
                <li><a class="CNY" href="http://ch.md-factor.com/">Chinese</a></li>
                <li><a class="MXN" href="http://mx.md-factor.com/">Mexican</a></li>
            </ul>
        </li>
    </ul>
</nav>