<nav class="MDCurrencyWrapper">
    <ul>
        <li>
        <a class="selectedCurrency USD" href="javascript:void(0);"></a>
            <ul class="currencyNames" onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
                <li class="language">
                    Please choose your language
                </li>
                <li><a class="USD" href="https://md-factor.com/us">English</a></li>
                <li><a class="AUD" href="https://md-factor.com/au">Australian</a></li>
                <li><a class="BRL" href="https://md-factor.com/br">Portugese</a></li>
                <li><a class="CAD" href="https://md-factor.com/ca">French</a></li>
                <li><a class="CNY" href="https://md-factor.com/ch">Chinese</a></li>
                <li><a class="MXN" href="https://md-factor.com/mx">Spanish</a></li>
            </ul>
        </li>
    </ul>
</nav>