<?php
/**
 * Mageplaza_BetterBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 *
 *
 * ===================================================================================
 *   INCLUDE THIS EXTENSION TO YOUR THEMES, PLEASE CONTACT ME AT harrytpps@gmail.com
 * ===================================================================================
 *
 *
 */
?>

<!-- Edited By Rej -->

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_posts = $this->getPosts(); ?>

<div id="FeatureBlogListWrapper">
    <div id="FeaturedSlider" class="owl-carousel">
        <?php if ($_posts->getSize() > 0) : ?>
            <?php foreach ($_posts as $_post) : ?>
                <a class="item link" href="<?php echo $_post->getPostUrl(); ?>">
                    <div class="FeaturedSliderBG" style="background-image: url('<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>');">
                        <div class="overlay">
                            <div class="text">
                                <p><?php echo $_post->getPostTitle(); ?></p>
                            </div>
                        </div>
                    </div>
                </a>
            <?php endforeach; ?>
        <?php endif; ?>  
    </div>
</div>

<div class="BlogContentWrapper">
    <div class="page-title">
        <?php if (Mage::helper('mageplaza_betterblog/post')->isRssEnabled()) : ?>
            <div class="betterblog-rss">
                <a href="<?php echo Mage::helper('mageplaza_betterblog/post')->getRssUrl(); ?>" class="bb-rss-icon">
                    <img src="<?php echo $this->getSkinUrl('images/mageplaza_betterblog/rss.png') ?>" width="16px"/> </a>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($_posts->getSize() > 0) : ?>
        <?php //echo $this->getPagerHtml(); ?>
        <div class="post-list-container">
            <?php foreach ($_posts as $_post) : ?>
                <div class="post-list-item">

                    <a href="<?php echo $_post->getPostUrl(); ?>" class="post-image zoomEffect">
                        <div class="BlogContentBG" style="background-image: url('<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>');"></div>
                    </a>


                    <div class="contentWrapper">
                        <div class="contentInner">
                            <h2 class="mc-post-title">
                                <a href="<?php echo $_post->getPostUrl() ?>">
                                    <?php echo $_post->getPostTitle(); ?>
                                </a>

                                <div class="mc-post-info">
                                    <?php echo $this->__('Posted on'); ?> 
                                    <?php echo Mage::helper('core')->formatDate($_post->getCreatedAt(), 'medium', false) ?> <!-- |
                                    <?php //echo $this->__('Posted in'); ?> <?php //echo $_post->getPostCategoryHtml(); ?>
                                    <?php //if(Mage::helper('mageplaza_betterblog')->canShowCommentCount()) echo '| '. Mage::helper('mageplaza_betterblog')->formatCommentCount($_post->getCommentCount()); ?> -->
                                </div>
                            </h2>

                            <div class="post-short-description">
                                <p><?php echo $_post->getPostExcerpt(); ?><?php echo $this->__('...'); ?> <a class="mc-read-more" href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $this->__('Continue reading'); ?>"><?php echo $this->__('Continue reading'); ?></a></p>
                            </div>

                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <div class="post-list-container">
            <?php echo Mage::helper('mageplaza_betterblog')->__('There are no posts at this moment'); ?>
        </div>
    <?php endif; ?>
</div>


<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/owl.carousel.js"></script>
<script type="text/javascript">
    $('.post-list-item:even').addClass('alt');
</script>
<script>
    $(document).ready(function() {

      $("#FeaturedSlider").owlCarousel({
            items : 3,
            itemsCustom : false,
            itemsDesktopSmall : [980,3],
            itemsTablet: [768,2],
            itemsMobile : [540,1],
            
         
            //Basic Speeds
            slideSpeed : 200,
            paginationSpeed : 800,
            rewindSpeed : 1000,
         
            //Autoplay
            autoPlay : true,
            stopOnHover : true,
         
            // Navigation
            navigation : true,
            navigationText : ["<i class='fa fa-chevron-left' aria-hidden='true'></i>","<i class='fa fa-chevron-right' aria-hidden='true'></i>"],
            rewindNav : true,
         
            //Pagination
            pagination : true,
         
            // Responsive 
            responsive: true,
            responsiveRefreshRate : 200,
            responsiveBaseWidth: window,
         
            Type: Number,
            Default: 5
      });
    });


</script>
