<?php
/**
 * Mageplaza_BetterBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post view template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 *
 *
 * ===================================================================================
 *   INCLUDE THIS EXTENSION TO YOUR THEMES, PLEASE CONTACT ME AT harrytpps@gmail.com
 * ===================================================================================
 *
 *
 */
?>
<?php $_post = $this->getCurrentPost(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-568cdc40e9eab41d" async="async"></script>
<div class="BlogContentWrapper">
    <div class="post-image">
        <?php if ($_post->
        getImage()) : ?> <a href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $_post->
        getPostTitle(); ?>"> <img src="<?php echo mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>" alt="<?php echo $this->
        escapeHtml($_post->getPostTitle()); ?>"/> </a>
        <?php endif; ?>
    </div>

    <div class="contentWrapper">
        <div class="contentInner">
            <h2 class="mc-post-title">
                <a href="<?php echo $_post->getPostUrl() ?>"> <?php echo $_post->
                getPostTitle(); ?> </a>
                <div class="mc-post-info">
                    <?php echo $this->
                    __('Posted on'); ?> <?php echo Mage::helper('core')->
                    formatDate($_post->getCreatedAt(), 'medium', false) ?> 
                </div>
            </h2>
            <div class="post-view">
                <div class="post-post_content">
                    <?php echo $_post->
                    getPostContent(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="post-sharing-button">
        <div class="addthis_sharing_toolbox">
        </div>
    </div>
</div>