<?php $metrics = $this->getMetrics(); ?>
<div class="entry-edit">
<div class="entry-edit-head"><h4><?php echo $this->getHeaderTitle(); ?> (<?php echo $this->getDateRange(); ?>)</h4></div>
<fieldset class="np bold" style="font-size: 14px"><div class="grid np">
	<table cellspacing="0" style="border:0;">
		<col width="25%"><col width="25%"><col width="25%"><col width="25%">
		<tbody>
		<tr>
		<?php $count = 0; ?>
		<?php foreach ($metrics as $metric): ?>
			<?php
				if (($count % 4) == 0 and $count != 0 and $count != (count($metrics) - 1)) echo '</tr><tr>';
			?>
			<td>
				<?php $title = 'value: ' . $metric['value'] . (isset($metric['average_value']) ? '; avg: ' . $metric['average_value'] : '') . '; days: ' . $metric['num_days']; ?>
				<div title="<?php echo htmlspecialchars($title); ?>">
					<?php echo $metric['value']; ?> <span style="font-size:12px; color:#737373; font-weight:normal;"><?php echo $metric['label'] ?></span>
					<?php if (isset($metric['average_value'])): ?>
					/ <span style="color:#737373; font-weight: normal; font-size: 12px;"><?php echo $metric['average_value']; ?> <?php echo $this->__('avg'); ?></span>
					<?php endif; ?>
				</div>
			</td>
			<?php $count++; ?>
			<?php if (($count % 4) == 0 and $count == (count($metrics) - 1)) echo '</tr>'; ?>
		<?php endforeach; ?>
		<?php $left = ($count % 4); ?>
		<?php 
		if ($left > 0) {
			for ($i = (4 - $left); $i > 0; $i--) {
				echo '<td>&nbsp;</td>';
			}
		}
		?>
		</tr>
		</tbody>
	</table>
</div>
</fieldset>
</div>