<!-- append section to header fo category -->
<script>
$("#header").append('<div class="section"><div class="inner"><div class="overlay"><div class="text fadeInUp animated"><p class="title"><span>Physician-formulated</span> Fast-Acting. Real Results.</p></div><a href="#" class="shopNow pinkSolidBtn">SHOP NOW</a><a href="#" class="watchNow pinkHollowBtn">WATCH VIDEO</a></div></div></div>')
$("#header").addClass("forCategory")
$("#topNavi").addClass("whiteVer")
</script>

<div id="categories">
    <ul class="clearfix">
        <li>
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-hair-black.jpg');?>)"></div></div>
                <p><span>Hair</span></p>
            </a>
        </li>
        <li class="alt">
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-lash-factor-black.jpg');?>)"></div></div>
                <p><span>Lash Factor</span></p>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-skin-black.jpg');?>)"></div></div>
                <p><span>Skin</span></p>
            </a>
        </li>
        <li class="alt">
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-wellness-black.jpg');?>)"></div></div>
                <p><span>Wellness</span></p>
            </a>
        </li>
    </ul>
</div><!-- END categories -->

<div id="shop">
    <div class="section clearfix">
        <div id="sidebar">
            <div class="sideNavi">
                <p class="title">SHOP BY CATEGORY</p>
                <ul>
                    <li><a href="#">LASHES</a>
                        <ul>
                            <li><a href="#">Lash Conditioners</a></li>
                            <li><a href="#">Lash and Eyebrow Conditioner</a></li>
                        </ul>
                    </li>
                    <li><a href="#">HAIR</a>
                        <ul>
                            <li><a href="#">Cleansing &amp; Conditioning</a></li>
                            <li><a href="#">Hair Supplements</a></li>
                            <li><a href="#">Scalp Treatments</a></li>
                            <li><a href="#">Value Added Sets</a></li>
                            <li><a href="#">Color &amp; Shine</a></li>
                        </ul>
                    </li>
                    <li><a href="#">SKIN</a>
                        <ul>
                            <li><a href="#">Cleansers &amp; Toners</a></li>
                            <li><a href="#">Serums &amp; Treatments</a><li>
                            <li><a href="#">Anti-Aging Treatments</a></li>
                            <li><a href="#">Eye Treatments</a></li>
                            <li><a href="#">Oily / Acne Prone Treatments</a></li>
                            <li><a href="#">Protection</a></li>
                        </ul>
                    </li>
                    <li><a href="#">WELLNESS</a>
                        <ul>
                            <li><a href="#">Nutri Cleanse</a></li>
                            <li><a href="#">Ultimate Green Capsules</a></li>
                            <li><a href="#">Ultimate Beauty Drink Mix</a></li>
                            <li><a href="#">Adrenal Pro</a></li>
                            <li><a href="#">Intimate Restore</a></li>
                            <li><a href="#">Nutri Hair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            
            <div class="sideNavi">
                <p class="title">SHOP BY CONCERN</p>
                <ul>
                    <li><a href="#">LASHES</a>
                        <ul>
                            <li><a href="#">Thinning Eyebrows</a></li>
                            <li><a href="#">Thinning Lashes</a></li>
                        </ul>
                    </li>
                    <li><a href="#">HAIR</a>
                        <ul>
                            <li><a href="#">Loosing Hair from Stress</a></li>
                            <li><a href="#">Thinning Scalp</a></li>
                            <li><a href="#">Reasons for Hair Loss</a></li>
                            <li><a href="#">Thin Hair</a></li>
                            <li><a href="#">Oily Scalp</a></li>
                            <li><a href="#">Dry Hair</a></li>
                        </ul>
                    </li>
                    <li><a href="#">SKIN</a>
                        <ul>
                            <li><a href="#">Age or Dark Spots</a></li>
                            <li><a href="#">Loss of Firmness</a></li>
                            <li><a href="#">Fine Line and Crows Feet</a></li>
                            <li><a href="#">Acne Marks</a></li>
                            <li><a href="#">Oily Skin</a></li>
                        </ul>
                    </li>
                    <li><a href="#">WELLNESS</a>
                        <ul>
                            <li><a href="#">Detox Antioxidant</a></li>
                            <li><a href="#">Stress and Weight Reduction</a></li>
                            <li><a href="#">Sexual Wellness</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- END sidebar -->
        
        <div id="productListing">
            <ul class="breadcrumb">
                <li><a href="#">Shop</a></li>
                <li><a href="#">MD Hair</a></li>
                <li class="last">Cleansing &amp; Conditioning</li>
            </ul>
            
            <!-- <div class="naviBar">
                <div class="desktopTablet">
                    <div class="pager">
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>
                        
                        <a href="#" class="pagi prev">Prev Page</a>
                        <a href="#" class="pagi next">Next Page</a>
                    </div>
                    
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select>
                            <option>12</option>
                        </select>
                    </div>
                    
                    <div class="sort">
                        <span class="lbl">SORT BY</span>
                        <select>
                            <option>Please Select One</option>
                        </select>
                    </div>                      
                </div>
                
                <div class="mobileOnly">
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select class="showBy">
                            <option>12</option>
                        </select>
                        
                        <select class="sortBy">
                            <option>SORT BY</option>
                        </select>
                    </div>
                    
                    <div class="pager">
                        <a href="#" class="pagi prev">Prev Page</a>
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>   
                        <a href="#" class="pagi next">Next Page</a>                             
                    </div>
                </div>
            </div> --><!-- END navibar -->
            <?php echo $this->getToolbarHtml() ?>
            <div id="shopProducts">
                <div class="category-products">
                
                <!-- <ul>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image01.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    
                </ul> -->
                <!-- start products here -->
                <?php
                    $_productCollection=$this->getLoadedProductCollection();
                    $_helper = $this->helper('catalog/output');

                ?>
                <?php if(!$_productCollection->count()): ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
                <?php else: ?>
                <ul>
                    <?php $_iterator = 0; ?>
                    <?php $_imgSize = 277; ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                            <div class="image">
                                <a href="<?php echo $_product->getProductUrl() ?>" class="inner">
                                    <img 
                                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                    />
                                    <div class="overlay"><span><em>VIEW PRODUCT</em></span></div>
                                </a>
                            </div>
                             <div class="desc">
                                    <a href="#" class="name"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                                    <span class="price"><?php echo $this->getPriceHtml($_product, true) ?></span>
                            </div>
                            
                             <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                <a href="#" class="addCart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></a>               
                             <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                <?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                             <?php else: ?>
                                <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                             <?php endif; ?>
                        </li>
                    <?php endforeach //end product loop ?>
                </ul>
                <?php endif; //checker if no products ?>
                
              
            </div> <!-- end category-products -->   
        </div><!-- END shopProducts -->
          <?php echo $this->getToolbarHtml() ?>    
           
        </div><!-- END productListing -->
    </div>
</div><!-- END shop -->     

<div id="newsletter">
    <div class="section">
        <div class="fields clearfix">
            <div class="field"><input type="text" placeholder="Email" class="textbox"/></div>
            <div class="field"><input type="text" placeholder="Name" class="textbox"/></div>
            <a href="#" class="submitBtn pinkSolidBtn">SUBSCRIBE</a>
        </div>
    </div>
</div><!-- END newsletter -->