<div id="categories">
    <ul class="clearfix">
        <li>
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-hair-black.jpg');?>)"></div></div>
                <p><span>Hair</span></p>
            </a>
        </li>
        <li class="alt">
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-lash-factor-black.jpg');?>)"></div></div>
                <p><span>Lash Factor</span></p>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-skin-black.jpg');?>)"></div></div>
                <p><span>Skin</span></p>
            </a>
        </li>
        <li class="alt">
            <a href="#">
                <div class="image zoomEffect"><div class="pic" style="background-image: url(<?php echo $this->getSkinUrl('images/category-md-wellness-black.jpg');?>)"></div></div>
                <p><span>Wellness</span></p>
            </a>
        </li>
    </ul>
</div><!-- END categories -->

<div id="shop">
    <div class="section clearfix">
        <div id="sidebar">
            <div class="sideNavi">
                <p class="title">SHOP BY CATEGORY</p>
                <ul>
                    <li><a href="#">LASHES</a>
                        <ul>
                            <li><a href="#">Lash Conditioners</a></li>
                            <li><a href="#">Lash and Eyebrow Conditioner</a></li>
                        </ul>
                    </li>
                    <li><a href="#">HAIR</a>
                        <ul>
                            <li><a href="#">Cleansing &amp; Conditioning</a></li>
                            <li><a href="#">Hair Supplements</a></li>
                            <li><a href="#">Scalp Treatments</a></li>
                            <li><a href="#">Value Added Sets</a></li>
                            <li><a href="#">Color &amp; Shine</a></li>
                        </ul>
                    </li>
                    <li><a href="#">SKIN</a>
                        <ul>
                            <li><a href="#">Cleansers &amp; Toners</a></li>
                            <li><a href="#">Serums &amp; Treatments</a><li>
                            <li><a href="#">Anti-Aging Treatments</a></li>
                            <li><a href="#">Eye Treatments</a></li>
                            <li><a href="#">Oily / Acne Prone Treatments</a></li>
                            <li><a href="#">Protection</a></li>
                        </ul>
                    </li>
                    <li><a href="#">WELLNESS</a>
                        <ul>
                            <li><a href="#">Nutri Cleanse</a></li>
                            <li><a href="#">Ultimate Green Capsules</a></li>
                            <li><a href="#">Ultimate Beauty Drink Mix</a></li>
                            <li><a href="#">Adrenal Pro</a></li>
                            <li><a href="#">Intimate Restore</a></li>
                            <li><a href="#">Nutri Hair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            
            <div class="sideNavi">
                <p class="title">SHOP BY CONCERN</p>
                <ul>
                    <li><a href="#">LASHES</a>
                        <ul>
                            <li><a href="#">Thinning Eyebrows</a></li>
                            <li><a href="#">Thinning Lashes</a></li>
                        </ul>
                    </li>
                    <li><a href="#">HAIR</a>
                        <ul>
                            <li><a href="#">Loosing Hair from Stress</a></li>
                            <li><a href="#">Thinning Scalp</a></li>
                            <li><a href="#">Reasons for Hair Loss</a></li>
                            <li><a href="#">Thin Hair</a></li>
                            <li><a href="#">Oily Scalp</a></li>
                            <li><a href="#">Dry Hair</a></li>
                        </ul>
                    </li>
                    <li><a href="#">SKIN</a>
                        <ul>
                            <li><a href="#">Age or Dark Spots</a></li>
                            <li><a href="#">Loss of Firmness</a></li>
                            <li><a href="#">Fine Line and Crows Feet</a></li>
                            <li><a href="#">Acne Marks</a></li>
                            <li><a href="#">Oily Skin</a></li>
                        </ul>
                    </li>
                    <li><a href="#">WELLNESS</a>
                        <ul>
                            <li><a href="#">Detox Antioxidant</a></li>
                            <li><a href="#">Stress and Weight Reduction</a></li>
                            <li><a href="#">Sexual Wellness</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- END sidebar -->
        
        <div id="productListing">
            <ul class="breadcrumb">
                <li><a href="#">Shop</a></li>
                <li><a href="#">MD Hair</a></li>
                <li class="last">Cleansing &amp; Conditioning</li>
            </ul>
            
            <!-- <div class="naviBar">
                <div class="desktopTablet">
                    <div class="pager">
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>
                        
                        <a href="#" class="pagi prev">Prev Page</a>
                        <a href="#" class="pagi next">Next Page</a>
                    </div>
                    
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select>
                            <option>12</option>
                        </select>
                    </div>
                    
                    <div class="sort">
                        <span class="lbl">SORT BY</span>
                        <select>
                            <option>Please Select One</option>
                        </select>
                    </div>                      
                </div>
                
                <div class="mobileOnly">
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select class="showBy">
                            <option>12</option>
                        </select>
                        
                        <select class="sortBy">
                            <option>SORT BY</option>
                        </select>
                    </div>
                    
                    <div class="pager">
                        <a href="#" class="pagi prev">Prev Page</a>
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>   
                        <a href="#" class="pagi next">Next Page</a>                             
                    </div>
                </div>
            </div> --><!-- END navibar -->
            
            <div id="shopProducts">
                <!-- <ul>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image01.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image02.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image03.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image04.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image05.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image01.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image06.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image07.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                    <li>
                        <div class="image"><a href="#" class="inner"><img src="images/product-image08.jpg" alt=""/><div class="overlay"><span><em>VIEW PRODUCT</em></span></div></a></div>
                        <div class="desc">
                            <a href="#" class="name">Nutritional support in times of stress</a>
                            <span class="price">$40.00</span>
                        </div>
                        <a href="#" class="addCart"></a>
                    </li>
                </ul> -->
                <?php
                    $_productCollection=$this->getLoadedProductCollection();
                    $_helper = $this->helper('catalog/output');
                ?>
                <?php if(!$_productCollection->count()): ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
                <?php else: ?>
                <div class="category-products">
                    <?php echo $this->getToolbarHtml() ?>
                    <?php // List mode ?>
                    <?php if($this->getMode()!='grid'): ?>
                    <?php $_iterator = 0; ?>
                    <ol class="products-list" id="products-list">
                    <?php foreach ($_productCollection as $_product): ?>
                        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                            <?php // Product Image ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                
                                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                                        This $_imgSize value could even be decreased further, based on the page layout
                                        (one column, two column, three column) and number of product columns. */ ?>
                                <?php $_imgSize = 100; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                                
                            </a>
                            <?php // Product description ?>
                            <div class="product-shop">
                                <div class="f-fix">
                                    <div class="product-primary">
                                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                        <?php if($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                        <?php endif; ?>
                                        <?php
                                        // Provides extra blocks on which to hang some features for products in the list
                                        // Features providing UI elements targeting this block will display directly below the product name
                                        if ($this->getChild('name.after')) {
                                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                                $_nameAfterChild->setProduct($_product);
                                                echo $_nameAfterChild->toHtml();
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class="product-secondary">
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    </div>
                                    <div class="product-secondary">
                                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                            <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                                        <?php else: ?>
                                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                            <?php endif; ?>
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                    <div class="desc std">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                    </ol>
                    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

                    <?php else: ?>

                    <?php // Grid Mode ?>

                    <?php $_collectionSize = $_productCollection->count() ?>
                    <?php $_columnCount = $this->getColumnCount(); ?>
                    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                        <?php $i=0; foreach ($_productCollection as $_product): ?>
                            <?php /*if ($i++%$_columnCount==0): ?>
                            <?php endif*/ ?>
                            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                    <div class="overlay"><div class="inner"><span><em>VIEW PRODUCT</em></span></div></div>
                                </a>
                                <div class="product-info">
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    <?php
                                    // Provides extra blocks on which to hang some features for products in the list
                                    // Features providing UI elements targeting this block will display directly below the product name
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif; ?>
                                    <div class="actions">
                                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                        
                                    </div>
                                </div>
                            </li>
                            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                            <?php endif*/ ?>
                        <?php endforeach ?>
                    </ul>
                    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
                    <?php endif; ?>

                    <div class="toolbar-bottom">
                        <?php echo $this->getToolbarHtml() ?>
                    </div>
                </div>
                <?php endif; ?>
                <?php
                // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
                if ($this->getChild('after')) {
                    $_afterChildren = $this->getChild('after')->getSortedChildren();
                    foreach ($_afterChildren as $_afterChildName) {
                        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
                        //set product collection on after blocks
                        $_afterChild->setProductCollection($_productCollection);
                        echo $_afterChild->toHtml();
                    }
                }
                ?>
            </div><!-- END shopProducts -->
            
            <!-- <div class="naviBar">
                <div class="desktopTablet">
                    <div class="pager">
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>
                        
                        <a href="#" class="pagi prev">Prev Page</a>
                        <a href="#" class="pagi next">Next Page</a>
                    </div>
                    
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select>
                            <option>12</option>
                        </select>
                    </div>
                    
                    <div class="sort">
                        <span class="lbl">SORT BY</span>
                        <select>
                            <option>Please Select One</option>
                        </select>
                    </div>                      
                </div>
                
                <div class="mobileOnly">
                    <div class="show">
                        <span class="lbl">SHOW</span>
                        <select class="showBy">
                            <option>12</option>
                        </select>
                        
                        <select class="sortBy">
                            <option>SORT BY</option>
                        </select>
                    </div>
                    
                    <div class="pager">
                        <a href="#" class="pagi prev">Prev Page</a>
                        <ul>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>   
                        <a href="#" class="pagi next">Next Page</a>                             
                    </div>
                </div>
            </div> --><!-- END navibar -->
        </div><!-- END productListing -->
    </div>
</div><!-- END shop -->     

<div id="newsletter">
    <div class="section">
        <div class="fields clearfix">
            <div class="field"><input type="text" placeholder="Email" class="textbox"/></div>
            <div class="field"><input type="text" placeholder="Name" class="textbox"/></div>
            <a href="#" class="submitBtn pinkSolidBtn">SUBSCRIBE</a>
        </div>
    </div>
</div><!-- END newsletter -->