<?php
$is_validated=Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_validated');
if($is_validated=='1')
{
$js_code ='<script type="text/javascript" src="https://www.socleversocial.com/dashboard/client_share_js/client_'.Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_siteid').'_share_noautho.js?v='.time().'"></script>'.PHP_EOL.
          '<script>'.PHP_EOL.
          'csauthosharebarjs.init([\''.Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_appid').'\', \''.Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_siteid').'\',\''.Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_appsecret').'\',\''.Mage::getStoreConfig('socialloginsharing_options/apisettings/scsl_validdomain').'\']);'.PHP_EOL.
          'csauthosharebarjs.validateCsApi();'.PHP_EOL.
          '</script>'.PHP_EOL;
               
echo $js_code;
}
?>