<?php $quote = Mage::getSingleton('checkout/session')->getQuote();
	  $store_id = Mage::app()->getStore()->getId();
	  $spend_point = $this->getMaxPointsToCheckout();
	  $earn_rewardpoint = (int)$quote->getEarnRewardpoint();
	  $reward_icon = Mage::helper('rewardpoints/data')->getRewardIconHtml($store_id);
$check = version_compare(Mage::getVersion(),'1.4.0.1','>=');?>
<div id="rewardpoints_box">
<form id="rewardpoints-form" action="<?php echo $this->getUrl('rewardpoints/checkout/rewardPointsPost') ?>" method="post">
    <div class="discount discount-codes box" style="width:300px">
        <?php if($check):?><h2 style="background-image: : none; padding: 0px;"><?php echo $reward_icon.$this->__('Reward points') ?></h2><?php else:?><h4 style="background-image: : none; padding: 0px;"><?php echo $reward_icon.$this->__('Reward points') ?></h4><?php endif;?>
        <div class="discount-form">
        	<ul id="mw_reward_accordion">
		      <li class="mw_reward_section">
		        <div <?php if (!sizeof($this->getRewardPointsRule())) echo "style=\"display:none\"";?> ><span id="reward-points-rules-title" style="color: #0A263C;line-height: 1.5;"><?php echo $this->__("You will be awarded <b>%s</b>",Mage::helper('rewardpoints')->formatPoints($earn_rewardpoint,$store_id)." ")?><a id = "mw_view" class="mw_reward_title" style="color: #DC6809 !important;font-weight: bold" href="#"><?php echo $this->__('(Hide)');?></a></span></div>
		        <div id="reward-points-rules" class="mw_reward_toggle" style="margin-top: 5px;">
		        	<?php foreach($this->getRewardPointsRule() as $rule):?>
		        	<div style="width:100%;padding-left:10px; margin: 0 0 5px 0; overflow: hidden;">
		        		<div style="float:left;font-size: 12px; width:280px"><?php echo $this->__('<span style="float: left;">+</span> <div style="margin: 0px 0px 0px 10px;">%s %s</div>',($rule['qty']>1?$rule['qty']." x":""),$rule['message']);?></div>
		        	</div>
		        	<?php endforeach;?>
		        </div>
		      </li>
		    </ul>
        	<?php $rate = $this->getPointPerMoney($store_id);?>
        	<div style="width:100%;">
        	<?php if($this->_getCustomer()->getId()):?>
	        	
	        	
	        	<div style="float:left;width:265px;">
	        		<div style="font-size: 12px; margin-top:5px;"><?php echo $this->__("You have <b>%s</b> available (<b>%s</b> = <b>%s</b>)",Mage::helper('rewardpoints')->formatPoints($this->getCurrentRewardPoints(),$store_id),Mage::helper('rewardpoints')->formatPoints($rate[0],$store_id), $this->formatMoney($rate[1]))?></div>
	        		<h5 style="padding-bottom:10px;"></h5>
	        		<?php /*?><label><?php echo $this->__("Slide to specify number of points to redeem")?></label><?php */?>
	        		<div class="slider_contaner" style="width: 225px;">
	        			<div id="decr_handle"></div>
	        			<div id="incr_handle"></div>
	        			<div id="mw_slider"></div>
	        		</div>
	        		<div style="margin: 15px 0 5px 0;"><label for="amount" style="float:left;margin-right: 5px;"><?php echo $this->__("Points to redeem")?> </label><input style="color:#f6931f; width:50px; text-align:center;font-size: 13px;font-weight: bold;" type="text" name="amount" id="amount" /> <label id="label_amount" style="color:#f6931f; font-weight:bold;display:none;"></label></div>
	        		<div style="clear:both;"><input  type="checkbox" name="use_max_points" id="use_max_points" style="float:left;margin-right: 5px;" /><label for="use_max_points" style="padding-left: 5px;"> <?php echo $this->__("Use maximum (<b>%s</b>)",Mage::helper('rewardpoints')->formatPoints($spend_point,$store_id));?></label></div>
				</div>
		         <?php else:?>
		         <div style="text-align: center; margin-top:10px;border-top: 1px dashed;padding-top: 10px;"><?php echo $this->__("Please <a href='%s'>LOGIN</a> to use reward points", Mage::getUrl('customer/account/login'))?></div>
	            <?php endif;?>
            </div>
            <div style="clear:both;"></div>
		</div>
	</div>
</form>
<div style="clear:both;"></div>
<!-- 
<div style="width:100%;padding-top:10px; padding-bottom:20px; border-top: 1px dashed #333;"></div> -->

</div>
<?php 
$point = $quote->getMwRewardpoint();
$step = Mage::helper('rewardpoints/data')->getPointStepConfig($store_id);
$min = (int)Mage::helper('rewardpoints/data')->getMinPointCheckoutStore($store_id);

?>
<script type="text/javascript">
document.observe('dom:loaded', function(){
    
    // simple
    accordion = new Accordion('mw_reward_accordion', { startHidden: true });
});

var slider_ajax_timeout = 1000;
var slider_ajax_timeout_new = 3000;
var slider_runing = false;
var timer;
var value_buffer;
$mw_rewardpoints(function() {
	$mw_rewardpoints("#mw_slider").slider({
		value:<?php echo $this->getRewardPoints()?$this->getRewardPoints():0;?>,
		min: 0,
		max:<?php echo $this->getMaxPointsToCheckout()?>,
		step:<?php echo $step?>,
		slide: function(event, ui) {
			$mw_rewardpoints("#amount").val(ui.value);
			$mw_rewardpoints("#label_amount").html(ui.value);

			if(ui.value != <?php echo $this->getMaxPointsToCheckout()?>)
				$mw_rewardpoints("#use_max_points").attr("checked",false);
			else 
				$mw_rewardpoints("#use_max_points").attr("checked",true);
			slider_runing = true;
			runTimer();
		},
		animate: 1000
	});

	$mw_rewardpoints("#incr_handle").click(function(){
		if($mw_rewardpoints("#mw_slider").slider("value") < <?php echo $this->getMaxPointsToCheckout()?>){
			$mw_rewardpoints("#mw_slider").slider("value", $mw_rewardpoints("#mw_slider").slider("value") + <?php echo $step?>);
			updateAmount();
		}
	});

	
	$mw_rewardpoints("#decr_handle").click(function(){
		if($mw_rewardpoints("#mw_slider").slider("value") > 0){
			$mw_rewardpoints("#mw_slider").slider("value", $mw_rewardpoints("#mw_slider").slider("value") - <?php echo $step?>);
			//updateAmount();
			$mw_rewardpoints("#amount").val($mw_rewardpoints("#mw_slider").slider("value"));
			$mw_rewardpoints("#label_amount").html($mw_rewardpoints("#mw_slider").slider("value"));
			setUnsetCheckBox();
			runTimer();
		}
	});

	
	$mw_rewardpoints("#use_max_points").click(function(){
		if(this.checked)
			$mw_rewardpoints("#mw_slider").slider("value",<?php echo $this->getMaxPointsToCheckout()?>);
		else
			$mw_rewardpoints("#mw_slider").slider("value",0);
		updateAmount();
	});
	
	

	$mw_rewardpoints("#amount").keydown(function(event) {
        // Allow only backspace and delete
        if ( event.keyCode == 46 || event.keyCode == 8 ) {
                // let it happen, don't do anything
        }
        else {
                // Ensure that it is a number and stop the keypress
                if (event.keyCode < 48 || event.keyCode > 57 ) {
                    //event.preventDefault();
                }       
        }
    });

	$mw_rewardpoints("#amount").keyup(function(event) {
		//if ((event.keyCode >= 48 && event.keyCode <= 57) || event.keyCode == 46 || event.keyCode == 8 ) {
			if(this.value <= <?php echo $this->getMaxPointsToCheckout()?>){
				setUnsetCheckBox();
				$mw_rewardpoints("#mw_slider").slider("value",this.value);
				runTimerNew();
			}else
			{
				this.value = <?php echo $this->getMaxPointsToCheckout()?>;
				$mw_rewardpoints("#mw_slider").slider("value",<?php echo $this->getMaxPointsToCheckout()?>);
				setUnsetCheckBox();
				runTimerNew();
			}
		//}
	});
	
	//updateRewardPointsAmount();
	updateAmount(true);
});

function updateAmount(noAjax)
{
	var point = <?php echo $point?>;
	$mw_rewardpoints("#amount").val($mw_rewardpoints("#mw_slider").slider("value"));
	if(point && $mw_rewardpoints("#amount").val() == 0){
		 $mw_rewardpoints("#amount").val(point);
		 $mw_rewardpoints("#mw_slider").slider("value",point);
	}
	$mw_rewardpoints("#label_amount").html($mw_rewardpoints("#mw_slider").slider("value"));
	setUnsetCheckBox();
	if(!noAjax)
		runTimer();
}

function setUnsetCheckBox()
{
	if($mw_rewardpoints("#amount").val() != <?php echo $this->getMaxPointsToCheckout()?>)
		$mw_rewardpoints("#use_max_points").attr("checked",false);
	else 
		$mw_rewardpoints("#use_max_points").attr("checked",true);
}

function runTimer()
{
	clearTimeout(timer);
	timer = setTimeout("updateRewardPoints();",slider_ajax_timeout);
}

function runTimerNew()
{
	clearTimeout(timer);
	timer = setTimeout("updateRewardPoints();",slider_ajax_timeout_new);
}

function updateRewardPoints()
{
	slider_runing = false;
	var amount = $mw_rewardpoints("#amount").val();
	amount = parseInt(amount/<?php echo $step?>) * <?php echo $step?>;

	if(amount < <?php echo $min?>) amount = 0;
	
	$mw_rewardpoints("#amount").val(amount);
	$mw_rewardpoints('#label_amount').html(amount);
	$mw_rewardpoints("#shopping-cart-totals-contaner").html($mw_rewardpoints("#shopping-cart-totals-please-wait").html());
	$mw_rewardpoints.ajax({
		type: "POST",
		url: '<?php echo Mage::getUrl('rewardpoints/checkout/rewardpointspost',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>',
		data: "rewardpoints="+$mw_rewardpoints("#amount").val(),
	    success: function(data) {
			$mw_rewardpoints('#shopping-cart-totals-contaner').html(data);
			updateRules();
		}
	});
}

function updateRules()
{
	$mw_rewardpoints("#reward-points-rules").html($mw_rewardpoints("#shopping-cart-totals-please-wait").html());
	$mw_rewardpoints.ajax({
		type: "POST",
		url: '<?php echo Mage::getUrl('rewardpoints/checkout/updaterules',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>',
		data: "rewardpoints="+$mw_rewardpoints("#amount").val(),
	    success: function(data) {
			if(data)
				$mw_rewardpoints("#reward-points-rules-title").css("display","block");
			else
				$mw_rewardpoints("#reward-points-rules-title").css("display","none");
			$mw_rewardpoints('#reward-points-rules').html(data);
		}
	});
}

function updateRewardPointsAmount()
{
	$mw_rewardpoints.ajax({
		type: "GET",
		url: '<?php echo Mage::getUrl('rewardpoints/checkout/rewardpoints',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>',
	    success: function(data) {
			$mw_rewardpoints('#label_amount').html(data);
			$mw_rewardpoints("#amount").val(data);
		}
	});
}
</script>

