<!DOCTYPE html>
<html>
<head>
	<title>MD About Us</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="aboutus CustomCategoryPage">

<div class="VideoWrapper">
    <div class="overlay">
        <div class="overlay__inner">
        	<div class="transparentNav">
	           <div class="normalpageNav">
					<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/topnavigation.phtml')->toHtml(); ?>
				</div>
	        </div>
            <div class="content">
                <div class="custom-container">
                    <div class="left">
                    	<img src="<?php echo $this->getSkinUrl('images/aboutus/header-about-bottles.png') ?>" />
                    </div>
                    <div class="right">
                    	<h1>
	                       	WE CREATE BEAUTY
	                    </h1>
	                    <span>
	                       	...The MD Way!
	                    </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="contentWrapper">
	<div id="intro">
		<div class="custom-container">
			<p>MD is a collection of innovative hair, skin and wellness products utilizing the latest anti-aging technology. The products are created by a board-certified surgeon, physician and expert in the field of medical aesthetics, Dr. Susan Lin.</p>
			<img src="<?php echo $this->getSkinUrl('images/aboutus/intro-products.png') ?>" alt=""/>
		</div>
	</div>

	<div id="founder">
		<div class="custom-container">
			<div class="image wow fadeIn animated">
				<img src="<?php echo $this->getSkinUrl('images/aboutus/founder-image.jpg') ?>" alt=""/>
			</div>
			<div class="desc wow fadeInRight animated">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about-susan-about-us')->toHtml(); ?>
			</div>
		</div>
	</div>
	<div id="feedback">
		<div class="custom-container">
			<blockquote class="fadeInUp wow animated">
				<span class="quote open">“</span>
					Because I had hair problems, and was unsatisfied with current choices. I was motivated to develop simple and nature-inspired products specifically for this important issue.
				<span class="quote close">”</span>
			</blockquote>
		</div>
	</div>

	<div id="videoAbout">
		<a href="https://www.youtube.com/watch?v=xiIIqeHHY-c" data-lity="" class="wow fadeInUp animated">
			<span>
				<img src="<?php echo $this->getSkinUrl('images/aboutus/video-play-btn.png') ?>" />
			</span>
		</a>
	</div>


	<div id="ourProducts">
		<div class="custom-container">
			<ul>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
				<li>
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</li>
			</ul>

			<div class="ctaWrapper">
				<a href="<?php echo mage::app()->getStore()->getHomeUrl(); ?>categories"> <span>
				Shop Now </span>
				</a>
			</div>
		</div>
	</div>

	<div id="moreAbout">
		<div class="titleBar">
			<div class="custom-container">
				<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/more-about-pic.png" alt=""/>
				<span>More About Dr. Susan Lin</span>
			</div>
		</div>

		<div class="custom-container">
			<ul>
				<li>
					<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/about-graduate-ico.png" class="wow fadeInLeft animated">
					<span class="wow fadeInRight animated">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('more-about-susan-first-about-us')->toHtml(); ?>
					</span>
				</li>

				<li>
					<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/about-expertise-ico.png" class="wow fadeInLeft animated">
					<span class="wow fadeInRight animated">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('more-about-susan-second-about-us')->toHtml(); ?>
					</span>
				</li>

				<li>
					<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/about-current-job-ico.png"class="wow fadeInLeft animated">
					<span class="wow fadeInRight animated">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('more-about-susan-third-about-us')->toHtml(); ?>
					</span>
				</li>

				<li>
					<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/about-author-ico.png" class="wow fadeInLeft animated">
					<span class="wow fadeInRight animated">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('more-about-susan-fourth-about-us')->toHtml(); ?>
					</span>
				</li>

				<li>
					<img src="https://md-factor.com/blog/wp-content/themes/mdfactor/images/about-award-ico.png" class="wow fadeInLeft animated">
					<span class="wow fadeInRight animated">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('more-about-susan-fifth-about-us')->toHtml(); ?>
					</span>
				</li>
			</ul>
		</div>
	</div>

	<div id="gallery">
		<div class="custom-container">
			<h1>MD Gallery</h1>
		</div>

		<div class="contentWrapper">
			<div class="imageWrapper Desktop">
				<div class="left">
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</div>
				<div class="middle">
					<div class="inner">
						<div class="side">
						 	<div class="image-box">
							  	<div class="image">
							  	</div>
							</div>  
						</div>
						<div class="side">
						 	<div class="image-box">
							  	<div class="image">
							  	</div>
							</div>  
						</div>
					</div>
					<div class="inner">
						<div class="side">
						 	<div class="image-box">
							  	<div class="image">
							  	</div>
							</div> 
						</div>
						<div class="side">
						 	<div class="image-box">
							  	<div class="image">
							  	</div>
							</div> 
						</div>
					</div>
				</div>
				<div class="right">
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>
				</div>
			</div>

			<div class="imageWrapper Mobile" style="display: none;">
				<div class="mobileImage">
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</div>
				
				<div class="mobileImage">
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</div>

				<div class="mobileImage">
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
					<div class="image-box">
					  	<div class="image">
					  	</div>
					</div>  
				</div>
			</div>
		</div>
	</div>

	<div id="joinUs">
		<div class="custom-container">
			<h1>Join us #theMDway</h1>
		</div>
	</div>

	<div id="inThePress">
		<div class="custom-container">
			<h1>
				In the press
			</h1>
			<div class="ctaWrapper">
				<a href="https://md-factor.com/blog/press/"> 
					<span>
						View all
					</span>
				</a>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('footer') ?>

</body>
</html>