<!DOCTYPE html>
<html>
<head>
	<title>MD Careers</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="careers">

<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/custom-top-menu.phtml')->toHtml(); ?>

<div class="contentWrapper">
	<div class="custom-container">
		<center>
		<h2>BUSINESS OPERATIONS MANAGER</h2>
		</center>
		<strong>Description:</strong>
		<ul>
			<li>
			Oversee development of new anti-aging and medical clinic that will include on-site clinical research facility, aesthetic dermatology, and medical anti-aging facility. </li>
			<li>
			Manage incoming international aesthetic tourism and marketing team. </li>
			<li>
			Complete product registration for Brazil, ASEAN and EU countries. </li>
			<li>
			Manage development and clinical testing projects for medical device and personal care products. </li>
			<li>
			Lead marketing and social media team, aimed at growing chain pharmacy and direct-to-consumer sales. </li>
			<li>
			License Xemilofiban to suitable Chinese pharmaceutical company for clinical testing, manufacture, and successful SFDA registration. </li>
			<li>
			Develop and manage ongoing projects with Chinese and Singaporean drug and cosmetic business partners. </li>
			<li>
			Complete negotiations with Alibaba and develop successful international business e-commerce platform. </li>
			<li>
			Provide consultation to business partners on relevant strategic/operational considerations. </li>
		</ul>
		<p>
			<strong>Note:</strong> This position supervises one (1) Branding/Marketing Consultant, one (1) Social Media Consultant, one (1) Logistics employee, one (1) Operations employee, one (1) E-Commerce employee, one (1) Patient Education Coordinator, one (1) Public Relations employee, and one (1) Webmaster employee.
		</p>
		<strong>Requirements: </strong><br/>
		<ul class="req">
			<li>Master's Degree in Business Administration plus 24 months experience as a Business Operations Manager.</li>
			<li>Must be experienced in Medical Aesthetic facility management.</li>
			<li>Must be experienced in drug development and regulatory approval processes.</li>
			<li>Requires travel and/or relocation to various unanticipated locations for sales, supervision of manufacturers, marketing, and contract negotiations.</li>
		</ul>
		<div class="row">
			<div class="col-xs-6">
				<p>
					<strong>Job location:</strong><br/> 448 N. San Mateo Dr., Suite 1<br/>
					San Mateo, CA 94401
				</p>
			</div>
			<div class="col-xs-6">
				<p>
					<strong>Contact:</strong><br/> 448 N. San Mateo Dr., Suite 1<br/>
					San Mateo, CA 94401<br/>
					Attn: Susan Lin
				</p>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('footer') ?>

</body>
</html>