<!DOCTYPE html>
<html>
<head>
	<title>MD Categories</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="CustomCategoryPage CustomCategories">

<div class="VideoWrapper">
	<div id="video-container">
        <video preload="auto" autoplay loop muted controls="true" width="1440" height="810">
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/hair-category.mp4" type="video/mp4">  
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/hair-category.webm" type="video/webm"> 
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/hair-category.ogg" type="video/ogg">  
        </video>
    </div>
    
    <div class="overlay">
        <div class="overlay__inner">
        	<div class="transparentNav">
	           <nav class='main-nav' id="main-navWrapper">
	            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/topBar.phtml')->toHtml(); ?>
	                <div class="custom-container navi">
	                    <a class="logo" href='<?php echo mage::getbaseurl(); ?>'> 
	                        <img class="whitelogo" src="<?php echo $this->getSkinUrl('images/logo-blue.png') ?>"> 
	                        <img class="darklogo" src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>" style="display: none;"> 
	                    </a>
	                    <div class="MDnav">
	                        <ul>
	                             <?php
	                            $obj = new Mage_Catalog_Block_Navigation();
	                            $storeCategories = $obj->getStoreCategories();
	                            Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
	                            $limit_category = 4;
	                            $ctr = 1;

	                            foreach ($storeCategories as $_category):
	                            if($ctr <= $limit_category) :
	                        ?>
	                    <li> 

	                        <a href="<?php echo Mage::app()->getStore()->getHomeUrl().$_category->getUrlKey(); ?>">
	                        
	                        <?php
	                            $_category = Mage::getModel('catalog/category')->load($_category->getId());
	                        ?>
	                        <?php echo $_category->getName(); ?></a>
	                        <ul>
	                        <?php 
	                            
	                            
	                                $_subcategories = $_category->getChildrenCategories();
	                                if (count($_subcategories) > 0){    

	                                    foreach($_subcategories as $_subcategory){
	                                        //load products now
	                                    $products = Mage::getModel('catalog/category')->load($_subcategory->getId())
	                                     ->getProductCollection()
	                                     ->addAttributeToSelect('*')
	                                     ->addAttributeToFilter('status', 1)
	                                     ->addAttributeToFilter('visibility', 4)
	                                     ->setOrder('price', 'ASC');
	                                         echo '
	                                         <li><a href="'.$_subcategory->getUrl().'">'.$_subcategory->getName().'</a>';
	                                         if (count($products) > 0){    

	                                            echo '<ul>';
	                                            foreach($products as $_product){
	                                               echo '<li>
	                                                    <a class="thirdlevel" href="'.$_product->getProductUrl().'">
	                                                    <div class="image">
	                                                        <img src="'.$_product->getImageUrl().'">                                                    
	                                                    </div>
	                                                    <div class="desc">'.$_product->getName().'</div>
	                                                    </a>
	                                                </li>';
	                                            }
	                                                
	                                            echo '</ul>';
	                                        }
	                                         echo '</li>';
	                                    }// end foreach subcat
	                                }// end if count sub
	                            
	                        ?>      
	                         </ul>
	                        </li>
	                        <?php  $ctr++; endif;   endforeach; ?>   

	                            <li><a href="<?php echo Mage::getBaseUrl(); ?>sales">Sale</a></li>
	                            <li>
                                    <a href="http://md-factor.com/about/">Brand</a>
                                    <ul class="brandDropdown">
                                       <li>
                                            <a href="https://md-factor.com/about/">About Us</a>
                           	            </li>
                                        <li>
                                            <a href="https://md-factor.com/blog/">Blog</a>
                                        </li>
                                        <li>
                                            <a href="https://md-factor.com/pressmedia">Media</a>
                                        </li>
                                    </ul>
                                </li>
	                        </ul>
	                    </div>

	                    <div class="searchWrapper desktopSearcWrapper">
	                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('currency/currency.phtml')->toHtml(); ?>
	                                    
	                        <div id="searchInner" > 
	                            <form onsubmit="return check_small_search_form()" method="get" action="<?php echo Mage::getUrl('catalogsearch/result')?>">
	                                
	                                <button value="" type="submit">
	                                    <i class="fa fa-search" aria-hidden="true"></i>
	                                </button>
	                                
	                                <input placeholder="SEARCH PRODUCTS" class="query" "search_query"="" name="q" type="text">
	                            </form>
	                        </div> 
	                    </div>
	                </div>
	            </nav>
	        </div>
            <div class="content">
                <div class="custom-container">
                    <h1>
                        FAST ACTING
                    </h1>
                    <span>
                        Real Results.
                    </span>

                    <div class="ctaWrapper">
                        <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            Watch Video
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="customCategory">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('categories_list')->toHtml(); ?>
</div>

<?php echo $this->getChildHtml('footer') ?>

</body>
</html>