<!DOCTYPE html>
<html>
<head>
    <meta property="og:image" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/hairkit-bundle/fb-thumb-hairkitbundle.jpg" />
    
    <meta property="og:image:secure_url" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/hairkit-bundle/fb-thumb-hairkitbundle.jpg" />

    <title>Clear Skin</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />


    <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/guruu_LP9.css" type="text/css" />

    
    <!-- BEGIN GOOGLE ANALYTICS CODE -->
    <script type="text/javascript">
        //<![CDATA[
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-89987290-1']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        //]]>
    </script>
    <!-- END GOOGLE ANALYTICS CODE -->
        
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '1010013549017189');
        fbq('track', "PageView");
    </script>
    
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1010013549017189&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

</head>

<body class="clear-skin">
<?php $homeurl = Mage::app()->getStore()->getHomeUrl(); ?>
<?php $_product = Mage::registry('current_product'); ?>
<?php //$_productID = $_product->getId(); ?>
<?php $_productID = 121 ?>
<?php $formkey = Mage::getSingleton('core/session')->getFormKey(); ?>
<?php $cartUrl = $homeurl.'checkout/cart/add/product/'.$_productID.'/qty/1/?bundle_option[43]=48&form_key='.$formkey.'' ?>
<script type="text/javascript" src="js/lib/jquery/jquery-1.10.2.js"></script>
<div class="TopWrapper">
    <div class="custom-container">
        <p>
            <i class="fa fa-phone" aria-hidden="true"></i> Contact Us | 1-888-882-5788
        </p>
        <p>
            <i class="fa fa-truck" aria-hidden="true"></i> FREE US SHIPPING | USE CODE: FREESHIPPING
        </p>
    </div>
</div>


<div id="headerWrapper">
    <nav class='main-nav' id="main-navWrapper">
        <div class="custom-container">
            <ul class='main-nav'>
                <li>
                    <a href='<?php echo Mage::getBaseUrl(); ?>'>
                        <img src="<?php echo $this->getSkinUrl('images/guruu/logo.png') ?>">
                    </a>
                </li>
                <li>
                    <a href='#description'>
                        What is MD Skin
                    </a>
                </li>
                <li>
                    <a href='#description'>
                        How does it work
                    </a>
                </li>
                <li>
                    <a href='https://md-factor.com/shipping-policy/'>
                        satisfaction guarantee
                    </a>
                </li>
                <li>
                    <a href="<?php echo $cartUrl; ?>" class="buynow">
                        Buy now
                    </a>
                    <div id="popupTest" class="lity-hide" style="display: none;">
                        <div class="inner">
                            <p>
                                Sorry this bundle is currently available for US customers only.
                            </p>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="https://www.addtoany.com/share" class="share a2a_dd" style="display: none;">
                        Share
                    </a>
                </li>

            </ul>
            <a href='#' id='openup'>
                <img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>">
            </a>

            <span>
                <a href="https://www.addtoany.com/share" class="share a2a_dd">
                    <i class="fa fa-reply" aria-hidden="true"></i> Share
                </a>
            </span>
        </div>
    </nav>

    <div class="custom-container">
        <div class="inner">
            <div class="content">
                <h1>
                    Clear Skin
                </h1>

                <p>
                    FLAWLESS CLEAR BLEMISH-FREE SKIN
                <br>
                    WIN FIGHT WITH ACNE WITH MD
                </p>
               
                <div class="cta">
                    <a href="<?php echo $cartUrl; ?>">
                        Order Yours Now
                    </a>
                    <div id="popupTest" class="lity-hide" style="display: none;">
                        <div class="inner">
                            <p>
                                Sorry this bundle is currently available for US customers only.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="hanging-products">
                <div>
                    <img src="<?php echo $this->getSkinUrl('images/guruu/LP9/productPhotos/flawless-factor.png') ?>" class="wow fadeInDown animated" data-wow-delay="2s">
                </div>

                <div>
                    <img src="<?php echo $this->getSkinUrl('images/guruu/LP9/productPhotos/complexion-factor-starter-kit.png') ?>" class="wow fadeInDown animated" data-wow-delay="1s">
                </div>
            </div>
        </div>
    </div>
</div>

<div id="FreeShipping">
    <div class="custom-container">
        <h1>
            FREE SHIPPING 
        </h1>
        <p>
            PLUS FREE SAMPLE WITH FIRST ORDER
        </p>
        <div>
            <a href="<?php echo $cartUrl; ?>">
                SUBSCRIBE NOW
            </a>
            <div id="popupTest" class="lity-hide" style="display: none;">
                <div class="inner">
                    <p>
                        Sorry this bundle is currently available for US customers only.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="bundleWrapper">
    <div class="custom-container">
        <div class="imageWrapper">
            <div class="inner">
                <div>
                    <img src="<?php echo $this->getSkinUrl('images/guruu/LP9/productPhotos/flawless-factor.png') ?>" class="wow fadeInLeft animated" data-wow-delay="2s">
                </div>

                <div>
                    <img src="<?php echo $this->getSkinUrl('images/guruu/LP9/productPhotos/complexion-factor-starter-kit.png') ?>" class="wow fadeInLeft animated" data-wow-delay="1s">
                </div>
            </div>
        </div>

        <div class="content">
            <p class="para"> 
                CLEAR
            </p>
            <h1>
                SKIN
            </h1>
            <p>
                Battle acne with Clear Skin B bundle
            </p>

            <div class="price">
                <span>$110</span>
                <p>
                    $70
                </p>
            </div>

            <strong>
                Bundle Includes:    
            </strong>

            <ul>
                <li>
                   MD Complexion Factor Starter Kit ($70.00)
                </li>
                <li> 
                    MD Flawless Factor ($40.00)
                </li>
            </ul>

            <div class="cta">
                <a href="<?php echo $cartUrl; ?>">
                    Order Now
                </a>
                <div id="popupTest" class="lity-hide" style="display: none;">
                    <div class="inner">
                        <p>
                            Sorry this bundle is currently available for US customers only.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="AsSeenIn">
    <div class="custom-container">
        <h2>
            As Seen In
        </h2>
        <div id="AsSeenInSlider" class="owl-carousel">
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/guruu/cosmopolitan-logo.png') ?>">
            </a>
            <a class="item">
                <img class="intimate" src="<?php echo $this->getSkinUrl('images/guruu/marie-claire-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/guruu/the-new-york-times-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/guruu/allure-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/guruu/womens-health-logo.png') ?>">
            </a>
        </div>
    </div>
</div>

<div id="description">
    <div class="custom-container desktop">
        <div class="left">
            <div class="inner">
                <h2>
                 How it works?
                </h2>
                <strong>
                MD ACNE CONTROL CREAM
                </strong>
                <p>
                   Cleanse the skin thoroughly before applying this product. Put a thin layer on affected area one to two times daily. If bothersome dryness or peeling occurs, reduce application to once a day or once every other day.  
                </p>
                <strong>
                MD EXFOLIATING CLEANSER
                </strong>
                <p>
                    Use morning and night. Apply a small amount to the palm of the hand, rub hands together, and gently massage onto the face for 20 seconds. Avoid the eye area. Rinse thoroughly with lukewarm water, and pat dry.
                </p>
                <strong>
                    MD SEAWEED GEL MOISTURIZER
                </strong>
                <p>
                    Apply all over face. Use once or twice daily.
                </p>
            </div>
                
            <div>
                <a class="add-to-bag" href="<?php echo $cartUrl; ?>">
                    <img src="<?php echo $this->getSkinUrl('images/guruu/bag.png') ?>">
                    Add to bag
                </a>
                <div id="popupTest" class="lity-hide" style="display: none;">
                    <div class="inner">
                        <p>
                            Sorry this bundle is currently available for US customers only.
                        </p>
                    </div>
                </div>

                <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-1.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-1.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-2.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-2.jpg') ?>">
                    </a> 
                </div> 
            </div>

            <div class="vid">
                <div class="inner">
                    <a href="https://www.youtube.com/watch?v=k4UXtfU8KcQ" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-container mobile" style="display: none;">

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-1.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-1.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-2.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/guruu/skin/ba/BandA-2.jpg') ?>">
                    </a> 
                </div> 
            </div>
        </div>
        <div class="left">
            <div class="inner">
                <h2>
                    How it works?
                </h2>
                <strong>
                    MD ACNE CONTROL CREAM
                </strong>
                <p>
                   Cleanse the skin thoroughly before applying this product. Put a thin layer on affected area one to two times daily. If bothersome dryness or peeling occurs, reduce application to once a day or once every other day.  
                </p>
                <strong>
                    MD EXFOLIATING CLEANSER
                </strong>
                <p>
                    Use morning and night. Apply a small amount to the palm of the hand, rub hands together, and gently massage onto the face for 20 seconds. Avoid the eye area. Rinse thoroughly with lukewarm water, and pat dry.
                </p>
                <strong>
                    MD SEAWEED GEL MOISTURIZER
                </strong>
                <p>
                    Apply all over face. Use once or twice daily.
                </p>
            </div>

            <div>
                <a class="add-to-bag" href="<?php echo $cartUrl; ?>">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/bag.png') ?>">
                    Add to bag
                </a>
                <div id="popupTest" class="lity-hide" style="display: none;">
                    <div class="inner">
                        <p>
                            Sorry this bundle is currently available for US customers only.
                        </p>
                    </div>
                </div>

                <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ingredients">
    <div class="custom-container">
        <div class="left">
            <p>
                key

                <span>
                    ingredients
                </span>
            </p>
        </div>

        <div class="right">
            <div class="inner wow zoomIn animated" data-wow-delay="1s">
                <div></div>
                <p>
                    WITCH HAZEL
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="2s">
                <div></div>
                <p>
                    CAVIAR EXTRACT
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="3s">
                <div></div>
                <p>
                    PROPOLIS
                </p>
            </div>
        </div>
    </div>
</div>

<div id="testimonial">
    <div class="custom-container">
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
               Tried this product to help with detox. Noticed my stubborn acne for many years finally cleared after one month. I will continue using the product.
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-1.jpg') ?>">
                    <a href="javascript:void(0);">
                        Cyndi W
                    </a>
                </span>
            </div>
        </div>
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
                My skin improves on the overall and becomes less dry after taking the product.
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-2.jpg') ?>">
                    <a href="javascript:void(0);">
                        Peggy J.
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>
       

<div id="promo">
    <div class="custom-container">
        <div class="left wow fadeInUp animated" data-wow-delay="0.5s">
        </div>
        <div class="middle">
            <h1>
                SIGN UP FOR FREE SHIPPING
            </h1>
            <p>
                OVER 1 MILLION CUSTOMERS WORLDWIDE
            </p>
            <!-- <form>
                <input type="text" name="Email" placeholder="EMAIL">
                <a href="javascript:void(0);">
                    Become a MD Friend
                </a>
            </form> -->

            
<div class="ctct-embed-signup">
   <div>
       <span id="success_message" style="display:none;">
           <div style="text-align:center;">Thanks for signing up!</div>
       </span>
       <form data-id="embedded_signup:form" class="ctct-custom-form Form" name="embedded_signup" method="POST" action="https://visitor2.constantcontact.com/api/signup">
          
           <p></p>
           <!-- The following code must be included to ensure your sign-up form works properly. -->
           <input data-id="ca:input" type="hidden" name="ca" value="3921fc69-899e-4066-995d-7a14bd9cf887">
           <input data-id="list:input" type="hidden" name="list" value="1508315983">
           <input data-id="source:input" type="hidden" name="source" value="EFD">
           <input data-id="required:input" type="hidden" name="required" value="list,email">
           <input data-id="url:input" type="hidden" name="url" value="">
           <input data-id="Email Address:input" type="text" name="email" value="" placeholder="EMAIL" maxlength="80"></p>
           <button type="submit" class="Button ctct-button Button--block Button-secondary" data-enabled="enabled">Become a MD Friend</button>
        
       </form>
   </div>
</div>
<script type='text/javascript'>
   var localizedErrMap = {};
   localizedErrMap['required'] =    'This field is required.';
   localizedErrMap['ca'] =      'An unexpected error occurred while attempting to send email.';
   localizedErrMap['email'] =       'Please enter your email address in name@email.com format.';
   localizedErrMap['birthday'] =    'Please enter birthday in MM/DD format.';
   localizedErrMap['anniversary'] =   'Please enter anniversary in MM/DD/YYYY format.';
   localizedErrMap['custom_date'] =   'Please enter this date in MM/DD/YYYY format.';
   localizedErrMap['list'] =      'Please select at least one email list.';
   localizedErrMap['generic'] =     'This field is invalid.';
   localizedErrMap['shared'] =    'Sorry, we could not complete your sign-up. Please contact us to resolve this.';
   localizedErrMap['state_mismatch'] = 'Mismatched State/Province and Country.';
  localizedErrMap['state_province'] = 'Select a state/province';
   localizedErrMap['selectcountry'] =   'Select a country';
   var postURL = 'https://visitor2.constantcontact.com/api/signup';
</script>
<script type='text/javascript' src='https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/js/signup-form.js'></script>
<!--End CTCT Sign-Up Form-->
            
            <span>
                We protect your personal information. We use secure transaction.
            </span>
        </div>
        <div class="right wow fadeInDown animated" data-wow-delay="0.5s">
        </div>
    </div>
</div>


<div id="about">
    <div class="custom-container">  
        <div class="title">
            <img src="<?php echo $this->getSkinUrl('images/guruu/aboutSusanLin/drLin.jpg') ?>">
            <p>
                <span>
                    About DR Susan Lin            
                </span>
            </p>
        </div>

        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('guruu_lp_susan_bio')->toHtml(); ?>
    </div>
</div>

<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="<?php echo Mage::getBaseUrl(); ?>/terms-and-conditions/">User Agreement</a> and <a href="<?php echo Mage::getBaseUrl(); ?>privacy-policy">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/guruu/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/guruu/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/guruu/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/guruu-custom.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/guruu-custom.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>


<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>


<script>

$(document).ready(function() {

    $("#AsSeenInSlider").owlCarousel({
        items : 5,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : false,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 200,
        paginationSpeed : 800,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : true,
        stopOnHover : true,
     
        // Navigation
        navigation : false,
        navigationText : ["prev","next"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
    });

    $(".BeforeAndAfterSlider").owlCarousel({
        items : 1,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : true,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 5000,
        paginationSpeed : 3000,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : false,
        stopOnHover : true,
     
        // Navigation
        navigation : true,
        navigationText : ["<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-left-arrow.png') ?>'>","<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-right-arrow.png') ?>'>"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
      });

});


    </script>

<script type="text/javascript">

$(function() {
    menu = $('nav ul');

    $('#openup').on('click', function(e) {
        e.preventDefault(); menu.slideToggle();
    });
  
    $(window).resize(function(){
        var w = $(this).width(); if(w > 760 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
  
    $('nav li').on('click', function(e) {                
        var w = $(window).width(); if(w < 760 ) {
            menu.slideToggle(); 
        }
    });
    
    $('.open-menu').height($(window).height());
});

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>

<script type='text/javascript'>
window.__lo_site_id = 59158;

(function() {
var wa = document.createElement('script'); wa.type = 'text/javascript'; wa.async = true;
wa.src = 'https://d10lpsik1i8c69.cloudfront.net/w.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wa, s);
})();
</script>

</body>
</html>