<!DOCTYPE html>
<html>
<head>
	<title>MD FAQ</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">


</head>

<body class="faq">

<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/custom-top-menu.phtml')->toHtml(); ?>

<div class="contentWrapper">
	<div class="custom-container">
		<div class="panel-group" id="accordion">
			<!-- Faq-1-->
			<div class="panel panel-default">
				<div class="panel-heading active">
					<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="normalcollapse">MD Follicle Energizer <span></span></a>
					</h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse in">
					<div class="panel-body">
						<!-- Content -->
						<div class="content-inner">
							<strong>What causes female hair loss?</strong>
							<p>
								<b>-</b> Most common cause for female hair loss are from childbirth, menopause or over processed hair
							</p>
							<br/>
							<strong>What is the difference between male and female hair loss?</strong>
							<p>
								<b>-</b> In women, hair loss tends to be more diffuse&#8212;meaning you'll see an all-over decrease in volume, thickness and fullness, as opposed to the receding hairline and/or thinning of the crown you'll observe with men.
							</p>
							<br/>
							<p>
								<img src="<?php echo $this->getSkinUrl('images/hair-faq.jpg') ?>">
							</p>
							<br/>
							<strong>How does MD Hair Restoration Follicle Energizer work?</strong>
							<p>
								<b>-</b> MD Hair Restoration Follicle Energizer is designed specifically for female accelerated hair loss by revitalizing the female scalp. This is important because healthy hair starts with healthy scalp.
							</p>
							<br/>
							<strong>What are the active ingredients in MD Hair Restoration Follicle Energizer?</strong>
							<p>
								<b>-</b> The active ingredient, cytokines, activates dormant hair follicles by increasing follicular cell metabolism to improve microcirculation and encourage hair growth.
							</p>
							<br/>
							<strong>Is MD Hair Restoration Follicle Energizer safe?</strong>
							<p>
								<b>-</b> Yes. MD Hair Restoration Follicle Energizer does not contain any drugs so it can be used by women over 18. Not recommended for women who are pregnant or breast feeding.
							</p>
							<br/>
							<strong>How do I use MD Hair Restoration Follicle Energizer?</strong>
							<p>
								<b>-</b> Simple. Apply nightly on a dry, clean scalp. Dispense MD Hair Restoration Follicle Energizer by clicking the base of the tube. Apply the product with precision brush where the hair is thinning. One dab per area should be sufficient for both the front and back portions of your scalp. Using the applicator brush, distribute the product along the problem areas. Do not rinse. Style as desired.
							</p>
							<br/>
						</div>
					</div>
				</div>
			</div>
			<!-- /Faq-1 -->
			<!-- Faq-2 -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="normalcollapse">MD Lash Factor <span></span></a>
					</h4>
				</div>
				<div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="content-inner">
							<strong>What is MD Lash Factor?</strong>
							<p>
								<b>-</b> MD Lash Factor is a physician formulated eyelash conditioner that helps to promote the appearance of longer, thicker, and fuller looking eyelashes in 4 to 5 weeks.
							</p>
							<br/>
							<strong>How do I use MD Lash Factor?</strong>
							<p>
								<b>-</b> At night after cleansing, apply a thin line of MD Lash Factor to your upper lash line once a day, as though you were applying liquid eyeliner. Do not apply MD Lash Factor to your actual eyelashes and only use a small amount when applying the product.
							</p>
							<br/>
							<strong>Can I apply MD Lash Factor more than once a day?</strong>
							<p>
								<b>-</b> For optimal results you need only apply a very small amount to your upper lash line once a day.
							</p>
							<br/>
							<strong>Am I still able to use my regular skincare line while using your products?</strong>
							<p>
								<b>-</b> Yes! MD Lash Factor makes a wonderful addition to your skincare routine.
							</p>
							<br/>
							<strong>Can I use MD Lash Factor on my eyebrows?</strong>
							<p>
								<b>-</b> Yes! MD Lash Factor is safe to use on your eyebrows to help your over-plucked eyebrows look denser, thicker, and darker.
							</p>
							<br/>
							<strong>Can I use MD Lash Factor if I have had permanent make up done?</strong>
							<p>
								<b>-</b> Yes! MD Lash Factor is safe to use on permanent make up and will not cause any discoloration or fading.
							</p>
							<br/>
							<strong>Has any safety studies been done on MD Lash Factor?</strong>
							<p>
								<b>-</b> Yes! In an independent clinical study by a board certified ophthalmologist, MD Lash Factor showed no affect on visual acuity, cornea, eyelid, and conjunctiva. There were no changes in color or deposits on the contact lenses
							</p>
							<br/>
							<strong>Have any allergic reactions or allergies been reported from the use of MD Lash Factor?</strong>
							<p>
								<b>-</b> As with any cosmetic preparation, there are some individuals that may be allergic to one or more components of the product. If you know or suspect that you might be allergic to any of the ingredients used in MD Lash Factor, we recommend that you do not use the product. Some users have reported a mild irritation at the base of their upper lashes while using the product. If this occurs, you can either temporarily withhold using the product for a few days and then continue use, or stop using the product if severe irritation occurs. Most of our users report no irritation or minimal irritation after a few weeks of use.
							</p>
							<br/>
							<strong>Once I have the results I am looking for, do I have to keep using MD Lash Factor every night?</strong>
							<p>
								<b>-</b> No. Once you have your desired look you can go ahead and use MD Lash Factor 2 to 3 times a week to maintain your current look. If you do decide to stop using MD Lash Factor, your lashes will go back to their original length.
							</p>
							<br/>
							<strong>Who should not use MD Lash Factor?</strong>
							<p>
								<b>-</b> We do not recommend using MD Lash Factor if you are currently using eye medication, have had eye surgery in the last 6 months or have an eye infection
							</p>
							<br/>
						</div>
					</div>
				</div>
			</div>
			<!-- /Faq-2 -->
			<!-- Faq-3 -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" class="normalcollapse">MD Nutri Hair <span></span></a>
					</h4>
				</div>
				<div id="collapseThree" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="content-inner">
							<strong>Is MD Nutri Hair created specifically for female hair loss?</strong>
							<p>
								<b>-</b> Yes. MD Nutri Hair was formulated for woman facing hair loss and thinning hair
							</p>
							<br/>
							<strong>Does MD Nutri Hair contain drugs?</strong>
							<p>
								<b>-</b> No, MD Nutri Hair uses natural plant stem cell derived ingredient and does not contain drugs such as Minoxidil or Finasteride
							</p>
							<br/>
							<strong>What types of female hair loss can MD Nutri Hair help?</strong>
							<p>
								<b>-</b> MD Nutri Hair is designed for accelerated female hair loss from stress, menopause, childbirth, diet and overworked hair
							</p>
							<br/>
							<strong>Can I use MD Nutri Hair with my current shampoo or hair regeneration products?</strong>
							<p>
								<b>-</b> Yes, MD Nutri Hair uses unique anti-aging ingredient to work synergistically with your topical or nutrient supplements for your thinning hair
							</p>
							<br/>
							<strong>What is the science behind MD Nutri Hair?</strong>
							<p>
								<b>-</b> Female scalp and hair have unique needs. By using the latest plant stem cell technology to anti-age female scalp, MD Nutri Hair provides a solution for female hair loss
							</p>
							<br/>
							<strong>Who should not take MD Nutri Hair?</strong>
							<p>
								<b>-</b> MD Nutri Hair is not recommended for pregnant or breastfeeding woman or anyone who is allergic to seafood
							</p>
							<br/>
						</div>
					</div>
				</div>
			</div>
			<!-- /Faq-3 -->
			<!-- Faq-4 -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour" class="normalcollapse">MD Scalp Essentials <span></span></a>
					</h4>
				</div>
				<div id="collapseFour" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="content-inner">
							<strong>How does MD Scalp Essentials work?</strong>
							<p>
								<b>-</b> MD Scalp Essentials immediately relieves and calms itching scalp. It refreshes greasy and oily scalp to unclog clogged hair follicles to promote a more youthful looking scalp for fuller and thicker looking hair.
							</p>
							<br/>
							<strong>Should I continue to use MD Scalp Essentials once my symptoms are resolved?</strong>
							<p>
								<b>-</b>Yes. Apply once per week to keep your scalp feeling healthy and fresh.
							</p>
							<br/>
							<strong>What are the active ingredients in MD Scalp Essentials?</strong>
							<p>
								<b>-</b> Lilac extract derived from plant stem cell technology to anti-age your scalp. Mandelic acid decongests hair follicles for healthy scalp and healthy hair
							</p>
							<br/>
							<strong>How do I use MD Scalp Essentials?</strong>
							<p>
								<b>-</b> Massage 1 dropper full daily onto clean scalp. Repeat until symptoms improve. Apply weekly to maintain results.
							</p>
							<br/>
							<strong>What can I use MD Scalp Essentials for?</strong>
							<p>
								<b>-</b> May be used for scalp irritation, dandruff, excess oil production and thinning hair
							</p>
							<br/>
							<strong>Can I use MD Scalp Essentials with my other hair regeneration products?</strong>
							<p>
								<b>-</b> Yes. MD Scalp Essentials may be used in conjunction with other regeneration products
							</p>
							<br/>
							<strong>Who should not use MD Scalp Essentials?</strong>
							<p>
								<b>-</b> MD Scalp Essentials is not recommended for pregnant or breastfeeding
							</p>
							<br/>
						</div>
					</div>
				</div>
			</div>
			<!-- /Faq-4 -->
		</div>
	</div>
</div>


<?php echo $this->getChildHtml('footer') ?>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
	jQuery('.panel-heading').click(function(e) {
	    e.preventDefault(); //prevent the link from being followed
	    jQuery('.panel-heading').removeClass('active');
	    jQuery(this).addClass('active');
	});
});
	                                  
</script>
</body>
</html>