<!DOCTYPE html>
<html>
<head>
	<title>MD Lash</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="CustomCategoryPage CustomLashCategory">

<div class="VideoWrapper">
	<div id="video-container">
        <video preload="auto" autoplay loop muted controls="true" width="1440" height="810">
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/lash-category.mp4" type="video/mp4">  
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/lash-category.webm" type="video/webm"> 
            <source src="https://boozaid.com/skin/frontend/default/boozaid/images/mdvid/lash-category.ogg" type="video/ogg">  
        </video>
    </div>

    <div class="overlay">
        <div class="overlay__inner">
        	<div class="transparentNav">
	           <nav class='main-nav' id="main-navWrapper">
	            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/topBar.phtml')->toHtml(); ?>
	                <div class="custom-container navi">
	                    <a class="logo" href='<?php echo mage::getbaseurl(); ?>'> 
	                        <img class="whitelogo" src="<?php echo $this->getSkinUrl('images/logo-blue.png') ?>"> 
	                        <img class="darklogo" src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>" style="display: none;"> 
	                    </a>
	                    <div class="MDnav">
	                        <ul>
	                             <?php
	                            $obj = new Mage_Catalog_Block_Navigation();
	                            $storeCategories = $obj->getStoreCategories();
	                            Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
	                            $limit_category = 4;
	                            $ctr = 1;

	                            foreach ($storeCategories as $_category):
	                            if($ctr <= $limit_category) :
	                        ?>
	                    <li> 

	                        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$_category->getUrlKey(); ?>">
	                        
	                        <?php
	                            $_category = Mage::getModel('catalog/category')->load($_category->getId());
	                        ?>
	                        <?php echo $_category->getName(); ?></a>
	                        <ul>
	                        <?php 
	                            
	                            
	                                $_subcategories = $_category->getChildrenCategories();
	                                if (count($_subcategories) > 0){    

	                                    foreach($_subcategories as $_subcategory){
	                                        //load products now
	                                    $products = Mage::getModel('catalog/category')->load($_subcategory->getId())
	                                     ->getProductCollection()
	                                     ->addAttributeToSelect('*')
	                                     ->addAttributeToFilter('status', 1)
	                                     ->addAttributeToFilter('visibility', 4)
	                                     ->setOrder('price', 'ASC');
	                                         echo '
	                                         <li><a href="'.$_subcategory->getUrl().'">'.$_subcategory->getName().'</a>';
	                                         if (count($products) > 0){    

	                                            echo '<ul>';
	                                            foreach($products as $_product){
	                                               echo '<li>
	                                                    <a class="thirdlevel" href="'.$_product->getProductUrl().'">
	                                                    <div class="image">
	                                                        <img src="'.$_product->getImageUrl().'">                                                    
	                                                    </div>
	                                                    <div class="desc">'.$_product->getName().'</div>
	                                                    </a>
	                                                </li>';
	                                            }
	                                                
	                                            echo '</ul>';
	                                        }
	                                         echo '</li>';
	                                    }// end foreach subcat
	                                }// end if count sub
	                            
	                        ?>      
	                         </ul>
	                        </li>
	                        <?php  $ctr++; endif;   endforeach; ?>   

	                            <li><a href="<?php echo Mage::getBaseUrl(); ?>sales">Sale</a></li>
	                            <li>
                                    <a href="http://md-factor.com/about/">Brand</a>
                                    <ul>
                                        <li>
                                            <a href="https://md-factor.com/pressmedia/">Media</a> 
                                            <ul>
                                                <li>
                                                    <a href="https://md-factor.com/blog/">Blog</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
	                        </ul>
	                    </div>

	                    <div class="searchWrapper desktopSearcWrapper">
	                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('currency/currency.phtml')->toHtml(); ?>
	                                    
	                        <div id="searchInner" > 
	                            <form onsubmit="return check_small_search_form()" method="get" action="<?php echo Mage::getUrl('catalogsearch/result')?>">
	                                
	                                <button value="" type="submit">
	                                    <i class="fa fa-search" aria-hidden="true"></i>
	                                </button>
	                                
	                                <input placeholder="SEARCH PRODUCTS" class="query" "search_query"="" name="q" type="text">
	                            </form>
	                        </div> 
	                    </div>
	                </div>
	            </nav>
	        </div>
            <div class="content" style="display: none;">
                <div class="custom-container">
                    <h1>
                       	Get Real
                    </h1>
                    <span>
                        Longer Lashes
                    </span>

                    <div class="ctaWrapper">
                        <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            Watch Video
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="customCategory">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lash_category_list')->toHtml(); ?>
</div>


<div class="footerMenuWrapper footerMenuDesktop">
    <div class="custom-container">
        <div>
            <ul>
                <li>
                    CUSTOMER SERVICE
                </li>
                <li>
                    <a href="http://md-factor.com/shipping-policy/">
                        Shipping Policies
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/shipping-policy/">
                        Return Policy
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/authenticity/">
                        Authenticity
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/contact-us/">
                        Contact Us
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/privacy-policy/">
                        Privacy Policy
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/terms-and-conditions/">
                        Terms and Conditions
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/wholesale/">
                        Wholesale
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <ul>
                <li>
                    ABOUT MD
                </li>
                <li>
                    <a href="http://md-factor.com/md-factor-careers/">
                        Careers 
                    </a>
                </li>
                <!-- <li>
                    <a href="">
                        International
                    </a>
                </li> -->
                <li> 
                    <a href="http://md-factor.com/about/">
                        About MD® / 于MD®
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/press/">
                        In The Press
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/faq/">
                        FAQs
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <ul>
                <li>
                    ACCOUNT
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>customer/account">
                        My Account
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>wishlist">
                        Wishlist
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>sales/order/history">
                        Order Status
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>checkout/cart">
                        View Cart
                    </a>
                </li>
            </ul>
        </div>

        <div>
            <ul>
                <li>
                    INTERNATIONAL
                </li>
                <li>
                    <a href="javascript:void(0);">
                        繁體中文
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);">
                        体中文
                    </a>
                </li>
                <li class="jabber">
                    <a href="http://www.sitejabber.com/reviews/www.md-factor.com?sort=rating&direction=desc#reviews">
                        <img src="<?php echo $this->getSkinUrl('images/landingpage-revamp/jabber-logo.png') ?>">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>


<div class="footerMenuWrapper footerMenuMobile" style="display: none;">
    <div class="tab_container">
        <input id="tab1" type="radio" name="tabs" checked>
        <label for="tab1">CUSTOMER SERVICE</label>

        <input id="tab2" type="radio" name="tabs">
        <label for="tab2">ABOUT MD</label>

        <input id="tab3" type="radio" name="tabs">
        <label for="tab3">ACCOUNT</label>

        <input id="tab4" type="radio" name="tabs">
        <label for="tab4">INTERNATIONAL</label>
        

        <section id="content1" class="tab-content">
            <ul>
                <li>
                    <a href="http://md-factor.com/shipping-policy/">
                        Shipping Policies
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/shipping-policy/">
                        Return Policy
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/authenticity/">
                        Authenticity
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/contact-us/">
                        Contact Us
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/privacy-policy/">
                        Privacy Policy
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/terms-and-conditions/">
                        Terms and Conditions
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/wholesale/">
                        Wholesale
                    </a>
                </li>
            </ul>
        </section>
       
        <section id="content2" class="tab-content">
            <ul>
                <li>
                    <a href="http://md-factor.com/md-factor-careers/">
                        Careers 
                    </a>
                </li>
                <!-- <li>
                    <a href="">
                        International
                    </a>
                </li> -->
                <li> 
                    <a href="http://md-factor.com/about/">
                        About MD® / 于MD®
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/press/">
                        In The Press
                    </a>
                </li>
                <li>
                    <a href="http://md-factor.com/faq/">
                        FAQs
                    </a>
                </li>
            </ul>
        </section>
       
        <section id="content3" class="tab-content">
            <ul>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>customer/account">
                        My Account
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>wishlist">
                        Wishlist
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>sales/order/history">
                        Order Status
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getBaseUrl(); ?>checkout/cart">
                        View Cart
                    </a>
                </li>
            </ul>
        </section>

        <section id="content4" class="tab-content">
            <ul>
                <li>
                    <a href="javascript:void(0);">
                        繁體中文
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);">
                        体中文
                    </a>
                </li>
                <li class="jabber">
                    <a href="http://www.sitejabber.com/reviews/www.md-factor.com?sort=rating&direction=desc#reviews">
                        <img src="<?php echo $this->getSkinUrl('images/landingpage-revamp/jabber-logo.png') ?>">
                    </a>
                </li>
            </ul>
        </section>
    </div>
</div>


<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="http://md-factor.com/terms-and-conditions/">User Agreement</a> and <a href="http://md-factor.com/privacy-policy/">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/landingpage-revamp/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/landingpage-revamp/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/landingpage-revamp/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>


<style type="text/css">
    ::-webkit-media-controls {
  display:none !important;
}
</style>

<!--  Custom Scripts  -->

<script type="text/javascript" src="http://us.md-factor.com/js/lib/jquery/jquery-1.10.2.js"></script>

<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-js/jquery.event.move.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-js/jquery.twentytwenty.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-js/nav.min.js') ?>"></script>

<script type="text/javascript">
        jQuery(document).ready(function($) {
            jQuery('.MDnav').MDNav({
                theme: 'light'
            });
        });
    </script>

<script>

$(window).load(function(){
      $(".twentytwenty-container[data-orientation!='vertical']").twentytwenty({default_offset_pct: 0.8});
      $(".twentytwenty-container[data-orientation='vertical']").twentytwenty({default_offset_pct: 0.3, orientation: 'vertical'});
});

</script>

<script>



$(document).ready(function() {

     $(document).on('click', '.submitBtnCust', function(){
        var ca = $('form[data-id="embedded_signup:form"] input[data-id="ca:input"]').val();
        var email = $('form[data-id="embedded_signup:form"] input[data-id="Email Address:input"]').val();
        var name = $('form[data-id="embedded_signup:form"] input[data-id="First Name:input"]').val();

        postURL = 'https://visitor2.constantcontact.com/api/signup?'+ 'ca='+ ca + '&email='+ email +'&first_name='+ name +'&list';
          $.ajax({
              type: 'POST',
              crossDomain: true,
              url: postURL,
              error: function(xhr, status, err) {
                
                alert('error');
          },
          success: function(data, status, xhr) {
              $('.ctct-embed-signup.subscription p').hide();
              $('.ctct-embed-signup.subscription h2').hide();
              $('.ctct-embed-signup.subscription button').hide();
              $('.ctct-embed-signup.subscription form').hide();
              $('#success_message_subscription').removeClass('u-hide');
              $('#success_message_subscription').show();
    
          }
      });
    });

   
});


</script>
<script type="text/javascript">

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>

<script type="text/javascript">

'use strict';

function debounce(func, wait, immediate) {

  // Debounce
  // http://davidwalsh.name/javascript-debounce-function

    var timeout;
    return function() {
        var context = this,
          args = arguments;
        var later = function() {
          timeout = null;
          if (!immediate) {
            func.apply(context, args);
          }
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) {
          func.apply(context, args);
        }
      };
}

    var htmlTag = document.getElementsByTagName('html')[0];
    var videoContainer = document.querySelector('#video-container');
    var videoElem = document.querySelector('#video-container video');

    var minW = 320; // Minimum video width allowed
    var vidWOrig; // Original video dimensions
    var vidHOrig;

    vidWOrig = videoElem.getAttribute('width');
    vidHOrig = videoElem.getAttribute('height');

    var videoCover = function() {

      var winWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
      var winHeight = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;

      // Set the video viewport to the window size

      videoContainer.style.width = winWidth + 'px';
      videoContainer.style.height = winHeight + 'px';

      // Use largest scale factor of horizontal/vertical
      var scaleH = winWidth / vidWOrig;
      var scaleV = winHeight / vidHOrig;
      var scale = scaleH > scaleV ? scaleH : scaleV;

      // Don't allow scaled width < minimum video width
      if (scale * vidWOrig < minW) {
        scale = minW / vidWOrig;
      }

      // Scale the video
      var videoNewWidth = scale * vidWOrig;
      var videoNewHeight = scale * vidHOrig;

      videoElem.style.width = videoNewWidth + 'px';
      videoElem.style.height = videoNewHeight + 'px';

      // Center it by scrolling the video viewport
      videoContainer.scrollLeft = (videoNewWidth - winWidth) / 2;
      videoContainer.scrollTop = (videoNewHeight - winHeight) / 2;

    };

    if (htmlTag.classList.contains('no-touch')) {
      videoCover();

      // Adjust on resize
      var updateVideo = debounce(function() {
        videoCover();
      }, 100);

      window.addEventListener('resize', updateVideo);
    }
        
</script>


</body>
</html>