
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
<meta name="googlebot" content="noindex, nofollow">
<script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
<title></title>
<script type='text/javascript'>//<![CDATA[
$(document).ready(function(){
$.get("//ipinfo.io", function (response) {
    $("#ip").html("IP: " + response.country);
    if(response.country == "AU"){
    	window.location.href = '//staging.md-factor.com/au';
    }else if(response.country == "BR"){
    	window.location.href = '//staging.md-factor.com/br';
    }
    else if(response.country == "CA"){
    	window.location.href = '//staging.md-factor.com/ca';
    }
    else if(response.country == "CH"){
    	window.location.href = '//staging.md-factor.com/ch';
    }
    else if(response.country == "MX"){
    	window.location.href = '//staging.md-factor.com/mx';
    }
    else if(response.country == "US"){
    	window.location.href = '//staging.md-factor.com/us';
    }else{
    	window.location.href = '//staging.md-factor.com/us';
    }
    
}, "jsonp");
});//]]> 
</script>
</head>

<body>
</body>
</html>