<!DOCTYPE html>
<html>
<head>
	<title>MD Hair Kit Offer</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="http://127.0.0.1/webfiles/MDMagento/skin/frontend/default/md-theme/css/lity.min.css" media="all" />

    <!-- Owl Carousel Assets -->
    <link href="owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="owl-carousel/owl.theme.css" rel="stylesheet"> 

	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/hair-landing.css" type="text/css" />
</head>

<body class="hairkitoffer">

<!-- Edited by rej -->

<div class="navWrapper">
	<nav id="header" class="navbar navbar-fixed-top">
        <div id="header-container" class="MDcontainer navbar-container">
            <div class="navbar-header">
                <a id="brand" class="navbar-brand" href="<?php echo Mage::getUrl('home'); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/logo.png') ?>" alt=""/>
                </a>
            </div>
            
            <div class="right">
            	<a href="javascript:void(0);">
            		<i class="fa fa-phone" aria-hidden="true"></i>
            		Contact Us | 1-650-340-8688
            	</a>
            </div>
       </div>
    </nav>
</div>

<div class="contentWrapper">
	<div class="freeshippingWrapper">
        <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/truck.png') ?>" alt=""/> 
		Free US shipping | Use Code: freeshipping
	</div>
    
    <!-- Header -->
    <section id="header-section" data-speed="4" data-type="background">
        <div class="MDcontainer">
            <div class="col-md-6">
            </div>

            <div class="col-md-6">
                <span class="share wow fadeInDown animated" data-wow-delay="0.5s">
                    <a href="#" >
                        <i class="fa fa-reply" aria-hidden="true"></i> Share
                    </a>
                </span>

                <h1 class="wow fadeIn animated" data-wow-delay="0.3s">
                    MD Nutri hair
                    <p>Ultimate Program</p>
                    <span>
                        For only $39.95
                    </span>
                </h1>

                <div class="top wow fadeIn animated" data-wow-delay="0.4s">
                    <button class="pinkBG">
                        Buy Now
                    </button>

                    <button class="pinkBorder">
                        Free Consult
                    </button>
                </div>

                <div class="bottom wow fadeIn animated" data-wow-delay="0.5s">
                    <div class="inner">
                         <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/playbutton.png') ?>" alt=""/>
                            <span>
                                click to learn more
                            </span>
                         </a>
                    </div>
                </div>

                <div class="hangingProduct wow zoomIn animated" data-wow-delay="1s">
                     <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/scalp-essentials-prod.png') ?>" alt=""/>
                </div>
               
            </div>
        </div>
             
    </section>

    <section id="AsSeenIn">
        <h2>
            As Seen In
        </h2>

        <div class="container wow fadeIn animated" data-wow-delay="0.3s">
            <div id="AsSeenInSlider" class="owl-carousel">
                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/cosmopolitan.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/marie-claire.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/the-new-york-times.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/allure.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/womens-health.png') ?>" alt="Lazy Owl Image">
                </div>
            </div>
        </div>
    </section>

    <section id="JoinMD">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3s">
            <h2>
                Join MD Now!

                <span>
                    Over 1 million customers worldwide
                </span>

                <p>
                    Your information will be secured. We do not share or spam.
                </p>
            </h2>

            <form class="wow fadeIn animated" data-wow-delay="0.3s">
                <input type="text" name="Fullname" placeholder="Email">
                <button class="pinkBG">
                    Subscribe
                </button>
            </form>
        </div>
    </section>

    <section id="CustomDescription">
        <div class="MDcontainer">
            <div class="leftSide">
                <div class="title">
                    <h1>
                        Thick, Healthier

                        <span>
                            hair
                        </span>
                    </h1>
                </div> 

                <div class="contentInner">
                    <div class="left wow zoomIn animated" data-wow-delay="0.8">
                        <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/brush.png') ?>" alt=""/> 
                    </div>

                    <div class="right">
                        <div class="top">
                            <p>
                                This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth*. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair.
                            </p>
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/description-logos.png') ?>" alt=""/>
                        </div>

                        <div class="bottom">
                            <button class="pinkBG">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/shopping-bag-ico.png') ?>" alt=""/>
                                Add to bag
                            </button>

                            <button class="pinkBorder">
                                Learn more
                            </button>
                        </div>

                    </div>
                </div>  

                <div class="contentInnerMobile" style="display: none;">
                    <div class="right">
                        <div class="top">
                            <p>
                                This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair.
                            </p>

                            <div class="brush wow zoomIn animated" data-wow-delay="0.8">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/brush.png') ?>" alt=""/> 
                            </div>
                            
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/description-logos.png') ?>" alt=""/>
                        </div>

                        <div class="bottom">
                            <button class="pinkBG">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/shopping-bag-ico.png') ?>" alt=""/>
                                Add to bag
                            </button>

                            <button class="pinkBorder">
                                Learn more
                            </button>
                        </div>

                    </div>
                </div>      
            </div>

            <div class="rightSide">
            </div>
        </div>
    </section>

    <section id="Promo">
        <div class="MDcontainer">
            <div class="leftSide">
                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/kitoffer-prod-left.png') ?>" alt=""/ class="wow fadeInUp animated" data-wow-delay="0.5s"> 
            </div>
            <div class="middle">
                <h1>
                    Up to 30% OFF

                    <span>
                        Get your discount code now!
                    </span>
                </h1>

                <form>
                    <input type="email" name="email" placeholder="email">
                    <button class="pinkBG">
                        Reveal Code
                    </button>
                </form>
            </div>
            <div class="rightSide">
                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/kitoffer-prod-right.png') ?>" alt=""/ class="wow fadeInDown animated" data-wow-delay="0.5s"> 
            </div>
        </div>
    </section>


    <section id="Ingredients">
        <div class="MDcontainer">
            <div class="leftSide">
                <h1>
                    Nutri hair

                    <span>
                        ingredients
                    </span>     
                </h1>
            </div>

            <div class="rightSide">
                <div class="firstIngredient wow fadeIn animated" data-wow-delay="0.8">
                    <span></span>
                    <p>
                        Collagen
                    </p>
                </div>

                <div class="secondIngredient wow fadeIn animated" data-wow-delay="1s">
                    <span></span>
                    <p>
                        Lilac Extract
                    </p>
                </div>

                <div class="thirdIngredient wow fadeIn animated" data-wow-delay="1.8s">
                    <span></span>
                    <p>
                        Flaxseed powder
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section id="CustomerReview">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3">
            <div class="leftSide">
                <div class="rating">
                    <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/stars.png') ?>" alt=""/> 
                </div>

                <div class="testimonial">
                    <p>
                        This product qualifies almost as a miracle, as far as I'm concerned. I've been using hair supplements and creams for ages, and I had just gotten a hair extension when I found your product. My thinning hair is filling in, so I no longer need it. PLUS - I've had my husband take it, and HIS thinning hair is filling in! Hallelujah! Thank you, thank you, thank you! 
                    </p>
                </div>

                <div class="author">
                    <span></span>
                    <p>
                        Cyndi W
                    </p>
                </div>
            </div>

            <div class="rightSide">
                <div class="vid">
                    <div class="inner">
                        <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/playbutton-medium.png') ?>" alt=""/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="customFooter">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3">
            <h1>
                Connect 

                <span>
                    with us
                </span>
            </h1>

            <div class="social">
                <a href="javascript:void(0);" class="icon-button facebook">
                    <i class="fa fa-facebook" aria-hidden="true"></i><span></span>
                </a>

                <a href="javascript:void(0);" class="icon-button twitter">
                    <i class="fa fa-twitter" aria-hidden="true"></i><span></span>
                </a>

                <a href="javascript:void(0);" class="icon-button instagram">
                    <i class="fa fa-instagram" aria-hidden="true"></i><span></span>
                </a>
            </div>
        </div>
    </section>

    <section id="Copyright">
        <div class="MDcontainer">
            <p>
                Copyright &copy; 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/><a href="javascript:void(0);">User Agreement</a> and <a href="javascript:void(0);"> Privacy Policy </a>.
            </p>
        </div>
    </section>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script type="text/javascript" src="http://127.0.0.1/webfiles/MDMagento/skin/frontend/default/md-theme/js/md-js/lity.min.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-hair-landing/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-hair-landing/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-hair-landing/animate-custom.min.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-js/owl.carousel.js') ?>"></script>

<script>

    // Fixed Nav

    $(document).ready(function(){


    var myNavBar = {

        flagAdd: true,

        elements: [],

        init: function (elements) {
            this.elements = elements;
        },

        add : function() {
            if(this.flagAdd) {
                for(var i=0; i < this.elements.length; i++) {
                    document.getElementById(this.elements[i]).className += " md-hair-theme";
                }
                this.flagAdd = false;
            }
        },

        remove: function() {
            for(var i=0; i < this.elements.length; i++) {
                document.getElementById(this.elements[i]).className =
                        document.getElementById(this.elements[i]).className.replace( /(?:^|\s)md-hair-theme(?!\S)/g , '' );
            }
            this.flagAdd = true;
        }

    };

    /**
     * Init the object. Pass the object the array of elements
     * that we want to change when the scroll goes down
     */
    myNavBar.init(  [
        "header",
        "header-container",
        "brand"
    ]);

    /**
     * Function that manage the direction
     * of the scroll
     */
    function offSetManager(){

        var yOffset = 0;
        var currYOffSet = window.pageYOffset;

        if(yOffset < currYOffSet) {
            myNavBar.add();
        }
        else if(currYOffSet == yOffset){
            myNavBar.remove();
        }

    }

    /**
     * bind to the document scroll detection
     */
    window.onscroll = function(e) {
        offSetManager();
    }

    /**
     * We have to do a first detectation of offset because the page
     * could be load with scroll down set.
     */
    offSetManager();
    });


    // AsSeenIn Slider

     $(document).ready(function() {

      $("#AsSeenInSlider").owlCarousel({
        items : 5,
        itemsDesktopSmall : [991,3],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        lazyLoad : true,

        //Autoplay
        autoPlay : true,
        stopOnHover : true,
     
        // Navigation
        navigation : false,
        navigationText : ["prev","next"],
        rewindNav : true,
        scrollPerPage : false,
      });

    });

</script>

</body>
</html>