<!DOCTYPE html>
<html>
<head>
    <meta property="og:image" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/hairkit-bundle/fb-thumb-hairkitbundle.jpg" />
    
    <meta property="og:image:secure_url" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/hairkit-bundle/fb-thumb-hairkitbundle.jpg" />

    <title>MD Hair Kit Bundle</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />


    <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/hairkit-bundle.css" type="text/css" />

    
    <!-- BEGIN GOOGLE ANALYTICS CODE -->
    <script type="text/javascript">
        //<![CDATA[
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-89987290-1']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        //]]>
    </script>
    <!-- END GOOGLE ANALYTICS CODE -->
        
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '1010013549017189');
        fbq('track', "PageView");
    </script>
    
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1010013549017189&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

</head>

<body>

<div class="TopWrapper">
    <div class="custom-container">
        <p>
            <i class="fa fa-phone" aria-hidden="true"></i> Contact Us | 1-888-882-5788
        </p>
        <p>
            <i class="fa fa-truck" aria-hidden="true"></i> FREE US SHIPPING | USE CODE: FREESHIPPING
        </p>
    </div>
</div>


<div id="headerWrapper">
	<nav class='main-nav' id="main-navWrapper">
	    <div class="custom-container">
	        <ul class='main-nav'>
	            <li>
	                <a href='<?php echo Mage::getBaseUrl(); ?>'>
	                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/logo.png') ?>">
	                </a>
	            </li>
	            <li>
	                <a href='#description'>
	                    What is MD Hair
	                </a>
	            </li>
	            <li>
	                <a href='#description'>
	                    How does it work
	                </a>
	            </li>
	            <li>
	                <a href='https://md-factor.com/shipping-policy/'>
	                    satisfaction guarantee
	                </a>
	            </li>
	            <li>
	                <a href="https://us.md-factor.com/md-hair-restoration-starter-kit" class="buynow">
	                    Buy now
	                </a>
	            </li>
	            <li>
	                <a href="https://www.addtoany.com/share" class="share a2a_dd" style="display: none;">
                        Share
                    </a>
	            </li>

	        </ul>
	        <a href='#' id='openup'>
	            <img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>">
	        </a>

	        <span>
	            <a href="https://www.addtoany.com/share" class="share a2a_dd">
	                <i class="fa fa-reply" aria-hidden="true"></i> Share
	            </a>
	        </span>
	    </div>
	</nav>

    <div class="custom-container">
        <div class="inner">
        	<div class="left"></div>

	        <div class="middle">
	        	<h1>
	        		MD HAIR
	        	</h1>
	        	
	        	<p>
	        		YOU WANT FULLER HAIR
	        	</p>
	        	<p>
	        		YOU WANT YOUNGER LOOKING HEALTHY HAIR
	        	</p>
	        	<p>
	        		YOU WANT SEXY SHINNY HAIR
	        	</p>

	        	<span>
                    Physician formulated natural <br/><strong>DRUG FREE</strong> formula
                </span>

                <div>
                    <a href="javascript:void(0);">
                        SIGN UP FOR FREE SHIPPING  &amp; FREE SAMPLES
                    </a> 
                </div>
	        </div>

	        <div class="right">
	        	<div class="wow fadeInDown animated" data-wow-delay="1.5s">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/nutri-hair.png') ?>">      
                </div>
                <div class="wow zoomIn animated" data-wow-delay="0.5s">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/follicle-energizer.png') ?>">
                </div>
                <div class="wow fadeInUp animated" data-wow-delay="2s">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/scalp-essentials.png') ?>">
                </div>
	        </div>
        </div>
    </div>
</div>

<div id="FreeShipping">
    <div class="custom-container">
        <h1>
            FREE SHIPPING 
        </h1>
        <p>
            PLUS FREE SAMPLE WITH FIRST ORDER
        </p>
        <div>
            <a href="javascript:void(0);">
                SUBSCRIBE NOW
            </a>
        </div>
    </div>
</div>

<div id="AsSeenIn">
    <div class="custom-container">
        <h2>
            As Seen In
        </h2>
        <div id="AsSeenInSlider" class="owl-carousel">
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/cosmopolitan-logo.png') ?>">
            </a>
            <a class="item">
                <img class="intimate" src="<?php echo $this->getSkinUrl('images/hairkit-bundle/marie-claire-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/the-new-york-times-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/allure-logo.png') ?>">
            </a>
            <a class="item">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/womens-health-logo.png') ?>">
            </a>
        </div>
    </div>
</div>

<div id="description">
    <div class="custom-container desktop">
        <div class="left">
            <div class="inner">
                <h2>
                    Thicker, healthier hair
                </h2>
                <p>
                    This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair. 
                </p>
            </div>

            <div class="inner">
                <h2>
                    What is hair ultimate program?
                </h2>
                <p>
                    MD® Scalp Essential is a physician formulated scalp serum support for fine and brittle hair. Beautiful hair starts with healthy scalp MD® Scalp Essential gets to the root to help you overcome scalp and hair issues. This lightweight serum helps to provide a refreshed scalp environment. It helps addresses irritated scalp, oiliness, flakes, and hair breakage.
                </p>
            </div>

            <div class="inner">
                <h2>
                    How it works?
                </h2>
                <p>
                    Take one capsule daily. Use alone or in conjunction with your current hair care regimen for fuller, thicker and healthier looking hair. Take one capsule daily. Use alone or in conjunction with your current hair care regimen for fuller, thicker and healthier looking hair. 
                </p>
            </div>
                
            <div>
                <a href="https://us.md-factor.com/md-hair-restoration-starter-kit">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/bag.png') ?>">
                    Add to bag
                </a>

                <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-1.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-1.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-2.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-2.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-3.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-3.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-4.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-4.png') ?>">
                    </a> 
                </div> 
            </div>

            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-container mobile" style="display: none;">

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-1.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-1.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-2.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-2.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-3.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-3.png') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-4.jpg') ?>" data-lity="" data-lity-desc="Photo of a flower">
                        <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/BandA-4.png') ?>">
                    </a> 
                </div> 
            </div>
        </div>
        <div class="left">
            <div class="inner">
                <h2>
                    Thicker, healthier hair
                </h2>
                <p>
                    This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair. 
                </p>
            </div>

            <div class="inner">
                <h2>
                    What is hair ultimate program?
                </h2>
                <p>
                    MD® Scalp Essential is a physician formulated scalp serum support for fine and brittle hair. Beautiful hair starts with healthy scalp MD® Scalp Essential gets to the root to help you overcome scalp and hair issues. This lightweight serum helps to provide a refreshed scalp environment. It helps addresses irritated scalp, oiliness, flakes, and hair breakage.
                </p>
            </div>

            <div class="inner">
                <h2>
                    How it works?
                </h2>
                <p>
                    Take one capsule daily. Use alone or in conjunction with your current hair care regimen for fuller, thicker and healthier looking hair. Take one capsule daily. Use alone or in conjunction with your current hair care regimen for fuller, thicker and healthier looking hair. 
                </p>
            </div>
                
            <div>
                <a href="https://us.md-factor.com/md-hair-restoration-starter-kit">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/bag.png') ?>">
                    Add to bag
                </a>

                <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/_pv-ZZ3geXM" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ingredients">
    <div class="custom-container">
        <div class="left">
            <p>
                Nutri hair

                <span>
                    ingredients
                </span>
            </p>
        </div>

        <div class="right">
            <div class="inner wow zoomIn animated" data-wow-delay="0s">
                <div></div>
                <p>
                    NORWEGIAN FISH COLLAGEN
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="1s">
                <div></div>
                <p>
                    Lilac Extract
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="2s">
                <div></div>
                <p>
                    Flaxseed powder
                </p>
            </div>
        </div>
    </div>
</div>

<div id="testimonial">
    <div class="custom-container">
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
                This product qualifies almost as a miracle, as far as I'm concerned. I've been using hair supplements and creams for ages, and I had just gotten a hair extension when I found your product. My thinning hair is filling in, so I no longer need it. PLUS - I've had my husband take it, and HIS thinning hair is filling in! Hallelujah! Thank you, thank you, thank you! 
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-1.jpg') ?>">
                    <a href="javascript:void(0);">
                        Cyndi W
                    </a>
                </span>
            </div>
        </div>
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
                So far so good..only been using this hair products for a month but my sister has been using it longer and the difference in her hair is remarkable!
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-2.jpg') ?>">
                    <a href="javascript:void(0);">
                        Peggy J.
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>
       

<div id="promo">
    <div class="custom-container">
        <div class="left wow fadeInUp animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/promo-hairkit-bundle-left.png') ?>"> 
        </div>
        <div class="middle">
            <h1>
                SIGN UP FOR FREE SHIPPING <br/>&amp; FREE SAMPLE
            </h1>
            <p>
                OVER 1 MILLION CUSTOMERS WORLDWIDE
            </p>
            <form>
                <input type="text" name="Email" placeholder="EMAIL">
                <a href="javascript:void(0);">
                    Become a MD Friend
                </a>
            </form>
            <span>
                We protect your personal information. We use secure transaction.
            </span>
        </div>
        <div class="right wow fadeInDown animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/promo-hairkit-bundle-right.png') ?>"> 
        </div>
    </div>
</div>


<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="javascript:void(0);">User Agreement</a> and <a href="javascript:void(0);">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>

<script type="text/javascript" src="js/lib/jquery/jquery-1.10.2.js"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>


<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>


<script>

$(document).ready(function() {

    $("#AsSeenInSlider").owlCarousel({
        items : 5,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : false,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 200,
        paginationSpeed : 800,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : true,
        stopOnHover : true,
     
        // Navigation
        navigation : false,
        navigationText : ["prev","next"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
    });

    $(".BeforeAndAfterSlider").owlCarousel({
        items : 1,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : true,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 5000,
        paginationSpeed : 3000,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : false,
        stopOnHover : true,
     
        // Navigation
        navigation : true,
        navigationText : ["<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-left-arrow.png') ?>'>","<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-right-arrow.png') ?>'>"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
      });

});


    </script>

<script type="text/javascript">

$(function() {
    menu = $('nav ul');

    $('#openup').on('click', function(e) {
        e.preventDefault(); menu.slideToggle();
    });
  
    $(window).resize(function(){
        var w = $(this).width(); if(w > 760 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
  
    $('nav li').on('click', function(e) {                
        var w = $(window).width(); if(w < 760 ) {
            menu.slideToggle(); 
        }
    });
    
    $('.open-menu').height($(window).height());
});

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>

<script type='text/javascript'>
window.__lo_site_id = 59158;

(function() {
var wa = document.createElement('script'); wa.type = 'text/javascript'; wa.async = true;
wa.src = 'https://d10lpsik1i8c69.cloudfront.net/w.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wa, s);
})();
</script>
</body>
</html>