<!DOCTYPE html>
<html>
<head>
	<title>MD Hair Loss</title>

    <!-- Google Analytics Content Experiment code -->
    <script>function utmx_section(){}function utmx(){}(function(){var
    k='137572866-2',d=document,l=d.location,c=d.cookie;
    if(l.search.indexOf('utm_expid='+k)>0)return;
    function f(n){if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.
    indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.
    length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;d.write(
    '<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':
    '://www')+'.google-analytics.com/ga_exp.js?'+'utmxkey='+k+
    '&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().
    valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
    '" type="text/javascript" charset="utf-8"><\/sc'+'ript>')})();
    </script><script>utmx('url','A/B');</script>
    <!-- End of Google Analytics Content Experiment code -->


    <meta property="og:image" content="http://us.md-factor.com/skin/frontend/default/md-theme/images/md-hair-landing/nutrihair-fb-thumbnail.jpg" />
    
    <meta property="og:image" content="http://us.md-factor.com/skin/frontend/default/md-theme/images/md-hair-landing/nutrihair-fb-thumbnail.jpg" />

    <meta name="viewport" content="width=device-width,initial-scale=1.0">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

	<!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />

    <!-- Owl Carousel Assets -->
    <link href="owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="owl-carousel/owl.theme.css" rel="stylesheet"> 

	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/hair-landing.css" type="text/css" />

    <!-- BEGIN GOOGLE ANALYTICS CODE -->
    <script type="text/javascript">
        //<![CDATA[
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-89987290-1']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        //]]>
    </script>
    <!-- END GOOGLE ANALYTICS CODE -->
        
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '1010013549017189');
        fbq('track', "PageView");
    </script>
    
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1010013549017189&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

</head>

<body class="hairlossVer-two">

<div class="navWrapper">
	<nav id="header" class="navbar navbar-fixed-top">
        <div id="header-container" class="MDcontainer navbar-container">
            <div class="navbar-header">
                <a id="brand" class="navbar-brand" href="<?php echo Mage::getUrl('home'); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/logo.png') ?>" alt=""/>
                </a>
            </div>
            
            <div class="right">
            	<a href="javascript:void(0);">
            		<i class="fa fa-phone" aria-hidden="true"></i>
            		Contact Us | 1-650-340-8688
            	</a>
            </div>
       </div>
    </nav>
</div>

<div class="contentWrapper">
	<div class="freeshippingWrapper">
        <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/truck.png') ?>" alt=""/> 
		Free US shipping | Use Code: freeshipping
	</div>
    
    <!-- Header -->
    <section id="header-section" data-speed="4" data-type="background">
        <div class="MDcontainer">
            <div class="col-md-6">
            </div>

            <div class="col-md-6">
                <span class="share wow fadeInDown animated" data-wow-delay="0.5s">
                    <a href="https://www.addtoany.com/share" class="a2a_dd" >
                        <i class="fa fa-reply" aria-hidden="true"></i> Share
                    </a>
                </span>

                <h1 class="wow fadeIn animated" data-wow-delay="0.3s">
                    Buy 1 Get 1
                    <span>
                        Save 50%
                    </span>
                </h1>

                <div class="top wow fadeIn animated" data-wow-delay="0.4s">
                    <p>
                        Nourish your hair back to beautiful
                    </p>
                    <button class="pinkBG" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>md-nutri-hair';">
                        Buy Now
                    </button>

                    <button class="pinkBorder">
                        Free Consult
                    </button>
                </div>

                <div class="bottom wow fadeIn animated" data-wow-delay="0.5s">
                    <div class="inner">
                         <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/playbutton.png') ?>" alt=""/>
                            <span>
                                click to learn more
                            </span>
                         </a>
                    </div>
                </div>

               
            </div>
        </div>
             
    </section>

    <section id="AsSeenIn">
        <h2>
            As Seen In
        </h2>

        <div class="container wow fadeIn animated" data-wow-delay="0.3s">
            <div id="AsSeenInSlider" class="owl-carousel">
                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/cosmopolitan.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/marie-claire.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/the-new-york-times.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/allure.png') ?>" alt="Lazy Owl Image">
                </div>

                <div class="item">
                    <img class="lazyOwl" data-src="<?php echo $this->getSkinUrl('images/md-hair-landing/as-seen-in/womens-health.png') ?>" alt="Lazy Owl Image">
                </div>
            </div>
        </div>
    </section>

    <section id="JoinMD">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3s">
            <h2>
                Join MD Now!

                <span>
                    Over 1 million customers worldwide
                </span>
            </h2>
                <div class="fields clearfix">
          <div class="ctct-embed-signup subscription">
            <div class="fields clearfix">
              <span id="success_message_subscription" style="display:none;">
                <div style="text-align:center;font-size:32px;color:#fff">Thanks for signing up!</div>
              </span>
              
              <form data-id="embedded_signup:form" class="ctct-custom-form Form subscribe" name="embedded_signup" method="POST" >
              <input data-id="ca:input" name="ca" value="84bd4af4-34ab-46fe-93f8-cc6f0d942fdf" type="hidden">
              <input data-id="list:input" name="list" value="1275815905" type="hidden">
              <input data-id="source:input" name="source" value="EFD" type="hidden">
              <input data-id="required:input" name="required" value="list,email,first_name" type="hidden">
              <input data-id="url:input" name="url" value="" type="hidden">
                  <input data-id="Email Address:input" placeholder="<?php echo $this->__('Email') ?>" class="textbox newsletter-email" name="email" value="" maxlength="80" type="text">
                  <input data-id="First Name:input" placeholder="<?php echo $this->__('Name') ?>" class="textbox newsletter-name" name="first_name" value="" maxlength="50" type="text">
                <div class="subscribe-btn-wrp">
                  <button type="button" class="pinkBG Button ctct-button Button--block Button-secondary newsletter-submit submitBtn submitBtnCust " data-enabled="enabled">Subscribe<img id="loader" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/md-theme/images/subscribe-loader.gif" alt="" style="display: none;"/></button>
                  <label>
                    
                  </label>
                </div>
              </form>
            </div>
          </div>

          <script type="text/javascript">var localizedErrMap={};localizedErrMap['required']='This field is required.';localizedErrMap['ca']='An unexpected error occurred while attempting to send email.';localizedErrMap['email']='Please enter your email address in name@email.com format.';localizedErrMap['birthday']='Please enter birthday in MM/DD format.';localizedErrMap['anniversary']='Please enter anniversary in MM/DD/YYYY format.';localizedErrMap['custom_date']='Please enter this date in MM/DD/YYYY format.';localizedErrMap['list']='Please select at least one email list.';localizedErrMap['generic']='This field is invalid.';localizedErrMap['shared']='Sorry, we could not complete your sign-up. Please contact us to resolve this.';localizedErrMap['state_mismatch']='Mismatched State/Province and Country.';localizedErrMap['state_province']='Select a state/province';localizedErrMap['selectcountry']='Select a country';var postURL='https://visitor2.constantcontact.com/api/signup';</script> 
        </div>
            <!-- <form class="wow fadeIn animated" data-wow-delay="0.3s">
                <input type="text" name="Fullname" placeholder="Name">
                <input type="email" name="email" placeholder="Email">
                <button class="pinkBG">
                    Subscribe
                </button>
            </form> -->
        </div>
    </section>

    <section id="CustomDescription">
        <div class="MDcontainer">
            <div class="leftSide">
                <div class="title">
                    <h1>
                        GoodBye

                        <span>
                            hair loss
                        </span>
                    </h1>
                </div> 

                <div class="contentInner">
                    <div class="left wow zoomIn animated" data-wow-delay="0.8">
                        <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/brush.png') ?>" alt=""/> 
                    </div>

                    <div class="right">
                        <div class="top">
                            <p>
                                This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair.
                            </p>
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/description-logos.png') ?>" alt=""/>
                        </div>

                        <div class="bottom">
                            <button class="pinkBG" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>md-nutri-hair';">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/shopping-bag-ico.png') ?>" alt=""/>
                                Add to bag
                            </button>

                            <button class="pinkBorder">
                                <a href="https://www.youtube.com/watch?v=xiIIqeHHY-c&feature=youtu.be" target="_blank" data-lity="">
                                    Learn more
                                </a>
                            </button>
                        </div>

                    </div>
                </div>  

                <div class="contentInnerMobile" style="display: none;">
                    <div class="right">
                        <div class="top">
                            <p>
                                This physician-formulated daily supplement is a clinically-tested drug and hormone free solution for hair growth. MD Nutri Hair also addresses hair breakage and excess shedding—for more beautiful, full, and thick-looking hair.
                            </p>

                            <div class="brush wow zoomIn animated" data-wow-delay="0.8">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/brush.png') ?>" alt=""/> 
                            </div>
                            
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/description-logos.png') ?>" alt=""/>
                        </div>

                        <div class="bottom">
                            <button class="pinkBG" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>md-nutri-hair';">
                                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/shopping-bag-ico.png') ?>" alt=""/>
                                Add to bag
                            </button>

                            <button class="pinkBorder">
                                <a href="https://www.youtube.com/watch?v=xiIIqeHHY-c&feature=youtu.be" target="_blank" data-lity="">
                                    Learn more
                                </a>
                            </button>
                        </div>

                    </div>
                </div>      
            </div>

            <div class="rightSide">
            </div>
        </div>
    </section>

    <section id="Promo">
        <div class="MDcontainer">
            <div class="leftSide">
                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/nutri-hair-med-left.png') ?>" alt=""/ class="wow fadeInUp animated" data-wow-delay="0.5s"> 
            </div>
            <div class="middle">
                <h1>
                    Buy 2 get 1

                    <span>
                        Get your discount code now!
                    </span>
                </h1>
                <div class="ctct-embed-signup reveal-code" style="font: 16px Helvetica Neue, Arial, sans-serif; font: 1rem Helvetica Neue, Arial, sans-serif; line-height: 1.5; -webkit-font-smoothing: antialiased;">
                   <div class="reavel-code" style="color:#5b5b5b; background-color:#e8e8e8; border-radius:5px;">
                       <span id="success_message_revealcode" style="display:none;">
                           <div style="text-align:center;font-size: 18px;margin-top: 44px;background: none;">Please check email after 24 hours. Thanks you!</div>
                       </span>
                       <form data-id="embedded_reveal:form" class="ctct-custom-form Form reveal" name="embedded_signup" method="POST">
                          
                           <!-- The following code must be included to ensure your sign-up form works properly. -->
                           <input data-id="ca:input" type="hidden" name="ca" value="5224d021-d80f-4db5-ad04-84b8bda089b6">
                           <input data-id="list:input" type="hidden" name="list" value="1592355839">
                           <input data-id="source:input" type="hidden" name="source" value="EFD">
                           <input data-id="required:input" type="hidden" name="required" value="list,email">
                           <input data-id="url:input" type="hidden" name="url" value="">
                           <p data-id="Email Address:p" ><input data-id="Email Address:input" type="text" id="reveal-email" name="email" value="" maxlength="80" placeholder="EMAIL"></p>
                           <button type="submit" class="pinkBG Button ctct-button Button--block Button-secondary RevealsubmitBtn" data-enabled="enabled">Reveal Code</button>
                        
                       </form>
                   </div>
                </div>
                <script type='text/javascript'>
                   var localizedErrMap = {};
                   localizedErrMap['required'] =    'This field is required.';
                   localizedErrMap['ca'] =      'An unexpected error occurred while attempting to send email.';
                   localizedErrMap['email'] =       'Please enter your email address in name@email.com format.';
                   localizedErrMap['birthday'] =    'Please enter birthday in MM/DD format.';
                   localizedErrMap['anniversary'] =   'Please enter anniversary in MM/DD/YYYY format.';
                   localizedErrMap['custom_date'] =   'Please enter this date in MM/DD/YYYY format.';
                   localizedErrMap['list'] =      'Please select at least one email list.';
                   localizedErrMap['generic'] =     'This field is invalid.';
                   localizedErrMap['shared'] =    'Sorry, we could not complete your sign-up. Please contact us to resolve this.';
                   localizedErrMap['state_mismatch'] = 'Mismatched State/Province and Country.';
                  localizedErrMap['state_province'] = 'Select a state/province';
                   localizedErrMap['selectcountry'] =   'Select a country';
                   var postURL = 'https://visitor2.constantcontact.com/api/signup';
                </script>
                <script type="text/javascript" src="../skin/frontend/default/md-theme/js/md-js/success-message-revealcode.js"></script> 

                <!-- <form>
                    <input type="email" name="email" placeholder="email">
                    <button class="pinkBG">
                        Reveal Code
                    </button>
                </form> -->
            </div>
            <div class="rightSide">
                <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/nutri-hair-med-right.png') ?>" alt=""/ class="wow fadeInDown animated" data-wow-delay="0.5s"> 
            </div>
        </div>
    </section>


    <section id="Ingredients">
        <div class="MDcontainer">
            <div class="leftSide">
                <h1>
                    Nutri hair

                    <span>
                        ingredients
                    </span>     
                </h1>
            </div>

            <div class="rightSide">
                <div class="firstIngredient wow fadeIn animated" data-wow-delay="0.8">
                    <span></span>
                    <p>
                        Collagen
                    </p>
                </div>

                <div class="secondIngredient wow fadeIn animated" data-wow-delay="1s">
                    <span></span>
                    <p>
                        Lilac Extract
                    </p>
                </div>

                <div class="thirdIngredient wow fadeIn animated" data-wow-delay="1.8s">
                    <span></span>
                    <p>
                        Flaxseed powder
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section id="CustomerReview">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3">
            <div class="leftSide">
                <div class="rating">
                    <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/stars.png') ?>" alt=""/> 
                </div>

                <div class="testimonial">
                    <p>
                        This product qualifies almost as a miracle, as far as I'm concerned. I've been using hair supplements and creams for ages, and I had just gotten a hair extension when I found your product. My thinning hair is filling in, so I no longer need it. PLUS - I've had my husband take it, and HIS thinning hair is filling in! Hallelujah! Thank you, thank you, thank you! 
                    </p>
                </div>

                <div class="author">
                    <span></span>
                    <p>
                        Cyndi W
                    </p>
                </div>
            </div>

            <div class="rightSide">
                <div class="vid">
                    <div class="inner">
                        <a href="https://youtu.be/xiIIqeHHY-c" target="_blank" data-lity="">
                            <img src="<?php echo $this->getSkinUrl('images/md-hair-landing/playbutton-medium.png') ?>" alt=""/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="customFooter">
        <div class="MDcontainer wow fadeIn animated" data-wow-delay="0.3">
            <h1>
                Connect 

                <span>
                    with us
                </span>
            </h1>

            <div class="social">
                <a href="https://www.facebook.com/MDLASHF" class="icon-button facebook">
                    <i class="fa fa-facebook" aria-hidden="true"></i><span></span>
                </a>

                <a href="https://twitter.com/MDLFbySusanLin" class="icon-button twitter">
                    <i class="fa fa-twitter" aria-hidden="true"></i><span></span>
                </a>

                <a href="https://instagram.com/md_factor/" class="icon-button instagram">
                    <i class="fa fa-instagram" aria-hidden="true"></i><span></span>
                </a>
            </div>
        </div>
    </section>

    <section id="Copyright">
        <div class="MDcontainer">
            <p>
                Copyright &copy; 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/><a href="javascript:void(0);">User Agreement</a> and <a href="javascript:void(0);"> Privacy Policy </a>.
            </p>
        </div>
    </section>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/md-js/owl.carousel.js') ?>"></script>

<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>


<script>

    // Fixed Nav

    $(document).ready(function(){


    var myNavBar = {

        flagAdd: true,

        elements: [],

        init: function (elements) {
            this.elements = elements;
        },

        add : function() {
            if(this.flagAdd) {
                for(var i=0; i < this.elements.length; i++) {
                    document.getElementById(this.elements[i]).className += " md-hair-theme";
                }
                this.flagAdd = false;
            }
        },

        remove: function() {
            for(var i=0; i < this.elements.length; i++) {
                document.getElementById(this.elements[i]).className =
                        document.getElementById(this.elements[i]).className.replace( /(?:^|\s)md-hair-theme(?!\S)/g , '' );
            }
            this.flagAdd = true;
        }

    };

    /**
     * Init the object. Pass the object the array of elements
     * that we want to change when the scroll goes down
     */
    myNavBar.init(  [
        "header",
        "header-container",
        "brand"
    ]);

    /**
     * Function that manage the direction
     * of the scroll
     */
    function offSetManager(){

        var yOffset = 0;
        var currYOffSet = window.pageYOffset;

        if(yOffset < currYOffSet) {
            myNavBar.add();
        }
        else if(currYOffSet == yOffset){
            myNavBar.remove();
        }

    }

    /**
     * bind to the document scroll detection
     */
    window.onscroll = function(e) {
        offSetManager();
    }

    /**
     * We have to do a first detectation of offset because the page
     * could be load with scroll down set.
     */
    offSetManager();
    });

/* ROM Script*/
jQuery('input[name="email"]').on('change', function(e){
var email = jQuery('input[name="email"]').val();
});

jQuery('input[name="first_name"]').on('change', function(e){
var name = jQuery('input[name="first_name"]').val();
});

function validateEmail(email) {
  var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  
  return re.test(email);
}


    jQuery('.newsletter-submit').on('click', function(e){

    if(jQuery('.newsletter-name').val() == "" || jQuery('.newsletter-email').val() == "") {
        alert('Please Input Email and Name!'); 
        return false;
    }
    
    if(!validateEmail(jQuery('.newsletter-email').val())){
        alert('Invalid Email!'); 
        return false;
    }

    jQuery('#loader').removeAttr('style');
    
    });


    // AsSeenIn Slider

     $(document).ready(function() {

      $("#AsSeenInSlider").owlCarousel({
        items : 5,
        itemsDesktopSmall : [991,3],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        lazyLoad : true,

        //Autoplay
        autoPlay : true,
        stopOnHover : true,
     
        // Navigation
        navigation : false,
        navigationText : ["prev","next"],
        rewindNav : true,
        scrollPerPage : false,
      });

    });

</script>

</body>
</html>