<!DOCTYPE html>
<html>
<head>
    <!-- Google Analytics Content Experiment code -->
    <script>function utmx_section(){}function utmx(){}(function(){var
    k='137572866-0',d=document,l=d.location,c=d.cookie;
    if(l.search.indexOf('utm_expid='+k)>0)return;
    function f(n){if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.
    indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.
    length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;d.write(
    '<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':
    '://www')+'.google-analytics.com/ga_exp.js?'+'utmxkey='+k+
    '&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().
    valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
    '" type="text/javascript" charset="utf-8"><\/sc'+'ript>')})();
    </script><script>utmx('url','A/B');</script>
    <!-- End of Google Analytics Content Experiment code -->



    <meta property="og:image" content="http://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />
    
    <meta property="og:image:secure_url" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />

    <title>MD Intimate Restore</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />


    <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/intimate-restore.css" type="text/css" />
    
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TPDPWSV');</script>
    <!-- End Google Tag Manager -->
</head>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TPDPWSV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<div class="TopWrapper">
    <div class="custom-container">
        <p>
            <i class="fa fa-phone" aria-hidden="true"></i> Contact Us | 1-888-882-5788
        </p>
        <p>
            <i class="fa fa-truck" aria-hidden="true"></i> Sign Up and Receive Free Shipping
        </p>
    </div>
</div>

<nav class='main-nav' id="main-navWrapper">
    <div class="custom-container">
        <ul class='main-nav'>
            <li>
                <a href='<?php echo Mage::getBaseUrl(); ?>'>
                    <img src="<?php echo $this->getSkinUrl('images/intimate-restore/logo.png') ?>">
                </a>
            </li>
            <li>
                <a href='#description'>
                    how it works
                </a>
            </li>
            <li>
                <a href='#AmazonReview'>
                    reviews
                </a>
            </li>
            <li>
                <a href='https://md-factor.com/shipping-policy/'>
                    satisfaction guarantee
                </a>
            </li>
            <li>
                <a href="<?php echo Mage::getBaseUrl(); ?>md-intimate-restore" class="buynow">
                    Buy now
                </a>
            </li>
            <li>
                <a href="https://www.addtoany.com/share" class="share a2a_dd" style="display: none;">
                    Share
                </a>
            </li>

        </ul>
        <a href='#' id='openup'>
            <img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>">
        </a>

        <span>
            <a href="https://www.addtoany.com/share" class="share a2a_dd">
                <i class="fa fa-reply" aria-hidden="true"></i> Share
            </a>
        </span>
    </div>
</nav>


<div id="headerWrapper">
    <div class="custom-container">
        <div class="left">
            <h1>
                MD INTIMATE RESTORE

                <span>
                    Bring Sexy Back
                </span>
            </h1>

            <p>
                Formulated by Gynecologist <br/> Support Lubrication &amp; Restore Sensitivity
            </p>

            <p>
               Order Today &amp; 
            </p>

            <b>Get 25% Discount</b>

            <div>
                <a href="#getfreesample" data-lity>
                    Try It Now
                </a>
            </div>
        </div>

        <div class="right">
            <img class="price" src="<?php echo $this->getSkinUrl('images/intimate-restore/saleprice.png') ?>">
            <img class="intimate" src="<?php echo $this->getSkinUrl('images/intimate-restore/IntimateRestore.png') ?>">
        </div>
        
    </div>
</div>



<div id="getfreesample" class="lity-hide">
    <div class="ctct-embed-signup intimatefree">
       <span id="success_message" style="display:none;">
           <div style="text-align:center; font-size: 22px;">Please check your email after 24 hours. Thank You!</div>
       </span>
       <form data-id="embedded_signup:form" class="ctct-custom-form Form" name="embedded_signup" method="POST" action="https://visitor2.constantcontact.com/api/signup">
           <!-- The following code must be included to ensure your sign-up form works properly. -->
           <input data-id="ca:input" type="hidden" name="ca" value="bf332ca0-ab4a-484d-866a-bfbcd77fbf5b">
           <input data-id="list:input" type="hidden" name="list" value="2013007040">
           <input data-id="source:input" type="hidden" name="source" value="EFD">
           <input data-id="required:input" type="hidden" name="required" value="list,email">
           <input data-id="url:input" type="hidden" name="url" value="">
           <div data-id="Email Address:p" ><input data-id="Email Address:input" type="text" name="email" value="" maxlength="80" placeholder="EMAIL"></div>
           
           <button type="submit" class="Button ctct-button Button--block Button-secondary intimatemdfriend" data-enabled="enabled">SUBMIT</button>
       </form>
    </div>
    <script type='text/javascript'>
       var localizedErrMap = {};
       localizedErrMap['required'] =        'This field is required.';
       localizedErrMap['ca'] =          'An unexpected error occurred while attempting to send email.';
       localizedErrMap['email'] =           'Please enter your email address in name@email.com format.';
       localizedErrMap['birthday'] =        'Please enter birthday in MM/DD format.';
       localizedErrMap['anniversary'] =     'Please enter anniversary in MM/DD/YYYY format.';
       localizedErrMap['custom_date'] =     'Please enter this date in MM/DD/YYYY format.';
       localizedErrMap['list'] =            'Please select at least one email list.';
       localizedErrMap['generic'] =         'This field is invalid.';
       localizedErrMap['shared'] =      'Sorry, we could not complete your sign-up. Please contact us to resolve this.';
       localizedErrMap['state_mismatch'] = 'Mismatched State/Province and Country.';
        localizedErrMap['state_province'] = 'Select a state/province';
       localizedErrMap['selectcountry'] =   'Select a country';
       var postURL = 'https://visitor2.constantcontact.com/api/signup';
    </script>
    <script type='text/javascript' src='https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/js/signup-form.js'></script>
</div>


<div id="promo">
    <div class="custom-container">
        <div class="left wow fadeInUp animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/promo-intimate-left.png') ?>"> 
        </div>
        <div class="middle">
            <h1>
                SIGN UP FOR FREE SHIPPING <br/>&amp; FREE SAMPLE
            </h1>
            <p>
                OVER 1 MILLION CUSTOMERS WORLDWIDE
            </p>

            <div class="ctct-embed-signup subscription">
            <div class="fields clearfix">
              <span id="success_message_subscription" style="display:none;">
                <div style="text-align:center;font-size:32px;color:#000">Please check your email after 24 hours. Thank You!</div>
              </span>
              
              <form data-id="embedded_signup1:form" class="ctct-custom-form Form subscribe" name="embedded_signup" method="POST" >
              <input data-id="ca:input" name="ca" value="2d6dc7e8-e33d-4b40-8040-12f779675aaf" type="hidden">
              <input data-id="list:input" name="list" value="1275815905" type="hidden">
              <input data-id="source:input" name="source" value="EFD" type="hidden">
              <input data-id="required:input" name="required" value="list,email" type="hidden">
              <input data-id="url:input" name="url" value="" type="hidden">
                  <input data-id="Email Address:input" placeholder="<?php echo $this->__('Email') ?>" class="textbox newsletter-email" name="email" value="" maxlength="80" type="text">
                  <!-- <input data-id="First Name:input" placeholder="<?php echo $this->__('Name') ?>" class="textbox newsletter-name" name="first_name" value="" maxlength="50" type="text"> -->
                <div class="subscribe-btn-wrp">
                  <button type="button" class="pinkBG Button ctct-button Button--block Button-secondary newsletter-submit submitBtn submitBtnCust " data-enabled="enabled">BECOME A MD FRIEND<img id="loader" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/md-theme/images/subscribe-loader.gif" alt="" style="display: none;"/></button>
                  <label>
                    
                  </label>
                </div>
              </form>
            </div>
          </div>

          <script type="text/javascript">var localizedErrMap={};localizedErrMap['required']='This field is required.';localizedErrMap['ca']='An unexpected error occurred while attempting to send email.';localizedErrMap['email']='Please enter your email address in name@email.com format.';localizedErrMap['birthday']='Please enter birthday in MM/DD format.';localizedErrMap['anniversary']='Please enter anniversary in MM/DD/YYYY format.';localizedErrMap['custom_date']='Please enter this date in MM/DD/YYYY format.';localizedErrMap['list']='Please select at least one email list.';localizedErrMap['generic']='This field is invalid.';localizedErrMap['shared']='Sorry, we could not complete your sign-up. Please contact us to resolve this.';localizedErrMap['state_mismatch']='Mismatched State/Province and Country.';localizedErrMap['state_province']='Select a state/province';localizedErrMap['selectcountry']='Select a country';var postURL='https://visitor2.constantcontact.com/api/signup';</script> 
           

            <!-- <form>
                <input type="text" name="Email" placeholder="EMAIL">
                <a href="javascript:void(0);">
                    Become a MD Friend
                </a>
            </form> -->
            <span>
                We protect your personal information. We use secure transaction.
            </span>
        </div>
        <div class="right wow fadeInDown animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/promo-intimate-right.png') ?>"> 
        </div>
    </div>
</div>



<div id="AsSeenIn">
    <div class="custom-container">
        <h2>
            As Seen In
        </h2>
        <div id="AsSeenInSlider" class="owl-carousel">
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/cosmopolitan-logo.png') ?>">
            </a>
            <a class="item link">
                <img class="intimate" src="<?php echo $this->getSkinUrl('images/intimate-restore/marie-claire-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/the-new-york-times-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/allure-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/womens-health-logo.png') ?>">
            </a>
        </div>
    </div>
</div>

<div id="description">
    <div class="custom-container">
        <div class="left">
            <div class="inner">
                <h2>
                    WHY INTIMATE RESTORE?
                </h2>
                <p>
                    Feminine skin can change from stress, childbirth, aging, over usage and medications. As we age, many things change, including decreased nerve endings of the intimate area making it more difficult for many woman to achieve pleasurable intimacy. 
                </p>
            </div>
            <div class="inner">
                <h2>
                    HOW DOES INTIMATE RESTORE HELP ME?
                </h2>
                <p>
                    If you want to rejuvenate your intimate area look and feel younger we have the perfect solution for you. Formulated by a gynecologist, MD Intimate Restore is a great natural way to rejuvenate the intimate area by using peptides, vitamins and anti-oxidants. One of the things we should not forget is the intimate area ages the same way as the rest of the body, and it also needs proper care.
                </p>
            </div>

            <a href="#getfreesample" data-lity>
                Try It Now
            </a>

        </div>
    </div>
</div>


<div id="AmazonReview">
    <div class="custom-container">
        <h1>
            Our Customers give MD Factor
        </h1>

        <p>
            4.2 out of 5 stars
        </p>
        
        <span>
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/four-stars.png') ?>">
        </span>

        <a class="testi" href="https://md-factor.com/blog/md-intimate-restore-reviews/">
            See our amazon reviews
        </a>
        
        <span class="amazon">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/amazon-logo.png') ?>">
        </span>

        <!--<a class="button" href="https://www.amazon.com/MD-Factor-IR-60-Intimate-Restore/dp/B00KGNC4KU/ref=sr_1_1_a_it?ie=UTF8&qid=1485974696&sr=8-1&keywords=MD+Intimate+restore">
            check Out on amazon
        </a>-->

        <a class="button" href="https://md-factor.com/blog/md-intimate-restore-reviews/">
            check Out on amazon
        </a>
       

    </div>
</div>


<div id="testimonial">
    <div class="custom-container">
        <div class="left">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/stars.png') ?>">
            <p>
                Thank you for Intimate Restore in helping me enjoy being intimate again. I thought something was wrong with me but this has help me feel good again. Took about 1 week to notice difference.
            </p>
            <span>
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/author.jpg') ?>">
                <p>
                    Janica N.
                </p>
            </span>
        </div>
        <div class="right">
            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/gjyR33NIu1o" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ingredients">
    <div class="custom-container">
        <div class="left">
            <p>
                Anti-Aging

                <span>
                    ingredients
                </span>
            </p>
        </div>

        <div class="right">
            <div class="inner wow zoomIn animated" data-wow-delay="0s">
                <div></div>
                <p>
                    Palmitoyl Tetrapeptides
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="1s">
                <div></div>
                <p>
                    Green Tea
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="2s">
                <div></div>
                <p>
                    Panthenol
                </p>
            </div>
        </div>
    </div>
</div>



<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="<?php echo Mage::getBaseUrl(); ?>/terms-and-conditions/">User Agreement</a> and <a href="<?php echo Mage::getBaseUrl(); ?>privacy-policy">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>

<script type="text/javascript" src="js/lib/jquery/jquery-1.10.2.js"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>

<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>

<script>
    $(document).ready(function() {
        $(document).on('click', '.submitBtnCust', function(){
        var ca = $('form[data-id="embedded_signup1:form"] input[data-id="ca:input"]').val();
        var email = $('form[data-id="embedded_signup1:form"] input[data-id="Email Address:input"]').val();
        var list = $('form[data-id="embedded_signup1:form"] input[data-id="list:input"]').val();
        var source = $('form[data-id="embedded_signup1:form"] input[data-id="source:input"]').val();
        
        postURL = 'https://visitor2.constantcontact.com/api/signup?'+ 'ca='+ ca + '&email='+ email +'&list';
            $.ajax({
                type: 'POST',
                crossDomain: true,
                url: postURL,
            error: function(xhr, status, err) {
                
                alert('error');
            },
            success: function(data, status, xhr) {
                $('.ctct-embed-signup.subscription p').hide();
                $('.ctct-embed-signup.subscription h2').hide();
                $('.ctct-embed-signup.subscription button').hide();
                $('.ctct-embed-signup.subscription form').hide();
                $('#success_message_subscription').removeClass('u-hide');
                $('#success_message_subscription').show();
    
            }
        });
    });
});
</script>


    <script>

    

    $(document).ready(function() {

      $("#AsSeenInSlider").owlCarousel({
    items : 5,
    itemsCustom : false,
    itemsDesktop : [1199,4],
    itemsDesktopSmall : [980,3],
    itemsTablet: [768,2],
    itemsTabletSmall: false,
    itemsMobile : [479,1],
    singleItem : false,
    itemsScaleUp : false,
 
    //Basic Speeds
    slideSpeed : 200,
    paginationSpeed : 800,
    rewindSpeed : 1000,
 
    //Autoplay
    autoPlay : true,
    stopOnHover : true,
 
    // Navigation
    navigation : false,
    navigationText : ["prev","next"],
    rewindNav : true,
    scrollPerPage : false,
 
    //Pagination
    pagination : true,
    paginationNumbers: false,
 
    // Responsive 
    responsive: true,
    responsiveRefreshRate : 200,
    responsiveBaseWidth: window,
 
    // CSS Styles
    baseClass : "owl-carousel",
    theme : "owl-theme",
 
    //Lazy load
    lazyLoad : true,
    lazyFollow : true,
    lazyEffect : "fade",
      });

      $('.link').on('click', function(event){
        var $this = $(this);
        if($this.hasClass('clicked')){
          $this.removeAttr('style').removeClass('clicked');
        } else{
          $this.css('background','transparent').addClass('clicked');
        }
      });


    });


    </script>

<script type="text/javascript">

$(function() {
    menu = $('nav ul');

    $('#openup').on('click', function(e) {
        e.preventDefault(); menu.slideToggle();
    });
  
    $(window).resize(function(){
        var w = $(this).width(); if(w > 760 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
  
    $('nav li').on('click', function(e) {                
        var w = $(window).width(); if(w < 760 ) {
            menu.slideToggle(); 
        }
    });
    
    $('.open-menu').height($(window).height());
});

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>

</body>
</html>