<!DOCTYPE html>
<html>
<head>
    <meta property="og:image" content="http://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />
    
    <meta property="og:image:secure_url" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />

    <title>MD Intimate Restore</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />


    <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/intimate-restore.css" type="text/css" />
    
            <!-- BEGIN GOOGLE ANALYTICS CODE -->
        <script type="text/javascript">
        //<![CDATA[
            var _gaq = _gaq || [];
            
_gaq.push(['_setAccount', 'UA-89987290-1']);

_gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        //]]>
        </script>
        <!-- END GOOGLE ANALYTICS CODE -->
    <!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '1010013549017189');
    fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=1010013549017189&ev=PageView&noscript=1"
        /></noscript>
<!-- End Facebook Pixel Code -->
</head>

<body class="intimate-restore-yellow">

<div class="TopWrapper">
    <div class="custom-container">
        <p>
            <i class="fa fa-phone" aria-hidden="true"></i> Contact Us | 1-888-882-5788
        </p>
        <p>
            <i class="fa fa-truck" aria-hidden="true"></i> Sign Up and Receive Free Shipping
        </p>
    </div>
</div>

<nav class='main-nav' id="main-navWrapper">
    <div class="custom-container">
        <ul class='main-nav'>
            <li>
                <a href='<?php echo Mage::getBaseUrl(); ?>'>
                    <img src="<?php echo $this->getSkinUrl('images/intimate-restore/logo.png') ?>">
                </a>
            </li>
            <li>
                <a href='#description'>
                    how it works
                </a>
            </li>
            <li>
                <a href='#AmazonReview'>
                    reviews
                </a>
            </li>
            <li>
                <a href='https://md-factor.com/shipping-policy/'>
                    satisfaction guarantee
                </a>
            </li>
            <li>
                <a href="<?php echo Mage::getBaseUrl(); ?>md-intimate-restore" class="buynow">
                    Buy now
                </a>
            </li>
            <li>
                <a href="https://www.addtoany.com/share" class="share a2a_dd" style="display: none;">
                    Share
                </a>
            </li>

        </ul>
        <a href='#' id='openup'>
            <img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>">
        </a>

        <span>
            <a href="https://www.addtoany.com/share" class="share a2a_dd">
                <i class="fa fa-reply" aria-hidden="true"></i> Share
            </a>
        </span>
    </div>
</nav>


<div id="headerWrapper">
    <div class="custom-container">
        <img class="MainCat" src="<?php echo $this->getSkinUrl('images/intimate-restore/cat-gif-bling.gif') ?>">
        <div class="inner">
            <h1>
                MD INTIMATE RESTORE
            </h1>
            <p>
                Be A Classy, Sexy <img src="<?php echo $this->getSkinUrl('images/intimate-restore/inlove-cat.png') ?>">
            </p>
            <span>
                Support Lubrication &amp; Restore Sensitivity
            </span>
            <div>
                <a href="javascript:void(0);">
                    Get your free sample
                </a>
            </div>
        </div>
        <img class="intimate wow slideInRight animated" data-wow-delay="0.5s" src="<?php echo $this->getSkinUrl('images/intimate-restore/IntimateRestore.png') ?>">
    </div>
</div>


<div id="AsSeenIn">
    <div class="custom-container">
        <h2>
            As Seen In
        </h2>
        <div id="AsSeenInSlider" class="owl-carousel">
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/cosmopolitan-logo.png') ?>">
            </a>
            <a class="item link">
                <img class="intimate" src="<?php echo $this->getSkinUrl('images/intimate-restore/marie-claire-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/the-new-york-times-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/allure-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/womens-health-logo.png') ?>">
            </a>
        </div>
    </div>
</div>

<div id="description">
    <div class="custom-container">
        <div class="left">
            <div class="inner">
                <h2>
                    WHY INTIMATE RESTORE?
                </h2>
                <p>
                    Feminine skin can change from stress, childbirth, aging, over usage and medications. As we age, many things change, including decreased nerve endings of the intimate area making it more difficult for many woman to achieve pleasurable intimacy. 
                </p>
            </div>
            <div class="inner">
                <h2>
                    HOW DOES INTIMATE RESTORE HELP ME?
                </h2>
                <p>
                    If you want to rejuvenate your intimate area look and feel younger we have the perfect solution for you. Formulated by a gynecologist, MD Intimate Restore is a great natural way to rejuvenate the intimate area by using peptides, vitamins and anti-oxidants. One of the things we should not forget is the intimate area ages the same way as the rest of the body, and it also needs proper care.
                </p>
            </div>

            <a href="https://youtu.be/m3O7yjaCoHk" target="_blank" data-lity="">
                How does it work?
            </a>

            <a href="https://www.youtube.com/watch?v=-TRk9ATsyWc" target="_blank" data-lity="">
                Learn More
            </a>
        </div>
    </div>
</div>


<div id="AmazonReview">
    <div class="custom-container">
        <h1>
            Our Customers give MD Factor
        </h1>

        <p>
            4.2 out of 5 stars
        </p>
        
        <span>
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/four-stars.png') ?>">
        </span>

        <a class="testi" href="https://md-factor.com/md-intimate-restore-reviews/">
            See our amazon reviews
        </a>
        
        <span class="amazon">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/amazon-logo.png') ?>">
        </span>

        <a class="button" href="https://www.amazon.com/MD-Factor-IR-60-Intimate-Restore/dp/B00KGNC4KU/ref=sr_1_1_a_it?ie=UTF8&qid=1485974696&sr=8-1&keywords=MD+Intimate+restore">
            check Out on amazon
        </a>
       

    </div>
</div>


<div id="testimonial">
    <div class="custom-container">
        <div class="left">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/stars.png') ?>">
            <p>
                Thank you for Intimate Restore in helping me enjoy being intimate again. I thought something was wrong with me but this has help me feel good again. Took about 1 weeks to notice difference.
            </p>
            <span>
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/author.jpg') ?>">
                <p>
                    Cyndi W
                </p>
            </span>
        </div>
        <div class="right">
            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/gjyR33NIu1o" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ingredients">
    <div class="custom-container">
        <div class="left">
            <p>
                Anti-Aging

                <span>
                    ingredients
                </span>
            </p>
        </div>

        <div class="right">
            <div class="inner wow zoomIn animated" data-wow-delay="0s">
                <div></div>
                <p>
                    Palmitoyl Tetrapeptides
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="1s">
                <div></div>
                <p>
                    Green Tea
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="2s">
                <div></div>
                <p>
                    Panthenol
                </p>
            </div>
        </div>
    </div>
</div>
       

<div id="promo">
    <div class="custom-container">
        <div class="left wow fadeInUp animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/promo-intimate-left.png') ?>"> 
        </div>
        <div class="middle">
            <h1>
                SIGN UP FOR FREE SHIPPING <br/>&amp; FREE SAMPLE
            </h1>
            <p>
                OVER 1 MILLION CUSTOMERS WORLDWIDE
            </p>
            <form>
                <input type="text" name="Email" placeholder="EMAIL">
                <a href="javascript:void(0);">
                    Become a MD Friend
                </a>
            </form>
            <span>
                We protect your personal information. We use secure transaction.
            </span>
        </div>
        <div class="right wow fadeInDown animated" data-wow-delay="0.5s">
            <img src="<?php echo $this->getSkinUrl('images/intimate-restore/promo-intimate-right.png') ?>"> 
        </div>
    </div>
</div>


<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="javascript:void(0);">User Agreement</a> and <a href="javascript:void(0);">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>

<script type="text/javascript" src="js/lib/jquery/jquery-1.10.2.js"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>

<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>


    <script>
    $(document).ready(function() {

      $("#AsSeenInSlider").owlCarousel({
    items : 5,
    itemsCustom : false,
    itemsDesktop : [1199,4],
    itemsDesktopSmall : [980,3],
    itemsTablet: [768,2],
    itemsTabletSmall: false,
    itemsMobile : [479,1],
    singleItem : false,
    itemsScaleUp : false,
 
    //Basic Speeds
    slideSpeed : 200,
    paginationSpeed : 800,
    rewindSpeed : 1000,
 
    //Autoplay
    autoPlay : true,
    stopOnHover : true,
 
    // Navigation
    navigation : false,
    navigationText : ["prev","next"],
    rewindNav : true,
    scrollPerPage : false,
 
    //Pagination
    pagination : true,
    paginationNumbers: false,
 
    // Responsive 
    responsive: true,
    responsiveRefreshRate : 200,
    responsiveBaseWidth: window,
 
    // CSS Styles
    baseClass : "owl-carousel",
    theme : "owl-theme",
 
    //Lazy load
    lazyLoad : true,
    lazyFollow : true,
    lazyEffect : "fade",
      });

      $('.link').on('click', function(event){
        var $this = $(this);
        if($this.hasClass('clicked')){
          $this.removeAttr('style').removeClass('clicked');
        } else{
          $this.css('background','transparent').addClass('clicked');
        }
      });


    });


    </script>

<script type="text/javascript">

$(function() {
    menu = $('nav ul');

    $('#openup').on('click', function(e) {
        e.preventDefault(); menu.slideToggle();
    });
  
    $(window).resize(function(){
        var w = $(this).width(); if(w > 760 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
  
    $('nav li').on('click', function(e) {                
        var w = $(window).width(); if(w < 760 ) {
            menu.slideToggle(); 
        }
    });
    
    $('.open-menu').height($(window).height());
});

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>
</body>
</html>