<!DOCTYPE html>
<html>
<head>
	<title>MD Privacy Policy</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="privacypolicy">

<div class="normalpageNav">
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/topnavigation.phtml')->toHtml(); ?>
</div>


<div class="contentWrapper">
	<div class="custom-container">
		<p><strong>What Information do we collect</strong></p>

		<ul>
			<li>We collect information from you when you register on our site.</li>
			<li>When ordering or registering on our site, as appropriate, you may be asked to enter your: name or e-mail address. You may however, visit our site anonymously.</li>
		</ul>
			
		<p><strong>What do we use your information for</strong></p>
		
		<p>Any of the information we collect from you may be used in one of the following ways:</p>
		
		<ul>
			<li>To personalize your experience (your information helps us to better respond to your individual needs).</li>
			<li>To improve our website (we continually strive to improve our website offerings based on information and feedback we receive from you).</li>
			<li>To improve customer service (your information helps us to more effectively respond to your customer service request and support needs).</li>
			<li>To process transactions
				<ul>
					<li>Your information will not be sold, exchanged, transferred or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested by the customer</li>
				</ul>
			</li>
			<li>To send periodic emails.
				<ul>
					<li>The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information.</li>
				</ul>
			</li>
			<li>To administer a contest, promotion, survey or other site feature.</li>
		</ul>
		
		<p><strong>How do we protect your identity</strong></p>
		
		<ul>
			<li>We implement a variety of security measures to maintain the safety of your personal information when you access your personal information.</li>
		</ul>
			
		<p><strong>Do we disclose any information to third parties</strong></p>
		
		<ul>
			<li>We do not sell, trade, or otherwise transfer to third parties your personal information. This does not include trusted third parties who assist us in conducting our business or servicing you, so long as those parties agree to keep this information confidential.</li>
		</ul>
		
		<p><strong>Your consent</strong></p>
		
		<ul>
			<li>By using our site, you consent to our privacy policy.</li>
		</ul>
	</div>
</div>

<?php echo $this->getChildHtml('footer') ?>

</body>
</html>