<!DOCTYPE html>
<html>
<head>
	<title>MD Shipping Policy</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>


</head>

<body class="shipping-policy">

<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/custom-top-menu.phtml')->toHtml(); ?>

<div class="contentWrapper">
	<div class="custom-container">
		<h2>SHIPPING &amp; RETURNS POLICY </h2>
		<div class="row">
			<strong>RETURNS</strong>
			<ul>
				<li>
				We want you to be totally satisfied with your order, however we understand if a product doesn&#39;t work out and want to make sure the return is as painless as possible. </li>
			</ul>
			<b>ONLINE PURCHASE RETURN</b>
			<ul>
				<li>
				If you wish to return a product, please do so within 30 days from the ship date for a refund on the purchase price, minus shipping, handling charges. Refunds will be credited to the original credit card use for payment. Purchases of gift certificates and sale items cannot be returned for a refund. </li>
				<li>
				Naturally, we cannot take returns products not bought online at <a href="www.md-factor.com" style="color:#0d6ba9; text-decoration: underline;"> MD Factor </a>
				</li>
				<li>
				To return items to <a href="www.md-factor.com" style="color:#0d6ba9; text-decoration: underline;"> MD Factor </a>, please follow these simple steps:
				<ol>
					<li>
					Call our customer service at (877) 215-0155 M-F PST 8-6 </li>
					<li>
					We recommend shipping your return with a service that provides tracking and insurance as we are not responsible for any packages lost in transit. All returns should be mailed to:
					<ul>
						<li>
						La Canada Ventures Inc, 448 N San Mateo Drive, San Mateo, CA 94401 </li>
					</ul>
					</li>
				</ol>
				</li>
				<li>
				Your return will be processed promptly upon arrival, and we will send you a confirmation by email. Please allow 2-3 weeks from the shipping date for your account to be credited. Shipping and handling charges are not refundable. </li>
			</ul>
		</div>
		<div class="row">
			<strong>SHIPPING POLICIES</strong>
			<ol>
				<li>All of our products are in stock and will be shipped from our warehouse in US.</li>
				<li>Most orders are shipped within 8 business hours and sent out via mailing carrier based on customer's preference.</li>
				<li>Orders placed after 3PM PST will be processed following day. We ship Monday through Friday 9-3 PST excluding holidays and weekends.</li>
				<li>Contact us directly by phone 1-888-882-5788 or email customercare@mdlashfactor.com to cancel your order within 24 hours at no additional charge. Due to efficiency of our team, if order cancelled after 24 hours, you will be responsible for $25.00 restocking fee if your order has already been shipped.</li>
				<li>To receive tracking information, please select express delivery. USPS confirmation number verifies when parcel has been delivered and not used to track packages en route. Unfortunately we are not responsible for damage, lost package or delay by USPS, FedEx, DHL or UPS.</li>
			</ol>
			<b>FOR INTERNATIONAL ORDERS:</b>
			<ol>
				<li>International shipping is provided via FedEx; lead times can be up to two weeks for international packages.</li>
				<li>MD&reg; is not responsible for taxes, duty charges,customs fees or shipping loss or damages.</li>
				<li>Different countries have different shipping rates, MD reserve right to adjust shipping fee. You will be notified by email and we will await for your approval prior to shipping.</li>
				<li>Contact us directly by phone 1-888-882-5788 or email customercare@mdlashfactor.com to cancel your order within 24 hours at no additional charge. Due to efficiency of our team, if order cancelled after 24 hours, you will be responsible for $25.00 restocking fee if your order has already been shipped.</li>
				<li>Various countries have different regulations, MD is not responsible if shipment does not clear custom and we will not be able to refund the purchase.</li>
			</ol>
		</div>
		<div class="row">
			<table class="table-bordered table-striped table-condensed cf">
				<thead class="cf shippingTitle">
					<tr>
						<th>
							Shipping <strong>(orders under $99.00)</strong>
						</th>
						<th>
							Shipping Cost
						</th>
					</tr>
				</thead>
			<tbody>
			<tr>
				<td data-column="Shipping (Orders under $99.00)">
					Ground Shipping (4-6 days)
				</td>
				<td data-column="Shipping Cost">
					$4.95
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (Orders under $99.00)">
					Priority Shipping ( 2-3 days)
				</td>
				<td data-column="Shipping Cost">
					$19.95
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (Orders under $99.00)">
					Overnight Shipping
				</td>
				<td data-column="Shipping Cost">
					$49.95
				</td>
			</tr>
			<tr class="shippingTitle">
				<td>
					Shipping Option <strong>(orders over $99.00)</strong>
				</td>
				<td>
					&nbsp;
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (Orders over $99.00)">
					Ground Shipping (4-6 Days)
				</td>
				<td data-column="Shipping Cost">
					FREE
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (Orders over $99.00)">
					Priority Shipping (2-3 Days)
				</td>
				<td data-column="Shipping Cost">
					$19.95
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (Orders over $99.00)">
					Overnight Shipping
				</td>
				<td data-column="Shipping Cost">
					$49.95
				</td>
			</tr>
			<tr class="shippingTitle">
				<td class="shippingTitle">
					 Shipping <strong>(INTERNATIONAL)</strong>
				</td>
				<td>
					 &nbsp;
				</td>
			</tr>
			<tr>
				<td data-column="Shipping (International)">
					Standard Shipping
				</td>
				<td data-column="Shipping Cost">
					By Weight. We reserve right to notify you by email if destination country require higher shipping fee. For purchases over $150 free international shipping, we reserve the right to chose the carrier and class of shipping. If you desire expedited or overnight shipping, additional fee will be applied.
				</td>
			</tr>
			</tbody>
			</table>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('footer') ?>

</body>
</html>