<!DOCTYPE html>
<html>
<head>
	<title>MD Terms and Conditions</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?php echo $this->getChildHtml('head') ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">


</head>

<body class="termsandconditions">

<div class="normalpageNav">
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/topnavigation.phtml')->toHtml(); ?>
</div>

<div class="contentWrapper">
	<div class="custom-container">
		<div class="col-sm-2">
			<nav class="nav-sidebar">
				<ul class="nav tabs">
					<li class="active"><a href="#tab1" data-toggle="tab">Autoship Policy</a></li>
					<li class=""><a href="#tab2" data-toggle="tab">Contest Policy</a></li>
					<li class=""><a href="#tab3" data-toggle="tab">Guarantee Policy</a></li>
					<li class=""><a href="#tab4" data-toggle="tab">Return Policy</a></li>
				</ul>
			</nav>
		</div>
		<!-- tab content -->
		<div class="tab-content">
			<div class="tab-pane active text-style" id="tab1">
				<h2>Auto-Delivery Offers</h2>
				<p>
					LA CANADA VENTURES, INC / MD may offer auto-delivery of a product with promotional pricing and/or bonus gifts and/or free shipping costs on certain items. These offers are subject to these terms and conditions and/or to change without notice.
				</p>
				<p>
					Auto-delivery of items happen in a recurring cycle of once every 90 days. One discount and/or bonus gift item(s) shall be applied per order unless otherwise stated. For MD Hair Utimate VIP Members, discounts and/or bonus gifts apply only to first payment and/or shipment; discount and/or bonus gifts will not apply to remaining automatic payments. Customers have the option of paying once per month or once every three months, as stated at the time of ordering.
				</p>
				<p>
					Customers are advised to read the details of auto-delivery under the product descriptions for each offer. Customers may choose to cancel auto-delivery at any time, but will be held responsible for any monies due and owing for any product that is not returned within 30 days of receipt.
				</p>
			</div>
			<div class="tab-pane text-style" id="tab2">
				<h2>MD Lash Factor Giveaway Contest</h2>
				<p>
					MD is giving away a FULL YEAR SUPPLY of MD LASH FACTOR EYELASH CONDITIONER to one lucky winner.<br/>
					Enter the #MDLashFactorGiveaway contest today!<br/>
					Post a picture of how you rock your luscious lashes to Instagram or Facebook!<br/>
					The most creative entry will win a full year supply of MD Lash Factor-value of $280!
				</p>
				<br/>
				<strong>CONTEST GUIDELINES: </strong>
				<ul class="contest">
					<li>Post your picture with the hashtag #MDLashFactorGiveaway</li>
					<li>Make sure to tag @MD_Factor in your post </li>
					<li>Make sure your profile is set to public (not private) so that we can see all of your entries</li>
					<li>Get creative and have fun!!</li>
				</ul>
				<p>
					<span style="color:red;">***</span> Multiple entries are ok! Post as many times as you like! (No duplicate photos)<br/>
					<span style="color:red;">***</span> The contest will run from February 5th to February 19th! The winner will be announced on February 22nd!<br/>
					<span style="color:red;">***</span> We are excited to see you let loose with your lashes! GOOD LUCK!!!
				</p>
			</div>
			<div class="tab-pane text-style" id="tab3">
				<h2>Guarantee Policy</h2>
				<ol>
					<li>Limit one guarantee policy related refund per purchaser over the purchaser's lifetime. </li>
					<li>The purchaser agrees to act with integrity, in kind spirit and without intent to defraud when requesting a guarantee policy related refund.</li>
					<li>We reserve the right to invalidate the guarantee policy at our sole discretion at any time (even retroactively), for any reason or for no reason. This is to prevent people from stealing from us. </li>
				</ol>
				<p>
					In your email to us, please include your name, e-mail address, order number (if available), the last four digits of your credit card number, a copy of your paper/digital invoice or a printed copy of your e-mail receipt, and the reason for return.
				</p>
			</div>
			<div class="tab-pane text-style" id="tab4">
				<div id="footer-content-wrapper" class="section">
					<div class="return row">
						<div class="row">
							<h2>Return Policy</h2>
							<ol>
								<li>
								While we take pride in offering our customers a top quality product, occasionally manufacturer defects do occur. Should you experience an issue with the packaging of the product, please contact us directly to authorize a product return, within 30 days of purchase. Otherwise, all sales are final and no returns or exchanges. </li>
								<li>
								MD does not process returns from products purchased through other websites, stores or unauthorized resellers. </li>
								<li>
								Unopened bottles returned within 60 days of shipment with receipt will receive a full refund minus shipping and handling. </li>
								<li>
								Opened bottles will not receive refunds, as opened bottles will be discarded upon return. </li>
								<li>
								Undelivered orders due to our error will be re-shipped at no additional charge. </li>
								<li>
								Undelivered orders due to customer error will be re-shipped at the customer's expense. Shipping and handling charges for return orders are not refunded for returns due to customer error. </li>
							</ol>
						</div>
						<div class="row">
							<div class="col-xs-3">
								<p>
									 Please send returns to:<br/><br/>
									<strong>MD Customercare<br/>
									448 N. San Mateo Dr.<br/>
									San Mateo, CA 94401</strong>
								</p>
							</div>
							<div class="col-xs-9">
								<p>
									 Please include your name, e-mail address, order number (if available), the last four digits of your credit card number, a copy of your paper invoice or a printed copy of your e-mail receipt, and the reason for return.
								</p>
								<p>
									 Because returns may occassionally be lost in transit, we recommend (but do not require) using a reliable delivery service (e.g. UPS Ground or FedEx Ground) that offers tracking or delivery confirmation.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('footer') ?>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>	