<!DOCTYPE html>
<html>
<head>
    <!-- Google Analytics Content Experiment code -->
    <script>function utmx_section(){}function utmx(){}(function(){var
    k='137572866-0',d=document,l=d.location,c=d.cookie;
    if(l.search.indexOf('utm_expid='+k)>0)return;
    function f(n){if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.
    indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.
    length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;d.write(
    '<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':
    '://www')+'.google-analytics.com/ga_exp.js?'+'utmxkey='+k+
    '&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().
    valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
    '" type="text/javascript" charset="utf-8"><\/sc'+'ript>')})();
    </script><script>utmx('url','A/B');</script>
    <!-- End of Google Analytics Content Experiment code -->



    <meta property="og:image" content="http://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />
    
    <meta property="og:image:secure_url" content="https://us.md-factor.com/skin/frontend/default/md-theme/images/intimate-restore/IntimateRestore-fb-thumbnail.png" />

    <title>MD Irresistible Beauty</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <link rel="icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />
    
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico') ?>" type="image/x-icon" />

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/lity.min.css" media="all" />


    <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bridal.css" type="text/css" />
    
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TPDPWSV');</script>
    <!-- End Google Tag Manager -->
</head>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TPDPWSV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<div class="TopWrapper">
    <div class="custom-container">
        <p>
            <i class="fa fa-phone" aria-hidden="true"></i> Contact Us | 1-888-882-5788
        </p>
        <p>
            <i class="fa fa-truck" aria-hidden="true"></i> Sign Up and Receive Free Shipping
        </p>
    </div>
</div>

<nav class='main-nav' id="main-navWrapper">
    <div class="custom-container">
        <ul class='main-nav'>
            <li>
                <a href='<?php echo Mage::getBaseUrl(); ?>'>
                    <img src="<?php echo $this->getSkinUrl('images/intimate-restore/logo.png') ?>">
                </a>
            </li>
            <li>
                <a href='#description'>
                    What is MD Lash Factor
                </a>
            </li>
            <li>
                <a href='#AmazonReview'>
                    How does it work
                </a>
            </li>
            <li>
                <a href='https://md-factor.com/shipping-policy/'>
                    satisfaction guarantee
                </a>
            </li>
            <li>
                <a href="<?php echo Mage::getBaseUrl(); ?>md-intimate-restore" class="buynow">
                    Buy now
                </a>
            </li>
            <li>
                <a href="https://www.addtoany.com/share" class="share a2a_dd" style="display: none;">
                    Share
                </a>
            </li>

        </ul>
        <a href='#' id='openup'>
            <img src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>">
        </a>

        <span>
            <a href="https://www.addtoany.com/share" class="share a2a_dd">
                <i class="fa fa-reply" aria-hidden="true"></i> Share
            </a>
        </span>
    </div>
</nav>

<div id="headerWrapper" class="headerone">
    <div class="custom-container desktop">
        <div class="left">
            <h1>
                GLOWING <br/>WEDDING BEAUTY
            </h1>

            <p>
                PHYSICIAN FORMULATED NATURAL DRUG FREE FORMULA
            </p>

            <div>
                <a href="#getfreesample" data-lity>
                    Order Yours Now
                </a>
            </div>
        </div>

        <div class="right">
            <div>
                <img src="<?php echo $this->getSkinUrl('images/bridal/header-products-one.png') ?>">
            </div>

            <div>
                <img src="<?php echo $this->getSkinUrl('images/bridal/awards.png') ?>">
            </div>
        </div>
    </div>

    <div class="custom-container mobile">
        <div class="top">
            <h1>
                GLOWING <br/>WEDDING BEAUTY
            </h1>

            <p>
                PHYSICIAN FORMULATED NATURAL DRUG FREE FORMULA
            </p>
        </div>

        <div class="bottom">
           
            <div>
                <a href="#getfreesample" data-lity>
                    Order Yours Now
                </a>
            </div>
        </div>
    </div>
</div>

<div id="getfreesample" class="lity-hide">
    <div class="ctct-embed-signup intimatefree">
       <span id="success_message" style="display:none;">
           <div style="text-align:center; font-size: 22px;">Please check your email after 24 hours. Thank You!</div>
       </span>
       <form data-id="embedded_requiredsignup:form" class="ctct-custom-form Form" name="embedded_signup" method="POST" action="https://visitor2.constantcontact.com/api/signup">
           <!-- The following code must be included to ensure your sign-up form works properly. -->
           <input data-id="ca:input" type="hidden" name="ca" value="bf332ca0-ab4a-484d-866a-bfbcd77fbf5b">
           <input data-id="list:input" type="hidden" name="list" value="2013007040">
           <input data-id="source:input" type="hidden" name="source" value="EFD">
           <input data-id="required:input" type="hidden" name="required" value="list,email">
           <input data-id="url:input" type="hidden" name="url" value="">
           <div data-id="Email Address:p" ><input data-id="Email Address:input" type="text" name="email" value="" maxlength="80" placeholder="EMAIL"></div>
           
           <button type="submit" class="Button ctct-button Button--block Button-secondary intimatemdfriend" data-enabled="enabled">SUBMIT</button>
       </form>
    </div>
    <script type='text/javascript'>
       var localizedErrMap = {};
       localizedErrMap[''] =        'This field is required.';
       localizedErrMap['ca'] =          'An unexpected error occurred while attempting to send email.';
       localizedErrMap['email'] =           'Please enter your email address in name@email.com format.';
       localizedErrMap['birthday'] =        'Please enter birthday in MM/DD format.';
       localizedErrMap['anniversary'] =     'Please enter anniversary in MM/DD/YYYY format.';
       localizedErrMap['custom_date'] =     'Please enter this date in MM/DD/YYYY format.';
       localizedErrMap['list'] =            'Please select at least one email list.';
       localizedErrMap['generic'] =         'This field is invalid.';
       localizedErrMap['shared'] =      'Sorry, we could not complete your sign-up. Please contact us to resolve this.';
       localizedErrMap['state_mismatch'] = 'Mismatched State/Province and Country.';
        localizedErrMap['state_province'] = 'Select a state/province';
       localizedErrMap['selectcountry'] =   'Select a country';
       var postURL = 'https://visitor2.constantcontact.com/api/signup';
    </script>
    <script type='text/javascript' src='https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/js/signup-form.js'></script>
</div>

<div id="promo">
    <div class="custom-container">
        <div class="middle">
            <h1>
                free shipping 
            </h1>
            <p>
                plus free sample with first order
            </p>
            <div>
                <a href="javascript:void(0);">
                    Subscribe Now
                </a>
            </div>
        </div>
    </div>
</div>

<div id="description">
    <div class="custom-container">
        <div class="right">
            <h3> 
                for
            </h3>

            <h1>
                irresistible beauty
                <span>
                    on your special day
                </span>
            </h1>

            <p>
                Bring Sexy Back, Gorgeous Long Full Hair and Lash Your Special Day. 
            </p>

            <strong> 
                Bundle Includes:
            </strong>

            <ul>
                <li>
                    MD Intimate Restore ($60.00)
                </li>
                <li>
                    MD Vitamin C Serum ($120.00)
                </li>
                <li>
                    NEW MD Lash Factor Eyelash Conditioner 2.95ml ($99.00)
                </li>
            </ul>

            <div class="price">
                <div class="inner">
                    <span>
                        <strike>
                            $279
                        </strike>
                    </span>

                    <p>
                        $205
                    </p>
                </div>
            </div>

            <div class="autoshipWrapper">
                <div class="inner">
                    <div class="custom-checkbox">
                        <input type="checkbox" value="None" id="custom-checkbox" name="check" checked/>
                        <label for="custom-checkbox">
                            <span>
                                Autoship every 90 days
                            </span>
                        </label>
                    </div>
                </div>

                <p>
                    Enjoy the special bundle saving and receive autoship every 90 days
                </p>
            </div>


            <div class="button">
                <a href="javascript:void(0);">
                    Order Now
                </a>
            </div>
        </div>
    </div>
</div>


<div id="AsSeenIn">
    <div class="custom-container">
        <h2>
            As Seen In
        </h2>
        <div id="AsSeenInSlider" class="owl-carousel">
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/cosmopolitan-logo.png') ?>">
            </a>
            <a class="item link">
                <img class="intimate" src="<?php echo $this->getSkinUrl('images/intimate-restore/marie-claire-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/the-new-york-times-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/allure-logo.png') ?>">
            </a>
            <a class="item link">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/womens-health-logo.png') ?>">
            </a>
        </div>
    </div>
</div>

<div id="howitworks">
    <div class="custom-container desktop">
        <div class="left">
            <div class="inner">
                <h2>
                    How it works?
                </h2>

                <strong>
                    MD INTIMATE RESTORE
                </strong>

                <p>
                    Intimate restore uses anti-aging peptide technology to rejuvenate feminine area to improve appearance, sensitivity and tone.      
                </p>

                <strong>
                    MD LASH FACTOR: LASH CONDITIONER
                </strong>

                <p>
                    Our award winning lash conditioner designed to make your lashes reach their fullest potential in length, thickness and fullness in 6-8 weeks.  Apply nightly to upper lash lines similar to application of eyeliner after applying eye cream and moisturizers.  3 month supply. 
                </p>

                <strong> 
                    MD VITAMIN C SERUM
                </strong>

                <p>
                    High potency 20% L-Ascorbic Acid works quickly to penetrate your skin and bring back your youthful glow. Brightens your complexion and minimize appearance of fine lines with natural anti-oxidants.
                </p>
            </div>
                
            <div>
                <a class="add-to-bag" href="#>">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/bag.png') ?>">
                    Add to bag
                </a>
                <div id="popupTest" class="lity-hide" style="display: none;">
                    <div class="inner">
                        <p>
                            Sorry this bundle is currently available for US customers only.
                        </p>
                    </div>
                </div>

                <a href="https://youtu.be/QUQR0xiWyvI" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-1.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-1.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-2.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-2.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-3.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-3.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-4.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-4.jpg') ?>">
                    </a> 
                </div> 
            </div>

            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/QUQR0xiWyvI" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-container mobile" style="display: none;">

        <div class="right">
            <h2>
                Before &amp; After
            </h2>
            
            <div class="BeforeAndAfterSlider" class="owl-carousel">
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-1.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-1.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-2.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-2.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-3.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-3.jpg') ?>">
                    </a> 
                </div> 
                <div class="item">
                    <a class="imageWrapper" href="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-4.jpg') ?>" data-lity="" data-lity-desc="">
                        <img src="<?php echo $this->getSkinUrl('images/bridal/beforeandafter-lash-4.jpg') ?>">
                    </a> 
                </div> 
            </div>
        </div>
        <div class="left">
            <div class="inner">
                <h2>
                    How it works?
                </h2>

                <strong>
                    MD INTIMATE RESTORE
                </strong>

                <p>
                    Intimate restore uses anti-aging peptide technology to rejuvenate feminine area to improve appearance, sensitivity and tone.      
                </p>

                <strong>
                    MD LASH FACTOR: LASH CONDITIONER
                </strong>

                <p>
                    Our award winning lash conditioner designed to make your lashes reach their fullest potential in length, thickness and fullness in 6-8 weeks.  Apply nightly to upper lash lines similar to application of eyeliner after applying eye cream and moisturizers.  3 month supply. 
                </p>

                <strong> 
                    MD VITAMIN C SERUM
                </strong>

                <p>
                    High potency 20% L-Ascorbic Acid works quickly to penetrate your skin and bring back your youthful glow. Brightens your complexion and minimize appearance of fine lines with natural anti-oxidants.
                </p>
            </div>
                
            <div>
                <a class="add-to-bag" href="#">
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/bag.png') ?>">
                    Add to bag
                </a>
                <div id="popupTest" class="lity-hide" style="display: none;">
                    <div class="inner">
                        <p>
                            Sorry this bundle is currently available for US customers only.
                        </p>
                    </div>
                </div>

                <a href="https://youtu.be/QUQR0xiWyvI" target="_blank" data-lity="">
                    Learn More
                </a>
            </div>
        </div>

        <div class="right">
            <div class="vid">
                <div class="inner">
                    <a href="https://youtu.be/QUQR0xiWyvI" target="_blank" data-lity="">
                        <img src="<?php echo $this->getSkinUrl('images/intimate-restore/playbutton-medium.png') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="ingredients">
    <div class="custom-container">
        <div class="left">
            <p>
                Key

                <span>
                    ingredients
                </span>
            </p>
        </div>

        <div class="right">
            <div class="inner wow zoomIn animated" data-wow-delay="0s">
                <div></div>
                <p>
                    Panthenol
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="1s">
                <div></div>
                <p>
                    Anti-Aging Peptides
                </p>
            </div>
            
            <div class="inner wow zoomIn animated" data-wow-delay="2s">
                <div></div>
                <p>
                    Green tea extract
                </p>
            </div>
        </div>
    </div>
</div>

<div id="testimonial">
    <div class="custom-container">
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
                Wonderful product, thank you to a wonderful team and excellent customer service! You're the best. Have never experienced a product that worked so well, I can literally see how my lashes grow longer and thicker. Much appreciation.
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-1.jpg') ?>">
                    <a href="javascript:void(0);">
                        Cyndi W
                    </a>
                </span>
            </div>
        </div>
        <div class="inner">
            <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/stars.png') ?>">
            <p>
               AMAZING product! I really did see a difference in lashes and brows!
            </p>
            <div>
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/hairkit-bundle/author-2.jpg') ?>">
                    <a href="javascript:void(0);">
                        Peggy J.
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

<div id="promoForm">
    <div class="custom-container">
        <div class="middle">
            <h1>
                SIGN UP FOR FREE SHIPPING <br/>&amp; FREE SAMPLE
            </h1>
            <p>
                OVER 1 MILLION CUSTOMERS WORLDWIDE
            </p>
            <form>
                <input type="text" name="Email" placeholder="EMAIL">
                <a href="javascript:void(0);">
                    Become a MD Friend
                </a>
            </form> 

            

            <span>
                <p>
                    We protect your personal information. We use secure transaction.
                </p>
            </span>
        </div>
    </div>
</div>


<div id="about">
    <div class="title">
        <div class="custom-container">
            <img src="<?php echo $this->getSkinUrl('images/guruu/healthy-hair-bundle/founder.jpg') ?>">
            <p>
                <span>
                    About DR Susan Lin            
                </span>
            </p>
        </div>
    </div>

    <div class="custom-container">  

        <ul>
            <li>
                <div class="inner">
                    Dr. Susan F. Lin is a practicing surgeon focusing on woman's health, antiaging and aesthetics medicine in San Francisco Area for 26 years. Dr. Lin graduated from Boston University School of Medicine with NIH Cancer Research Fellowship. She completed postdoctural training in Ob/GYN at Kaiser Permanente Oakland, Felix Rutledge Oncology Fellowship at MD Anderson Cancer Center and Galloway Fellowship in Gynecology Oncology at Memorial Sloan Kettering Cancer Center.
                </div>
            </li>

            <li>
                <div class="inner">
                    Dr. Lin has been fellow of American College of OB/GYN, American Academy of Anti Aging Medicine, American Academy of Aesthetic Medicine, American Society for Laser Medicine and Surgery, Expert Reviewer for Medical Board of California and Assistant Clinical Professor of OB/GYN for UCSF School of Medicine.
                </div>
            </li>

            <li>
                <div class="inner">
                    Dr. Lin directs MD Laser &amp; Cosmetics Center in San Mateo California and is the founder and president of La Canada Venture Inc. holding patient for lash and hair innovations. <a href="http://md-factor.com/">www.md-factor.com</a>. Currently serves on board for McGovern Institute of Brain Research at Massachusetts Institute of Technology and Community Gatepath for disabled children and adults.
                </div>
            </li>
        </ul>
    </div>
</div>


<div id="footer">
    <div class="custom-container">
        <p>
            Copyright © 2016 MD Factor. All RIghts Reserved. Designated trademarks and brands are the property of their respective owners. Use of this Web site constitutes acceptance of the MD Factor <br/>
            <a href="<?php echo Mage::getBaseUrl(); ?>/terms-and-conditions/">User Agreement</a> and <a href="<?php echo Mage::getBaseUrl(); ?>privacy-policy">Privacy Policy</a>.
        </p>
        <span>
            <a href="https://www.facebook.com/MDLASHF">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/fb.png') ?>"> 
            </a>
            <a href="https://twitter.com/MDLFbySusanLin">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/twitter.png') ?>"> 
            </a>
            <a href="https://instagram.com/md_factor/">
                <img src="<?php echo $this->getSkinUrl('images/intimate-restore/instagram.png') ?>"> 
            </a>
        </span>
    </div>
</div>

<script type="text/javascript" src="js/lib/jquery/jquery-1.10.2.js"></script>

<script src="<?php echo $this->getSkinUrl(); ?>js/carousel/owl.carousel.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/md-js/lity.min.js"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/wow.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/animation/animate-custom.min.js') ?>"></script>

<!-- Share button -->

<script>
var a2a_config = a2a_config || {};
a2a_config.num_services = 2;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>

<script>
    $(document).ready(function() {
        $(document).on('click', '.submitBtnCust', function(){
        var ca = $('form[data-id="embedded_signup1:form"] input[data-id="ca:input"]').val();
        var email = $('form[data-id="embedded_signup1:form"] input[data-id="Email Address:input"]').val();
        var list = $('form[data-id="embedded_signup1:form"] input[data-id="list:input"]').val();
        var source = $('form[data-id="embedded_signup1:form"] input[data-id="source:input"]').val();
        
        postURL = 'https://visitor2.constantcontact.com/api/signup?'+ 'ca='+ ca + '&email='+ email +'&list';
            $.ajax({
                type: 'POST',
                crossDomain: true,
                url: postURL,
            error: function(xhr, status, err) {
                
                alert('error');
            },
            success: function(data, status, xhr) {
                $('.ctct-embed-signup.subscription p').hide();
                $('.ctct-embed-signup.subscription h2').hide();
                $('.ctct-embed-signup.subscription button').hide();
                $('.ctct-embed-signup.subscription form').hide();
                $('#success_message_subscription').removeClass('u-hide');
                $('#success_message_subscription').show();
    
            }
        });
    });
});
</script>


<script>
$(document).ready(function() {

    $("#AsSeenInSlider").owlCarousel({
        items : 5,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : false,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 200,
        paginationSpeed : 800,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : true,
        stopOnHover : true,
     
        // Navigation
        navigation : false,
        navigationText : ["prev","next"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
    });

    $(".BeforeAndAfterSlider").owlCarousel({
        items : 1,
        itemsCustom : false,
        itemsDesktop : [1199,4],
        itemsDesktopSmall : [980,3],
        itemsTablet: [768,2],
        itemsTabletSmall: false,
        itemsMobile : [479,1],
        singleItem : true,
        itemsScaleUp : false,
     
        //Basic Speeds
        slideSpeed : 5000,
        paginationSpeed : 3000,
        rewindSpeed : 1000,
     
        //Autoplay
        autoPlay : false,
        stopOnHover : true,
     
        // Navigation
        navigation : true,
        navigationText : ["<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-left-arrow.png') ?>'>","<img src='<?php echo $this->getSkinUrl('images/hairkit-bundle/slider-right-arrow.png') ?>'>"],
        rewindNav : true,
        scrollPerPage : false,
     
        //Pagination
        pagination : true,
        paginationNumbers: false,
     
        // Responsive 
        responsive: true,
        responsiveRefreshRate : 200,
        responsiveBaseWidth: window,
     
        // CSS Styles
        baseClass : "owl-carousel",
        theme : "owl-theme",
     
        //Lazy load
        lazyLoad : true,
        lazyFollow : true,
        lazyEffect : "fade",
    });

    $('.link').on('click', function(event){
        var $this = $(this);
        if($this.hasClass('clicked')){
          $this.removeAttr('style').removeClass('clicked');
        } else{
          $this.css('background','transparent').addClass('clicked');
        }
    });
});


</script>

<script type="text/javascript">

$(function() {
    menu = $('nav ul');

    $('#openup').on('click', function(e) {
        e.preventDefault(); menu.slideToggle();
    });
  
    $(window).resize(function(){
        var w = $(this).width(); if(w > 760 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
  
    $('nav li').on('click', function(e) {                
        var w = $(window).width(); if(w < 760 ) {
            menu.slideToggle(); 
        }
    });
    
    $('.open-menu').height($(window).height());
});

var offset = $('#main-navWrapper').offset();
$(window).scroll(function(){
   
    $('#main-navWrapper').addClass('fixed-nav');
    
    if($(document).scrollTop() < 120){
        $('#main-navWrapper').removeClass('fixed-nav');
    }

});

$(window).scroll(function() {
    if ($(this).scrollTop() > 120){  
        $('#main-navWrapper').addClass("sticky");
    }
    else{
        $('#main-navWrapper').removeClass("sticky");
    }
});

</script>

</body>
</html>