
<div id="co-billing-form">
    <ul class="form-list">

        <?php if(!$this->isCustomerLoggedIn()): ?>
    
            <?php $guest_allowed = $this->getQuote()->isAllowedGuestCheckout(); if($guest_allowed): ?>
                <li class="control hidden">
                    <input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?php echo  $this->__('Create an account for later use') ?>"  class="checkbox" checked>
                    <label for="billing:create_account"><?php echo  $this->__('Create an account for later use') ?></label>
                </li>
                
                <?php else:?>
                    <input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
            <?php endif;?>
            

            <li class="fields <?php if($guest_allowed):?><?php endif;?>" id="register-customer-password">

                 <!-- Password -->

                <fieldset id="register_password" class="">
                    <strong  class="title">
                        It looks like you're new here
                    </strong>

                    <p class="subtitle">
                        Please enter a password to create your account and continue to delivery and payment.
                    </p>

                    <div class="form-group">

                        <label for="billing[customer_password]" class="control-label">
                            <?php echo $this->__('Password') ?>
                        </label>

                        <input type="password" class="form-control" autocomplete="off" value="" id="billing:customer_password" name="billing[customer_password]" placeholder="Password">
                    </div>
                    
                    <div class="NextButton">
                        <a class="btn btn-primary nextCustomReg">Continue</a>
                    </div>
                </fieldset>

                <!-- End of Password -->

                <!-- Confirm Password -->

                <fieldset id="register_confirm_password" class="">
                    <strong  class="title">
                        It looks like you're new here
                    </strong>

                    <p class="subtitle">
                        Please confrim your password.
                    </p>

                    <div class="form-group">
                        <label for="billing[confirm_password]" class="control-label">
                            Confirm password
                        </label>
                        
                        <input type="password" class="form-control" autocomplete="off" value="" id="billing:confirm_password" name="billing[confirm_password]" placeholder="Password">
                    </div>

                    <div class="PrevButton">
                        <a class="btn btn-primary" id="PreviousToRegisterPass">Previous</a>
                    </div>
                    
                    <div class="NextButton">
                        <a class="btn btn-primary nextCustomReg">
                            Continue
                        </a>
                    </div>
                </fieldset>

                <!-- End Confirm Password -->

            </li>
        <?php endif;?>

        <fieldset id="register_details" class="">      
            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide">
                    <label for="billing-address-select" class="notice"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                </li>
            <?php endif; ?>

            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
                
                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
               
                <ul>
                    <li class="fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?> 
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="billing:company">
                                <?php echo $this->__('Company') ?>
                            </label>
                            
                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('company') ?>" />
                        </div>

                        <?php if(!$this->isCustomerLoggedIn()): ?>
                            <div class="field">
                                <label for="billing:email" class="required">
                                    <em>*</em>
                                    <?php echo $this->__('Email Address') ?>
                                </label>

                                <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                            </div>
                        <?php endif; ?>
                    </li>

                    <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>

                    <li class="wide">
                        <label for="billing:street1" class="required">
                            <em>*</em>
                            <?php echo $this->__('Address') ?>
                        </label>

                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </li>

                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    
                        <li class="wide">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </li>
                    <?php endfor; ?>

                    <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                        <li class="wide">
                            <label for="billing:vat_id">
                                <?php echo $this->__('VAT Number') ?>
                            </label>
                            
                            <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                        </li>
                    <?php endif; ?>

                    <li class="fields">
                        <div class="field">
                            <label for="billing:city" class="required"><em>*</em>
                                <?php echo $this->__('City') ?>
                            </label>
                            
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="billing:city" />
                        </div>

                        <div class="field">
                            <label for="billing:region_id" class="required">
                                <em>*</em>
                                <?php echo $this->__('State / Province') ?>
                            </label>

                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State / Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            
                            <script type="text/javascript">
                                //<![CDATA[
                                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                            </script>
                                
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State / Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="billing:postcode" class="required">
                                <em>*</em><?php echo $this->__('Zip') ?>
                            </label>

                            <input type="text" title="<?php echo $this->__('Zip') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>" />
                        </div>

                        <div class="field">
                            <label for="billing:country_id" class="required">
                                <em>*</em><?php echo $this->__('Country') ?>
                            </label>
                            
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="billing:telephone" class="required">
                                <em>*</em><?php echo $this->__('Telephone') ?>
                            </label>
                            
                            <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                        </div>

                        <div class="field">
                            <label for="billing:fax">
                                <?php echo $this->__('Fax') ?>
                            </label>
                            
                            <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                        </div>
                    </li>

                    <?php if(!$this->isCustomerLoggedIn()): ?>

                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                            <li class="fields">
                                <?php if ($_dob->isEnabled()): ?>
                                    <div class="field">
                                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif; ?>
                                
                                <?php if ($_gender->isEnabled()): ?>
                                    <div class="field">
                                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif ?>
                            </li>
                        <?php endif ?>

                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li>
                                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                        <?php endif ?>
                    <?php endif; ?>

                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                        </li>
                        <?php else:?>
                            <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                    <?php endif; ?>
                    
                    <?php echo $this->getChildHtml('form.additional.info'); ?>

                </ul>
            </li>

            <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>

    <!-- fix browser autocomplete -->
    <div style="display:none !important">
        <input type="text" autocomplete="off" value="" />
        <input type="password" autocomplete="off" value=""/>
    </div>
    <!-- end fix browser autocomplete -->
    
   
    
    <?php if ($this->canShip()): ?>
        <li class="control <?php if (!Mage::helper('opc')->isShowShippingForm()):?>hidden<?php endif;?>">
            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>

        </fieldset>
    </ul>
</div>

<script type="text/javascript">

//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
//]]>
</script>


