<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
?>

<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $accountUrl = Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl());
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $accountUrl = $this->getCreateAccountUrl();
    }
?>

<!-- Edited By Rej -->

<div class="account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('paypalauth.login'); ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" class="OPCMain-Form" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <!-- Patrick Added Ajax Customer Email checker -->
        <!-- Login Email -->
        <fieldset id="login_email">

            <strong class="title">
                Hi there !
            </strong>

            <p class="subtitle">
                Please enter your email address to continue to delivery and payment.
            </p>

            <div class="form-group">
                <label for="login[username]" class="control-label">
                    <?php echo $this->__('Email Address') ?> 
                </label>

                <!--<input type="email" class="form-control MDLogin" id="email" name="login[username]" value="<?php //echo $this->htmlEscape($this->getUsername()) ?>"  placeholder="Type your email here">-->
                <input type="email" class="form-control MDLogin" id="email" name="login[username]" value=""  placeholder="Type your email here">
            </div>  

            <div class="NextButton">
                <a class="btn btn-primary nextCustomLogin">
                    Continue
                </a>
            </div>
        </fieldset>
        <!-- End of Login Email -->
        <!-- Login Password -->
        <fieldset id="login_password" class="hide">
            <strong class="title">Welcome Back</strong>
            <p class="subtitle">Please enter your password to continue to delivery and payment.</p>

            <div class="form-group">
                <label for="login[password]" class="control-label"><?php echo $this->__('Password') ?></label>
                <input type="password" class="form-control required-entry validate-password" id="pass" name="login[password]" placeholder="Password">
            </div>
                          
            <?php echo $this->getChildHtml('persistent.remember.me'); ?> 
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            
            <button type="submit" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
                <a><?php echo $this->__('Continue') ?></a>
            </button>
            <a href="#" id="OPC-ForgotPassword" class="forgotpass"><?php echo $this->__('Forgot your password?') ?></a>

            <?php if ($isContextCheckout): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
        </fieldset>
        <!-- End of Login Password -->
    </form>
         <!-- Login Email -->
        <form method="post" class="OPCGuests-Form" id="formGuests">
            <fieldset id="login_guest" class="hide">

                <strong class="title">
                    Hi Guest!
                </strong>
                <p class="subtitle">
                    We need your email to send you your receipt.
                </p>
                <div class="form-group">
                    <label for="guestlogin[username]" class="control-label">
                        <?php echo $this->__('Email Address') ?> 
                    </label>
                    <input type="text" class="required-entry validate-email" id="email" name="guestlogin[username]" placeholder="Type your email here">
                </div> 
                <div class="NextButton">
                    <input type="submit" value="Continue" class="btn btn-primary nextGuestLogin">
                </div>
            </fieldset>
        </form>
        <!-- End of Login Email -->

        <fieldset id="registration_password" class="hide">
        <?php echo $this->getLayout()->createBlock('customer/form_register')->setTemplate('customer/form/register2.phtml')->toHtml(); ?>
            <?php if ($isContextCheckout): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
            </form>
        </fieldset>

</div>

<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        jQuery("#formGuests").submit(function(e){
                e.preventDefault();
            });
        jQuery('.nextGuestLogin').on('click', function(){
            var guestsForm = new VarienForm('formGuests', true);
            if (guestsForm .validator.validate()){
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #opc-address-form-billing #register_details').show();
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #login_guest').addClass('hide');
                jQuery('body.opc-index-index .opc-wrapper-opc .shipping-session').removeClass('hide');    
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-right').removeClass('hide'); 
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center .checkout-selector').addClass('hide');  
                  
            }else{
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #opc-address-form-billing #register_details').hide();
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #login_guest').removeClass('hide');      
                jQuery('body.opc-index-index .opc-wrapper-opc .shipping-session').addClass('hide');  
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-right').addClass('hide');  
            } 
            jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center .TabLabel[for="tab1"]').on('click', function(){
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #content2').addClass('SectionTabWrapper'); 
            });
            jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center .TabLabel[for="tab2"]').on('click', function(){
                jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center #content2').removeClass('SectionTabWrapper'); 
            });
        });
    //]]>
</script>

<script type="text/javascript">
var url = '<?php echo Mage::getBaseUrl();?>email-lists/index/ajax';
jQuery(document).on('click', '.opc-index-index .nextCustomLogin', function(){
    var mail = jQuery('.opc-index-index input.MDLogin').val();
    var dataForm = new VarienForm('login-form', true);
    jQuery.ajax({
        type: "POST",
        url: url,
        dataType: "json",
        data: {email: mail},
        success: function (exists) {
            jQuery('.opc-index-index #login_password').removeClass('hide'); 
            jQuery('.opc-index-index #registration_password').addClass('hide'); 
        },
        error: function (exists, jqXHR, textStatus, errorThrown) {
           jQuery('.opc-index-index #registration_password').removeClass('hide'); 
           var email = jQuery('.opc-index-index input.MDLogin').val();
           localStorage.setItem("email", email);
        }
    });
if (jQuery('.opc-index-index #email-error:contains("Please enter a valid email address.")')){
    jQuery('.opc-index-index #registration_password').hide();      
    jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center .checkout-selector').removeClass('hide');       
}
if (jQuery('.opc-index-index #login_email[style="display: none;"]').length){
    jQuery('.opc-index-index #registration_password').show();  
    jQuery('body.opc-index-index .opc-wrapper-opc .opc-col-center .checkout-selector').addClass('hide');          
}
});

jQuery(document).on('click', '.opc-index-index #OPC-ForgotPassword', function(){
var url = '<?php echo Mage::getBaseUrl();?>customer/account/forgotpasswordpost';
var form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey()?>';
var email =  jQuery('.opc-index-index #login-form input[name="login[username]"]').val();
jQuery.post(url,{'email': email,});
jQuery('.opc-index-index .col-main').before('<ul class="messages"><li class="success-msg"><ul><li><span>If there is an account associated with '+email+' you will receive an email with a link to reset your password.</span></li></ul></li></ul>');
window.setTimeout(function(){
window.location.href = "<?php echo Mage::getBaseUrl();?>onepage/";}, 20000);
});
</script>