<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
?>

<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $accountUrl = Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl());
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $accountUrl = $this->getCreateAccountUrl();
    }
?>

<!-- Edited By Rej -->

<div class="account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('paypalauth.login'); ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <!-- Login Email -->

        <fieldset id="login_email">

            <strong class="title">
                Hi there !
            </strong>

            <p class="subtitle">
                Please enter your email address to continue to delivery and payment.
            </p>

            <div class="form-group">
                <label for="login[username]" class="control-label">
                    <?php echo $this->__('Email Address') ?> 
                </label>

                <input type="email" class="form-control" id="email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>"  placeholder="Type your email here">
            </div>  

            <div class="NextButton">
                <a class="btn btn-primary nextCustomLogin">
                    Continue
                </a>
            </div>
        </fieldset>

        <!-- End of Login Email -->

        <!-- Login Password -->

        <fieldset id="login_password" class="">

            <strong class="title">
                Welcome Back 
            </strong>

            <p class="subtitle">
                Please enter your password to continue to delivery and payment.
            </p>

            <div class="form-group">
                <label for="login[password]" class="control-label">
                    <?php echo $this->__('Password') ?>
                </label>

                <input type="password" class="form-control" id="pass" name="login[password]" placeholder="Password">
            </div>
                          
            <?php echo $this->getChildHtml('persistent.remember.me'); ?> 
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            
            <button type="submit" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
                <a>
                    <?php echo $this->__('Continue') ?>
                </a>
            </button>

            <ul class="links">
                <li><a href="<?php echo $this->getForgotPasswordUrl() ?>">Forgot you password?</a></li>
                <li>
                    <a id="PreviousToLoginEmail">Sign in with another account</a> 
                    <span>
                        - OR- 
                    </span>
                    <a class="nextCustomLogin">Create an account</a>
                </li>
            </ul>


            <?php if ($isContextCheckout): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
        </fieldset>

        <!-- End of Login Password -->

    </form>

</div>

<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
</script>

