<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
?>

<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $accountUrl = Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl());
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $accountUrl = $this->getCreateAccountUrl();
    }
?>

<!-- Edited By Rej -->

<div class="account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('paypalauth.login'); ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" class="OPCMain-Form" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <!-- Patrick Added Ajax Customer Email checker -->
        <!-- Login Email -->
        <fieldset id="login_email">

            <strong class="title">
                Hi there !
            </strong>

            <p class="subtitle">
                Please enter your email address to continue to delivery and payment.
            </p>

            <div class="form-group">
                <label for="login[username]" class="control-label">
                    <?php echo $this->__('Email Address') ?> 
                </label>

                <!--<input type="email" class="form-control MDLogin" id="email" name="login[username]" value="<?php //echo $this->htmlEscape($this->getUsername()) ?>"  placeholder="Type your email here">-->
                <input type="email" class="form-control MDLogin" id="email" name="login[username]" value=""  placeholder="Type your email here">
            </div>  

            <div class="NextButton">
                <a class="btn btn-primary nextCustomLogin">
                    Continue
                </a>
            </div>
        </fieldset>

        <!-- End of Login Email -->

        <!-- Login Password -->
        <fieldset id="login_password" class="hide">
            <strong class="title">Welcome Back</strong>
            <p class="subtitle">Please enter your password to continue to delivery and payment.</p>

            <div class="form-group">
                <label for="login[password]" class="control-label"><?php echo $this->__('Password') ?></label>
                <input type="password" class="form-control required-entry validate-password" id="pass" name="login[password]" placeholder="Password">
            </div>
                          
            <?php echo $this->getChildHtml('persistent.remember.me'); ?> 
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            
            <button type="submit" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
                <a><?php echo $this->__('Continue') ?></a>
            </button>

            <?php if ($isContextCheckout): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
        </fieldset>
        <!-- End of Login Password -->
    </form>

        <fieldset id="registration_password" class="hide">
        <?php echo $this->getLayout()->createBlock('customer/form_register')->setTemplate('customer/form/register2.phtml')->toHtml(); ?>
            <?php if ($isContextCheckout): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
            </form>
        </fieldset>

</div>

<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
</script>

<script type="text/javascript">
var url = '<?php echo Mage::getBaseUrl();?>email-lists/index/ajax';
jQuery('.opc-index-index .nextCustomLogin').on('click', function(){
    var mail = jQuery('.opc-index-index input.MDLogin').val();
    var dataForm = new VarienForm('login-form', true);
    jQuery.ajax({
        type: "POST",
        url: url,
        dataType: "json",
        data: {email: mail},
        success: function (exists) {
            jQuery('.opc-index-index #login_password').removeClass('hide'); 
            jQuery('.opc-index-index #registration_password').addClass('hide');
        },
        error: function (exists, jqXHR, textStatus, errorThrown) {
           jQuery('.opc-index-index #registration_password').removeClass('hide'); 
           var email = jQuery('.opc-index-index input.MDLogin').val();
           localStorage.setItem("email", email);
        }
    });
if (jQuery('.opc-index-index #email-error:contains("Please enter a valid email address.")').length){
    jQuery('.opc-index-index #registration_password').hide();           
}
});
if (jQuery('.opc-index-index #email-error:contains("Please enter a valid email address.")').length){
    jQuery('.opc-index-index #registration_password').hide();           
}
</script>