<?php
/**
 * @project: CartServiceMigrate
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<?php
$list = $this->getApiData();
if(!$list){
    $list = $this->getApiInfoOfFirstCart();
}
?>
<?php if(!$list){?>
    No Api Info.
<?php } else {?>
    <?php foreach($list as $api_key => $api_label){?>
        <div class="form-group">
            <div class="label-field">
                <p>
                    <label><?php echo $api_label; ?>:
                        <span class="required">*</span>
                    </label>
                </p>
            </div>
            <div class="input-field">
                <input type="text" name="api[<?php echo $api_key; ?>]" id="api-<?php echo $api_key; ?>" class="required-entry input-text"/>
            </div>
        </div>
    <?php }?>
    <div class="form-group">
        <div class="label-field">
            <p>
                <label>
                </label>
            </p>
        </div>
        <div class="input-field">
            <div id="error-api" class="validation-advice error-custom"><?php echo $this->__('API info is not correct'); ?></div>
        </div>
    </div>
<?php } ?>