<?php
/**
 * @project: CartServiceMigrate
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<?php $notice = $this->getNotice(); ?>
<form action="" method="post" id="form-config">
<h1 class="header_title">Configuration</h1>
<input type="hidden" name="action" value="config">
<div class="container" id="valid-cat-dup">
    <?php if($notice['config']['config_support']['category_map']){ ?>
    <h1><?php echo $this->__("Root Category"); ?></h1>
    <div class="section_guide">Choose a Category to put migrated categories from Source Cart into.</div>
    <?php foreach($notice['config']['category_data'] as $cat_key => $cat_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p>
                    <label><?php echo $cat_name; ?></label>
                </p>
            </div>
            <div class="input-field">
                <select name="cats[<?php echo $cat_key; ?>]">
                    <?php echo $this->getCategoriesOption("");?>
                </select>
            </div>
        </div>
    <?php } ?>
    <div class="form-group">
        <div class="label-field"><p><label></label></p></div>
        <div class="input-field">
            <p><div class="field-valid validation-advice"><?php echo $this->__('Can not be the same Root Category.'); ?></div></p>
        </div>
    </div>
</div>
<?php } ?>
<?php if($notice['config']['config_support']['attribute_map']){ ?>
    <div class="container" id="valid-attr-dup">
        <h1><?php echo $this->__("Product Attribute Set"); ?></h1>
        <div class="section_guide">Choose an appropriate Product Attribute Set or just leave it Default.</div>
        <?php foreach($notice['config']['attribute_data'] as $attr_key => $attr_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $attr_name; ?></label>
                    </p>
                </div>
                <div class="input-field">
                    <select name="attributes[<?php echo $attr_key; ?>]">
                        <?php echo $this->getAttributesOption("");?>
                    </select>
                </div>
            </div>
        <?php } ?>
        <div class="form-group">
            <div class="label-field"><p><label></label></p></div>
            <div class="input-field">
                <p><div class="field-valid validation-advice"><?php echo $this->__('Can not be the same Attribute Set.'); ?></div></p>
            </div>
        </div>
    </div>
<?php } ?>
<?php if($notice['config']['config_support']['language_map']){ ?>
    <div class="container" id="valid-lang-dup">
        <h1><?php echo $this->__("Languages Mapping"); ?></h1>
        <div class="section_guide">
            If your Source Cart is multilingual, corresponding languages ( or storeviews) should be available
            in Target Magento Store. You may need to create additional languages in Magento Store to avoid data loss.
        </div>
        <?php foreach($notice['config']['languages_data'] as $lang_key => $lang_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $lang_name; ?></label>
                    </p>
                </div>
                <div class="input-field">
                    <select name="languages[<?php echo $lang_key; ?>]">
                        <?php echo $this->getStoresOption('');?>
                    </select>
                </div>
            </div>
        <?php } ?>
        <div class="form-group">
            <div class="label-field"><p><label></label></p></div>
            <div class="input-field">
                <p><div class="field-valid validation-advice"><?php echo $this->__('Can not be the same Store View.'); ?></div></p>
            </div>
        </div>
    </div>
<?php } ?>
<?php if($notice['config']['config_support']['currency_map']){ ?>
    <div class="container">
        <h1><?php echo $this->__("Currencies Mapping"); ?></h1>
        <div class="section_guide">
            Please assign Source Cart currencies to proper Target Magento Store currencies. Creating currencies
            in Target Magento Store may be needed.
        </div>
        <?php foreach($notice['config']['currencies_data'] as $cur_key => $cur_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $cur_name; ?></label>
                    </p>
                </div>
                <div class="input-field">
                    <select name="currencies[<?php echo $cur_key; ?>]">
                        <?php echo $this->getCurrenciesOption('');?>
                    </select>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<?php if($notice['config']['config_support']['order_status_map']){ ?>
    <div class="container">
        <h1><?php echo $this->__("Orders Status Mapping"); ?></h1>
        <div class="section_guide">
            Please assign Source Cart order statuses to proper Target Magento Store order statuses.
            Creating additional order statues in Target Magento Store may be needed.
        </div>
        <?php foreach($notice['config']['order_status_data'] as $ord_stt_key => $ord_stt_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $ord_stt_name; ?></label>
                    </p>
                </div>
                <div class="input-field">
                    <select name="order_status[<?php echo $ord_stt_key; ?>]">
                        <?php echo $this->getOrderStatusOption('');?>
                    </select>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<?php if($notice['config']['config_support']['country_map']){?>
    <div class="container">
        <h1><?php echo $this->__("Countries Mapping"); ?></h1>
        <?php foreach($notice['config']['countries_data'] as $country_key => $country_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $country_name; ?></label>
                    </p>
                </div>
                <div class="input-field">
                    <select name="countries[<?php echo $country_key; ?>]">
                        <?php echo $this->getCountriesOption('');?>
                    </select>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<?php if($notice['config']['config_support']['customer_group_map']){ ?>
    <div class="container">
        <h1><?php echo $this->__("Customer Group Mapping"); ?></h1>
        <?php foreach($notice['config']['customer_group_data'] as $group_key => $group_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p>
                        <label><?php echo $group_name; ?></label>
                    </p>
                </div>
                <div class="input-fields">
                    <p>
                        <select name="customer_group[<?php echo $group_key; ?>]">
                            <?php echo $this->getCustomerGroupOption('');?>
                        </select>
                    </p>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<div class="container" id="valid-entity-sel">
    <h1><?php echo $this->__("Entities to Migrate"); ?></h1>
    <div class="section_guide">Select entities to migrate.</div>
    <div class="form-group entity-sel">
        <div class="lv0">
            <input type="checkbox" class="checkbox" id="select-all"/>
            <label class="form-checkbox"><?php echo $this->__("Select All"); ?></label>
        </div>
        <?php if($notice['config']['import_support']['taxes']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="taxes" id="taxes" class="checkbox lv1"/>
                    <label class="form-checkbox"><?php echo $this->__("Taxes"); ?></label>
                </div>
            </div>
        <?php } ?>
        <?php if($notice['config']['import_support']['manufacturers']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="manufacturers" id="manufacturers" class="checkbox lv1"/>
                    <label class="form-checkbox"><?php echo $this->__("Manufacturers"); ?></label>
                </div>
            </div>
        <?php } ?>
        <?php if($notice['config']['import_support']['categories']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="categories" id="product-categories" class="checkbox lv1"/>
                    <label class="form-checkbox"><?php echo $this->__("Categories"); ?></label>
                </div>
            </div>
        <?php } ?>
        <?php if($notice['config']['import_support']['products']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="products" class="checkbox lv1" />
                    <label class="form-checkbox"><?php echo $this->__("Products"); ?></label>
                </div>
                <?php if($notice['config']['import_support']['reviews']){ ?>
                    <ul class="le-list-select">
                        <li>
                            <input type="checkbox" name="reviews" id="reviews" class="checkbox lv2"/>
                            <label class="form-checkbox"><?php echo $this->__("Reviews"); ?></label>
                        </li>
                    </ul>
                <?php } ?>
            </div>
        <?php } ?>
        <?php if($notice['config']['import_support']['customers']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="customers" id="customers" class="checkbox lv1"/>
                    <label class="form-checkbox"><?php echo $this->__("Customers"); ?></label>
                </div>
            </div>
        <?php } ?>
        <?php if($notice['config']['import_support']['orders']){ ?>
            <div class="lv0">
                <div>
                    <input type="checkbox" name="orders" id="orders" class="checkbox lv1"/>
                    <label class="form-checkbox"><?php echo $this->__("Orders"); ?></label>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="form-group entity-sel">
        <div class="field-valid validation-advice"><?php echo $this->__('You must select at least one entity!') ?></div>
    </div>
</div>
<div class="container">
    <h1><?php echo $this->__("Additional Options"); ?></h1>
    <ul id="add-sel">
        <li>
            <input type="checkbox" name="add_new" class="checkbox" <?php if(LitExtension_CartServiceMigrate_Model_Custom::DEMO_MODE) echo 'disabled="disabled"';?>/>
            <label class="form-checkbox"><?php echo $this->__("Migrate recent data (adds new entities only)"); ?></label>
        </li>
        <li>
            <input type="checkbox" name="clear_data" class="checkbox" />
            <label class="form-checkbox"><?php echo $this->__("Clear current data on Target Store before Migration"); ?></label>
        </li>
        <li>
            <input type="checkbox" name="img_des" class="checkbox" />
            <label class="form-checkbox"><?php echo $this->__("Transfer images from Product descriptions to Target Store"); ?></label>
        </li>
        <li>
            <input type="checkbox" name="pre_cus" class="checkbox" />
            <label class="form-checkbox"><?php echo $this->__("Preserve Customer IDs on Target Store"); ?></label>
        </li>
        <li>
            <input type="checkbox" name="pre_ord" class="checkbox" />
            <label class="form-checkbox"><?php echo $this->__("Preserve Order IDs on Target Store"); ?></label>
        </li>
        <li>
            <input type="checkbox" name="stock" class="checkbox" />
            <label class="form-checkbox"><?php echo $this->__("Ignore stock management for products with quantity = 0"); ?></label>
        </li>
        <li>
            <input type="checkbox" id="choose-seo" name="seo_url" class="checkbox" <?php if(LitExtension_CartServiceMigrate_Model_Custom::DEMO_MODE) echo 'disabled="disabled"';?>/>
            <label class="form-checkbox"><?php echo $this->__("Migrate categories and products SEO URLs"); ?></label>
        </li>
        <div id="seo_plugin" class="form-group hidden">
            <div class="label-field mapping">
                <p><label><?php echo $this->__("Choose Plugin Seo In Source Cart"); ?></label></p>
            </div>
            <div class="input-field">
                <p>
                    <select name="seo_plugin">
                        <?php
                        $seo_plugin = $this->getSeoPlugin($notice['config']['cart_type']);
                        foreach($seo_plugin as $plugin){ ?>
                            <option value="<?php echo $plugin['value']?>"><?php echo $plugin['label'];?></option>
                        <?php } ?>
                    </select>
                </p>
            </div>
        </div>
    </ul>
</div>
<div class="form-submit">
    <div id="form-config-loading" class="form-loading"><?php echo $this->__('Preparing ...')?></div>
    <div id="form-config-submit" class="button-submit">
        <a href="javascript:void(0)" class="lecsmg-button"><?php echo $this->__('Next') ?> &raquo;</a>
    </div>
</div>
<div>
    <a id="form-config-back" href="javascript:void(0)">&laquo; <?php echo $this->__('Back to previous Step') ?></a>
</div>
</form>