<?php $quote = Mage::getSingleton('checkout/session')->getQuote();
	  $store_id = Mage::app()->getStore()->getId();
	  $spend_point = $this->getMaxPointsToCheckout();
	  $earn_rewardpoint = (int)$quote->getEarnRewardpoint();
	  $reward_icon = Mage::helper('rewardpoints/data')->getRewardIconHtml($store_id);
$check = version_compare(Mage::getVersion(),'1.4.0.1','>=');?>
<div id="rewardpoints_box">
<form id="rewardpoints-form" action="<?php echo $this->getUrl('rewardpoints/checkout/rewardPointsPost') ?>"  onsubmit="return false;" method="post">
    <div class="discount discount-codes box" >
        <?php if($check):?><h2 style="background-image: none; padding: 0px 0px 5px 0px;"><?php echo $reward_icon.$this->__('Reward points') ?></h2><?php else:?><h4 style="background-image: : none; padding: 0px;"><?php echo $reward_icon.$this->__('Reward points') ?></h4><?php endif;?>
        <div class="discount-form">
        	<ul id="mw_reward_accordion">
		      <li  class="mw_reward_section">
		     <?php /*?> <a href="#" class="mw_reward_title" style="margin-left:10px;display: block;padding: 0px 5px 5px 10px; text-decoration: none;" <?php if (!sizeof($this->getRewardPointsRule())) echo "style=\"display:none\"";?> ><span id="reward-points-rules-title" style="color: #0A263C;line-height: 1.35;"><?php echo $this->__("You will be awarded <b>%s</b>",Mage::helper('rewardpoints')->formatPoints($earn_rewardpoint,$store_id))?></span><a><?php echo $this->__('View details');?></a><a href="#" class="mw_reward_title" style="margin-left:10px;display: block;padding: 0px 5px 5px 10px; text-decoration: none;" <?php if (!sizeof($this->getRewardPointsRule())) echo "style=\"display:none\"";?> ><span id="reward-points-rules-title" style="color: #0A263C;line-height: 1.35;"><?php echo $this->__("You will be awarded <b>%s</b>",Mage::helper('rewardpoints')->formatPoints($earn_rewardpoint,$store_id))?></span><a><?php echo $this->__('View details');?></a><?php */?>
		        <div <?php if (!sizeof($this->getRewardPointsRule())) echo "style=\"display:none\"";?> ><span id="reward-points-rules-title" style="color: #0A263C;line-height: 1.5;"><?php echo $this->__("You will be awarded <b>%s</b>",Mage::helper('rewardpoints')->formatPoints($earn_rewardpoint,$store_id)." ")?><a id = "mw_view" class="mw_reward_title" style="color: #DC6809 !important;font-weight: bold"href="#"><?php echo $this->__('(Hide)');?></a></span></div>
		        <div  id="reward-points-rules" class="mw_reward_toggle">
		        	<?php foreach($this->getRewardPointsRule() as $rule):?>
		        	<div style="width:100%;font-size: 11px; margin: 0 0 5px 0; overflow: hidden;">
		        		<div><?php echo $this->__('<span style="float: left;">+</span> <div style="margin: 0px 0px 0px 10px;">%s %s</div>',($rule['qty']>1?$rule['qty']." x":""),$rule['message']);?></div>
		        	</div>
		        	<?php endforeach;?>
		        </div>
		      </li>
		    </ul>
		   
			
        	<?php $rate = $this->getPointPerMoney($store_id);?>
        	<?php if($this->_getCustomer()->getId()):?>
	        	<div class="inner">
	        		<div style="margin-top:5px;"><?php echo $this->__("You have <b>%s</b> available <br>(<b>%s</b> = <b>%s</b>)",Mage::helper('rewardpoints')->formatPoints($this->getCurrentRewardPoints(),$store_id),Mage::helper('rewardpoints')->formatPoints($rate[0],$store_id), $this->formatMoney($rate[1]))?></div>
	        		<?php /* ?><label><?php echo $this->__("Slide to specify number of points to redeem")?></label> <?php */?>
	        		<div id="mw_reward_slider_contaner" class="mw_reward_slider_contaner" style="width:215px;">
	        			<div id="mw_reward_decr_handle"></div>
	        			<div id="mw_reward_incr_handle"></div>
	        			<div id="mw_slider" class="mw_reward_select" ></div>
	        		</div>
	        		<div class="pointsWrapper"><label for="mw_amount"><?php echo $this->__("Points to redeem")?> </label><input style="color:#e8408b; width:150px; text-align:center;font-size: 13px;font-weight: bold;" type="text" name="mw_amount" id="mw_amount" /> <label id="mw_label_amount" style="color:#f6931f; font-weight:bold;display:none;"></label></div>
	        		<div ><input type="checkbox" name="mw_use_max_points" id="mw_use_max_points" /><label for="mw_use_max_points"><?php echo $this->__("Use maximum (<b>%s</b>)",Mage::helper('rewardpoints')->formatPoints($spend_point,$store_id));?></label></div>
              		
				</div>
		         <?php else:?>
		         <div style="text-align: center; margin-top:10px; border-top: 1px dashed;padding-top: 10px;"><?php echo $this->__("Please <a href='%s'>LOGIN</a> to use reward points", Mage::getUrl('customer/account/login',array('mw_re_login' => 1)))?></div>
	            <?php endif;?>
            <div style="clear:both;"></div>
		</div>
	</div>
</form>
</div>
<?php 
$point = $quote->getMwRewardpoint();
$step = Mage::helper('rewardpoints/data')->getPointStepConfig($store_id);
$min = (int)Mage::helper('rewardpoints/data')->getMinPointCheckoutStore($store_id);

?>

<script type="text/javascript">
document.observe('dom:loaded', function(){
    
    // simple
    accordion = new Accordion('mw_reward_accordion', { startHidden: false });

});
var time = 1000;
var time_new = 2000;
var timer;
var mw_sider = new MwRewardSlider(
        'mw_amount',
        'mw_reward_slider_contaner',
        'mw_slider',
        'mw_reward_decr_handle',
        'mw_reward_incr_handle',
        <?php echo $min?>,
        <?php echo $this->getMaxPointsToCheckout()?>,
        <?php echo $step?>,
       'mw_label_amount',
       'mw_use_max_points'   
        
    );

mw_sider.setPointChange(<?php echo $point?>);

mw_sider.changeRewardPointCallback = runTimer;

$('mw_amount').observe('keyup', function(e){

	amount = this.value;
	clearTimeout(timer);
	timer = setTimeout("mw_sider.setPointChange(amount);",time_new);
	
});

$('mw_use_max_points').observe('click', function(e){
	if(this.checked)
		mw_sider.setPointChange(<?php echo $this->getMaxPointsToCheckout()?>);
	else
		mw_sider.setPointChange(0);
});


function runTimer()
{
	clearTimeout(timer);
	timer = setTimeout("updateRewardPoints();",time);
};

function updateRewardPoints()
{
	var amount = $('mw_amount').value;
	amount = parseInt(amount/<?php echo $step?>) * <?php echo $step?>;
	if(amount < <?php echo $min?>) amount = 0;
	
	$('shopping-cart-totals-contaner').update($('shopping-cart-totals-please-wait').innerHTML);

	new Ajax.Request("<?php echo Mage::getUrl('rewardpoints/checkout/rewardpointspost',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>", {
		   method: 'post',
		   postBody: "rewardpoints="+$('mw_amount').value,
		   onComplete: function(data) {
				$('shopping-cart-totals-contaner').update(data.responseText);
			}
	});
}
</script>

