<div class="navigationWrapper">
		<nav class='main-nav' id="main-navWrapper">
			<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/topBar.phtml')->toHtml(); ?>
			<div class="custom-container DesktopView">
				<ul class="dropdownNavigation">
					<li class="logoWrapper">
						<a class="logo" href='https://md-factor.com/'> 
							<img class="whitelogo" src="<?php echo $this->getSkinUrl('images/logo-blue.png') ?>"> 
							<img class="darklogo" src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>"> 
						</a>
					</li>

					<?php $obj=new Mage_Catalog_Block_Navigation(); $storeCategories=$obj->
				 	getStoreCategories(); Mage::registry('current_category') ? $currentCategoryId=Mage::registry('current_category')->getId() : $currentCategoryId=''; $limit_category=4; $ctr=1; foreach ($storeCategories as $_category): if($ctr <=$limit_category) : ?>
							
						<li>
							<a href="<?php echo mage::app()->getStore()->getHomeUrl().$_category->getUrlKey(); ?>"> <?php $_category=Mage::getModel('catalog/category')->
								load($_category->getId()); ?> <?php echo $_category->
								getName(); ?>
							</a>
							
							<ul>
								<?php $_subcategories=$_category->
								getChildrenCategories(); if (count($_subcategories) > 0){foreach($_subcategories as $_subcategory){$products=Mage::getModel('catalog/category')->load($_subcategory->getId()) ->getProductCollection() ->addAttributeToSelect('*') ->addAttributeToFilter('status', 1) ->addAttributeToFilter('visibility', 4) ->setOrder('price', 'ASC'); echo '
								<li><a href="'.Mage::app()->getStore()->getHomeUrl().$_subcategory->request_path.'">'.$_subcategory->getName().'</a>'; if (count($products) > 0){echo '
								<ul>
									'; foreach($products as $_product){echo '
									<li><a class="thirdlevel" href="'.Mage::app()->getStore()->getHomeUrl().$_product->url_key.'">
									<div class="image">
										<img src="'.$_product->getImageUrl().'">
									</div>
									<div class="desc">
										'.$_product->getName().'
									</div>
									</a></li>
									';}echo '
								</ul>
								';}echo '</li>
								';}}?>
							</ul>
						</li>
					<?php $ctr++; endif; endforeach; ?>

					<li class="sale">
						<a href="<?php echo mage::app()->getStore()->getHomeUrl(); ?>sales">Sale</a>
					</li>
					
					<li>
						<a href="<?php echo mage::getbaseurl(); ?>about">Brand</a>
						
						<ul>
							<li><a href="<?php echo mage::getbaseurl(); ?>about">About Us</a></li>
							<li><a href="https://md-factor.com/blog/">Blog</a></li>
							<li><a href="https://md-factor.com/blog/pressmedia/">Media</a></li>
						</ul>
					</li>
				
				</ul>

				<div class="searchWrapper">
					<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('currency/currency.phtml')->toHtml(); ?>
						<div id="searchInner">
							<form onsubmit="return check_small_search_form()" method="get" action="<?php echo mage::geturl('catalogsearch/result')?>
								"> <button value="" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button><input placeholder="SEARCH PRODUCTS" class="query" "search_query"="" name="q" type="text">
							</form>
						</div>
					</div>
			</div>

			<div class="custom-container MobileView">
				<input id="menu-switch" type="checkbox" />
			    <div id="menu" role="navigation">
			        <div class="searchWrapper">
			        	<div id="searchInner">
							<form onsubmit="return check_small_search_form()" method="get" action="<?php echo mage::geturl('catalogsearch/result')?>
								"> <button value="" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button><input placeholder="SEARCH PRODUCTS" class="query" "search_query"="" name="q" type="text">
							</form>
						</div>
			        </div>            
			        <ul class="menuItems">
					    <?php $obj=new Mage_Catalog_Block_Navigation(); $storeCategories=$obj->
					       getStoreCategories(); Mage::registry('current_category') ? $currentCategoryId=Mage::registry('current_category')->getId() : $currentCategoryId=''; $limit_category=4; $ctr=1; foreach ($storeCategories as $_category): if($ctr <=$limit_category) : ?>
					              
					         <li>
								<input type="checkbox" checked>
					    		<i></i>
					    	<h2>
					    		<?php $_category=Mage::getModel('catalog/category')->load($_category->getId()); ?> <?php echo $_category->getName(); ?>
					     	</h2>
					        
					        <div class="content">
					            <?php $_subcategories=$_category->getChildrenCategories(); if (count($_subcategories) > 0){foreach($_subcategories as $_subcategory){$products=Mage::getModel('catalog/category')->load($_subcategory->getId()) ->getProductCollection() ->addAttributeToSelect('*') ->addAttributeToFilter('status', 1) ->addAttributeToFilter('visibility', 4) ->setOrder('price', 'ASC'); echo '
					               <a href="'.Mage::app()->getStore()->getHomeUrl().$_subcategory->request_path.'">'.$_subcategory->getName().'</a>'; if (count($products) > 0)echo '
					                ';}}?>
					        </div>
					      </li>
					    <?php $ctr++; endif; endforeach; ?>
					</ul>
			    </div>

			    <a class="logo" href='<?php echo mage::app()->getStore()->getHomeUrl(); ?>'> 
					<img class="darklogo" src="<?php echo $this->getSkinUrl('images/logo-brown.png') ?>"> 
				</a>
				<label for="menu-switch" id="menu-toggle"></label>
    
			</div>
		</nav>
	</div>
	